### ISSUE TITLE
Config screen goes blank when switching tabs - 201.5.2

### ISSUE THREAD

**Issue by Slooshie1** [mrbuilder1961/WheresMyChatHistory#100]
### Description
When I initially go into the config screen, everything is fine; the Timestamp tab looks fine, and I can change the configuration of it and save, but when I switch to a different tab, such as Hover Info, the config screen goes blank with the exception of the tabs, and going back to the Timestamp tab, the Timestamp tab becomes invisible as well. Also, when in a server and this happens I cannot leave the menu without closing the game, not even with ESC key.

### How to reproduce
1. Install chat patches 201.5.2, YetAnotherConfigLib 3.0.3, and mod menu 7.1.0
2. Use mod menu to open the config screen for chat patches
3. Select a new menu tab in the config menu

### Expected result
Config screens should render normally and not become invisible

### Log file link
[latest.log](https://mclo.gs/0Ccmbag)

### Specs and Details
Required information:
- Windows 11 Home
- Chat Patches 201.5.2
- Quilt Loader 0.19.2 and QFAPI 7.0.5 with QSL 6.0.4
- YetAnotherConfigLib 3.0.3 and Mod Menu 7.1.0
- Mods:
![image](https://github.com/mrbuilder1961/ChatPatches/assets/90230538/ef5b4aa5-2e1d-4588-bd30-14dd653340b4)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/90230538/9a1774be-84c7-43f3-b65e-a99bfdb7f839)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/90230538/ad6cfe63-6173-4a98-b674-178666fb34b7)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/90230538/86aaae93-4712-4a94-bf7e-64712026c5bf)

Optional but suggested information:
- [chatpatches.json](https://mclo.gs/mODkIeh)

### Additional context
![Screenshot 2023-07-13 231404](https://github.com/mrbuilder1961/ChatPatches/assets/90230538/d12fc860-9e71-45a0-8777-eaaf65f28fb5)

**Comment by mrbuilder1961** [comment]
i honestly have no idea what's going on here. i think this a YACL issue, bc when i tested both in dev and in my mod pack it seemed fine. however, xander seems pretty busy in general so this might take a while to fix. (it could also be a problem on Chat Patches end too 🤷)

@isXander when you have a moment, could you take a look at this? thanks!

**Comment by isXander** [comment]
I believe it is Bedrockify causing the issue.

**Comment by mrbuilder1961** [comment]
> I believe it is Bedrockify causing the issue.

@Slooshie1 have you tried this yet?

**Comment by Slooshie1** [comment]
Yeah it was Bedrockify. Weird because in Bedrockify YACL is listed as a blacklisted screen for panoramas

**Comment by mrbuilder1961** [comment]
ok closing this issue as unrelated to chat patches, lmk if anything else comes up or is related.
