### ISSUE TITLE
Subcommand selection (1.20.1)

### ISSUE THREAD

**Issue by M4X809** [mrbuilder1961/WheresMyChatHistory#101]
### Description

Subcommand select with ArrowUp is not working

https://discord.com/channels/1077285607375638529/1077297192659861686/1129438714855165952
https://discord.com/channels/1077285607375638529/1077297192659861686/1129442978843336822

**Comment by mrbuilder1961** [comment]
solution (on vacation, will impl when over):

[targeting here](https://github.com/mrbuilder1961/ChatPatches/blob/1.20.x/src/main/java/obro1961/chatpatches/mixin/gui/ChatScreenMixin.java#L394), insert this above:
```java
if(chatInputSuggestor.keyPressed(keyCode, scanCode, modifiers))
    cir.setReturnValue(true);
```

and this towards the top of the file:
```java
@Shadow private ChatInputSuggestor chatInputSuggestor;
```

**Comment by mrbuilder1961** [comment]
official release fix coming out shortly!
