### ISSUE TITLE
Chat fps drop

### ISSUE THREAD

**Issue by MrRoxandi** [mrbuilder1961/WheresMyChatHistory#102]
### **Description**
I'm not sure exactly what the problem is, but after installing the mod, 
I'm experiencing a drop in fps by about 20-40 frames when opening chat. 
After that, everything goes back to normal.

**Comment by mrbuilder1961** [comment]
- what mod version are you using? 
- https://mclo.gs link?
- `chatpatches.json` file?
- `chatlog.json` file?

i would also appreciate a small video or photo with the f3 debug pie and graph enabled, then opening the chat and sending a message or something.

**Comment by MrRoxandi** [comment]
Disc: I apologize for not providing enough information initially, I'm still new to github and making these kinds of "posts".
After seeing severe fps drops, I pressed F3+D and the chat cleared. The drops have gotten smaller, but are still observed and seem to grow a little bit at a time.
- version: 201.5.2
- `minecraft logs` https://mclo.gs/GqNUnZP
- ```json "time": true,
  "timeDate": "HH:mm",
  "timeFormat": "[$]",
  "timeColor": 10658466,
  "hover": true,
  "hoverDate": "MM/dd/yyyy",
  "hoverFormat": "$",
  "hoverColor": 16777215,
  "counter": false,
  "counterFormat": "\u00268(\u00267x\u0026r$\u00268)",
  "counterColor": 16777045,
  "counterCompact": false,
  "counterCompactDistance": 4,
  "boundary": true,
  "boundaryFormat": "\u00268[\u0026r$\u00268]",
  "boundaryColor": 5636095,
  "chatLog": true,
  "chatWidth": 451,
  "chatMaxMessages": 32767,
  "chatNameFormat": "\u003c$\u003e",
  "shiftChat": 40,
  "messageDrafting": false,
  "searchDrafting": true,
  "hideSearchButton": false,
  "vanillaClearing": false,
  "copyColor": 5636095,
  "copyReplyFormat": "/msg $ "
- `chatlog.json` https://mclo.gs/r638RcM 
- `small vid` https://youtu.be/pgap1pcdY6k
- `mods`

![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/120740818/b3a2e8f6-46a8-40f3-b883-1bc4c87030b0)
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/120740818/2892a344-204b-491b-8568-8f4be8f38699)
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/120740818/2ac41d2e-4649-4cfd-bfbb-4505753338bf)

**Comment by mrbuilder1961** [comment]
ok thanks for all the information, although i noticed the log you sent was from the server and not the client. i apologize, i probably should have specified that, but i need a client side log bc chat patches doesn't do anything server side.

i will continue to look into this, but know it could take a little while. definitely keeping it high priority though!

also: does this happen on other servers and worlds or in any other mod packs? and if anyone you play with uses this version could you ask them? thanks 🙏😊

**Comment by MrRoxandi** [comment]
I did not understand what server log you were talking about because the Minecraft logs I sent you were from the latest.log file. It was in the log folder, as was the chatlog.json file. I hardly ever play in single world, but the same problem is observed there. As for using this mod separately in other mod packs, I didn't see any such drops in version 1.19.4, but I can't prove it as that pack has long since been lost. My friend and colleague who used your mod was the first to point out the frame drop problem, and then rudely abandoned it. Our packs are very different, so I think it is almost irrelevant where this mod stands. Well, and it says here that the problems started after I received an update to 1.20, because before that I suffered with a couple of other mods like: morechathistory, chat utils and a couple of other useful mods, which I safely removed after the release of the chat patches.

**Comment by mrbuilder1961** [comment]
sorry, that was the right log file i misread it. thanks for the other info, i appreciate it. i can understand why your friend would "take a break" if this issue kept happening lol.

now looking into the log a little more, it says there were 2,260 saved messages restored into chat. i'm not sure how much storage that takes up on your computer, but i would consider at least moving that file elsewhere (so chat patches thinks it's empty) and seeing if the problem resolves.

if this does end up being a solution (clearing the chat log), it might take a while as said before bc that would require a lot more data compression shenanigans. this actually makes me wonder if your friend who dropped the mod had a lot of chat log messages too?

**Comment by MrRoxandi** [comment]
We just work as administrators of one minecraft server, it is vital for us to store a lot of messages that appear in chat. I also ask my colleagues to upload the same information that I sent you, maybe it will help in some way. On the subject of the number of posts. My computer is quite powerful (ryzen 7 3700x + 32 GB ddr4 if needed). If you need to allocate more RAM for gaming, no problem. I will also soon try to send you the information of my colleague who has agreed to provide it.

**Comment by MrRoxandi** [comment]
Also about clearing the message log. I did as you asked, then simulated active server chat via command block in single world. The situation happened again, I restarted the game and recorded it on video. I have sent all the necessary files in this post, and the mod list has not changed.
`minecraft logs` https://mclo.gs/gl1aR3u
`chatlogs.json` https://mclo.gs/HL0gXmQ
```json
{
  "time": true,
  "timeDate": "HH:mm",
  "timeFormat": "[$]",
  "timeColor": 10658466,
  "hover": true,
  "hoverDate": "MM/dd/yyyy",
  "hoverFormat": "$",
  "hoverColor": 16777215,
  "counter": false,
  "counterFormat": "\u00268(\u00267x\u0026r$\u00268)",
  "counterColor": 16777045,
  "counterCompact": false,
  "counterCompactDistance": 4,
  "boundary": true,
  "boundaryFormat": "\u00268[\u0026r$\u00268]",
  "boundaryColor": 5636095,
  "chatLog": true,
  "chatWidth": 451,
  "chatMaxMessages": 16384,
  "chatNameFormat": "\u003c$\u003e",
  "shiftChat": 40,
  "messageDrafting": false,
  "searchDrafting": true,
  "hideSearchButton": false,
  "vanillaClearing": false,
  "copyColor": 5636095,
  "copyReplyFormat": "/msg $ "
}
```
`video` https://youtu.be/RzgMLcwoj4I

**Comment by MrRoxandi** [comment]
Also, here's some information from a colleague of mine
`mod list` 
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/120740818/6699d02d-3ce1-4f78-bbf8-ad845dc52048)
`chatlog.json` https://mclo.gs/PA7kqcP
`minecraft log` https://mclo.gs/uOCiMOO
`chatpatches.json`
```json
{
  "time": true,
  "timeDate": "HH:mm:ss",
  "timeFormat": "[$]",
  "timeColor": 10658466,
  "hover": true,
  "hoverDate": "MM/dd/yyyy",
  "hoverFormat": "$",
  "hoverColor": 16777215,
  "counter": false,
  "counterFormat": "\u00268(\u00267x\u0026r$\u00268)",
  "counterColor": 16777045,
  "counterCompact": true,
  "counterCompactDistance": 7,
  "boundary": true,
  "boundaryFormat": "\u00268[\u0026r$\u00268]",
  "boundaryColor": 5636095,
  "chatLog": true,
  "chatWidth": 403,
  "chatMaxMessages": 32767,
  "chatNameFormat": "\u003c$\u003e",
  "shiftChat": 30,
  "messageDrafting": true,
  "searchDrafting": true,
  "hideSearchButton": false,
  "vanillaClearing": false,
  "copyColor": 5636095,
  "copyReplyFormat": "/msg $ "
}
```
`video` 

https://github.com/mrbuilder1961/ChatPatches/assets/120740818/74546d33-d484-4568-810c-cd5544b00458

**Comment by mrbuilder1961** [comment]
thank you so much for all the information!! i've been pretty busy and continue to be, but i will try and reproduce the issue and see if i can track down where the bottleneck is. sorry to keep you waiting with a laggy mod, hope to get this fixed ASAP 🤞🙏❤️

**Comment by MrRoxandi** [comment]
It's not a big deal. The situation is not as unpleasant as it may seem. A broken tab selector is more of a problem.
But I really hope you do well :)

**Comment by mrbuilder1961** [comment]
Still pretty busy, but I've been able to get my hands on a profiler and i can reproduce the issue. so when i have some time, this shouldn't be terribly hard to get under control. thanks for the patience 🙏 ❤️
