### ISSUE TITLE
Certain mods make the game crash

### ISSUE THREAD

**Issue by realFusionFusion** [mrbuilder1961/WheresMyChatHistory#111]
### Description
Mods from the modpack Simply Optimized version 8.2.2 + Chat Patches + Mod Menu make the game crash whenever you open up the settings for Chat Patches

### How to reproduce
1. Go to mod menu.
2. Open settings and notice how the game crash.

### Expected result
The game shouldn't crash.

### Log file link
https://pastebin.com/kmsyLxzt

### Specs and Details
Required information:
- Windows 10
- Mod version 201.5.5
- Fabric API version 0.87.0
- YetAnotherConfigLib version 3.0.2 and Mod Menu version 7.2.1

**Comment by mrbuilder1961** [comment]
try updating yacl

**Comment by realFusionFusion** [comment]
I updated YACL and that seems to work pretty well. Now the only problem is whenever I open my Minecraft with all of my mods the game really likes to crash given some time. I do not think that this is related to Chat Patches. I tried reading the crash page/text that it gave and as a non-coder there does not seem to be anything obvious, maybe it is something obvious for a coder? If you are not sure then who do you think I should ask about this?

Here is the text:
https://pastebin.com/iBdeYug5

**Comment by mrbuilder1961** [comment]
it seems to be related to "clearhhitboxes" mixin method called  `renderHitbox`, but the actual issue is that `MinecraftClient.getCameraEntity()` returns null.

^ all that is coding related, but if you can't figure out the issue on your own make sure to report it to the creator of clearhitboxes.

**Comment by realFusionFusion** [comment]
I removed the mod and OMG it finally stopped crashing! I put so much effort troubleshooting this, thank you so much for the help!! Much, much appreciated.

**Comment by mrbuilder1961** [comment]
i'm glad to hear it! 😄 just make sure to report that issue (if the mod has a site where you can do that) so it can get fixed for everyone. gonna close this as completed 👍
