### ISSUE TITLE
Message counter didn't work when session boundary was off

### ISSUE THREAD

**Issue by MaoYan5985** [mrbuilder1961/WheresMyChatHistory#112]
### Description
![image](https://github.com/mrbuilder1961/ChatPatches/assets/122714639/c3f8c39c-25cd-4a7c-a4cf-2dffe7167637)
When session boundary is off, message counter doesn't work, as the image shown.

### How to reproduce

- install chat patches
- load a world
- go to mod menu, turn off session boundary
- spam messages
- message counter doesn't work
- turn on session boundary
- message counter works

### Expected result
Message counter should work when session boundary is off.

### Log file link

[latest.log](https://mclo.gs/3B0a4TO)

### Specs and Details
Required information:
- Computer OS : Win 10 Pro
- Mod version : chatpatches-201.5.5
- Fabric : fabric-loader-0.14.22  
- API : fabric-api-0.86.1+1.20.1
- YetAnotherConfigLib : yet-another-config-lib-fabric-3.1.0+1.20
-  Mod Menu versions : modmenu-7.2.1
- List of all installed mods 
![image](https://github.com/mrbuilder1961/ChatPatches/assets/122714639/0be49fd0-c985-4508-a570-e55b7381c41e)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/122714639/02f98f1c-08bb-4514-9559-6d7b7586c6cc)

### Additional context
Issue still exists when only using fabric api, mod menu, chat patches and YACL.

**Comment by mrbuilder1961** [comment]
try this https://github.com/mrbuilder1961/ChatPatches/suites/15127864663/artifacts/864400932

**Comment by mrbuilder1961** [comment]
was the issue fixed with that jar or no?

**Comment by MaoYan5985** [comment]
Sorry about late reply. Yes, it's fixed.
