### ISSUE TITLE
Add Global and Local chat

### ISSUE THREAD

**Issue by DonorKrovi** [mrbuilder1961/WheresMyChatHistory#116]
I suggest adding local and global chat for the server as in the most popular plugins. For example, global chat through the !

**Comment by mrbuilder1961** [comment]
i'm not really sure what you mean, could you explain more? also, i don't think this would be possible because this is client side so it doesn't affect the server.

**Comment by mrbuilder1961** [comment]
if you provide some more context i might be able to help but in the meantime i'm going to close this.
