### ISSUE TITLE
Mod Menu freezes on Quilt - Chat Patches 201.5.5

### ISSUE THREAD

**Issue by EJAflatminor** [mrbuilder1961/WheresMyChatHistory#119]
### Description
When using Chat Patches on Quilt 1.20.1, Minecraft freezes when you open Mod Menu. Nothing responds, and you have to forcefully close the game.

### How to reproduce
1. Install Quilt, QFAPI, Chat Patches, YACL, and Mod Menu.
2. Start Minecraft and open Mod Menu.
3. Observe that the game freezes and becomes unresponsive.

### Expected result
I expected Minecraft to not freeze when I opened Mod Menu.

[Log file link](https://mclo.gs/aWyMknP)

### Specs and Details
Required information:
- macOS
- Chat Patches 201.5.5
- Quilt Loader 0.20.2
- Quilted Fabric API 7.2.1
- YetAnotherConfigLib 3.1.1
- Mod Menu 7.2.2

### Additional context
Note that this issue does not occur with Fabric Loader and Fabric API, **or with Chat Patches 201.5.4**.

**Comment by mrbuilder1961** [comment]
okay i'll check what changed between versions. in the meantime, could you take a video or see if anyone else is experiencing the same issue?

**Comment by EJAflatminor** [comment]
Here's a [video](https://streamable.com/n4mh1c) I recorded of the bug.

**Comment by mrbuilder1961** [comment]
i would say that's probably because of the preview images added in 201.5.5, but the screen freezes before even opening the config menu. i can try and reproduce this sometime soon, thanks for the video.

**Comment by mrbuilder1961** [comment]
also, could you try running the same setup w fabric and letting me know if the issue still occurs?

**Comment by Aces-and-Jacks** [comment]
Only happens on quilt. Fabric it runs normally

**Comment by mrbuilder1961** [comment]
i thought this was a YACL issue that was fixed, I wonder if something internal is FAPI and quilt maybe patches it out or something?

@Aces-and-Jacks if it exists could you try sending the `debug.log` file?

@isXander when you have a moment could you skim over this and see if it's caused by YACL itself at all?

@TerraformersMC (hope this is the right user at...) could this have something to do with mod menu's internals?

**Comment by Aces-and-Jacks** [comment]
> @Aces-and-Jacks if it exists could you try sending the `debug.log` file?

Where would that be located?

**Comment by mrbuilder1961** [comment]
same directory as the `latest.log`, however it might not exist.

**Comment by Aces-and-Jacks** [comment]
It doesn't show. There's `chatlog.json` but not `debug.log`

**Comment by mrbuilder1961** [comment]
is this issue still occurring in the current latest version `202.5.7`? i know this issue was opened under `201.5.5` but i haven't backported current updates yet.

**Comment by Aces-and-Jacks** [comment]
Still occurring in latest version

**Comment by mrbuilder1961** [comment]
okay, when i have some free time today i will try and forward this issue to the authors of the potential problem mods. thanks for your patience.

**Comment by mrbuilder1961** [comment]
> Here's a [video](https://streamable.com/n4mh1c) I recorded of the bug.

hey so since it's taken me so long to figure out this issue, the video link expired. could you record a new one and i will save it this time? i apologize for all these inconveniences :(

**Comment by Aces-and-Jacks** [comment]
Did you want a video of what happens when this is triggered/what led up to it?

**Comment by mrbuilder1961** [comment]
yes!

**Comment by Aces-and-Jacks** [comment]
https://github.com/mrbuilder1961/ChatPatches/assets/106651342/a1f473f2-2e40-49af-9860-dfb2c6222652

Not sure if this is what your looking for but here's one

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/c5eX22x and the log for it

**Comment by mrbuilder1961** [comment]
i tested it myself on 1.20.2 with fapi 0.90.7, mod menu 8.0.0, yacl 3.2.1, and chat patches 202.5.7, and it was fine.

i tested it again on 1.20.1 with qfapi 7.4.0+0.90.0, mod menu 7.2.2, yacl 3.2.1, and chat patches 201.5.5: the issue didn't happen there either.

i tested the original mod set and also did not experience the issue:
> Specs and Details
> Required information:
> ```macOS
> Chat Patches 201.5.5
> Quilt Loader 0.20.2
> Quilted Fabric API 7.2.1
> YetAnotherConfigLib 3.1.1
> Mod Menu 7.2.2

i tested the original mod set (detailed above) with updated versions for yacl (3.2.1) and qfapi (7.4.0+0.90.0) and i still had no problem.

so either A) outdated mod sets are being used, B) something else is at play here and it isn't being documented or logged, for whatever reason, or C) my computer has something else going on behind the scenes. let me know if any of these work for you guys or if i am blatantly forgetting something.

**Comment by Aces-and-Jacks** [comment]
Minecraft 1.20.1
```
Chat Patches 201.5.5
Quilted Fabric API 7.4.0+0.90.0-1.20.1
Quilt loader 0.21.2
Mod Menu 7.2.2
YetAnotherConfigLib 3.2.1+1.20
```
Still happens for me

**Comment by Aces-and-Jacks** [comment]
Tested your mod versions as well and same issue

**Comment by Aces-and-Jacks** [comment]
Here's for the first https://mclo.gs/3ZYu9Ho

And here's for the second with your versions https://mclo.gs/HVf0MhX

Not sure if you needed both but just incase

**Comment by Aces-and-Jacks** [comment]
Well the logs may not help but after `Generating YACL screen` it freezes. I'm using prism launcher so maybe it's that?

Edit: Tried it on modrinth launcher and same issue so it's probably not a launcher issue

**Comment by Aces-and-Jacks** [comment]
Ok so actually the game doesn't freeze. I was clicking around and even tho the screen was stuck on the mod page it still made clicking sounds and I somehow got to the `preparing for world generation` screen, so the screen is frozen but it still processes clicks maybe? Tho now it's stuck on that screen

**Comment by Aces-and-Jacks** [comment]
https://github.com/mrbuilder1961/ChatPatches/assets/106651342/89371de7-6f30-4171-89dc-8841b07fe474

So here is a more accurate version of what happens

**Comment by Aces-and-Jacks** [comment]
Can't really show it in the minecraft logs I guess so those probably wouldn't help

**Comment by mrbuilder1961** [comment]
okay, im thinking maybe it's a macOS issue, because it looks like you and OP both had the issue occur with it. I have an old mac lying around somewhere, I might be able to test these modsets out on there. thanks for all the new info!

**Comment by mrbuilder1961** [comment]
oh also, if it isn't too much trouble, could you export the mod sets that were causing the issue for you as prism launcher zipped files, and upload them here? it would greatly streamline my testing process!

**Comment by Aces-and-Jacks** [comment]
No problem. didn't think about it being a mac issue. It could be I'm on an older OS so if that's the case then I'll probably update sometime next month...I dislike the new UI settings menu which is why I haven't updated but more and more lose support for my version


And sure. Here it is
[chat test main.zip](https://github.com/mrbuilder1961/ChatPatches/files/13401698/chat.test.main.zip)

**Comment by mrbuilder1961** [comment]
is this still present in 201.5.6?

**Comment by Aces-and-Jacks** [comment]
yes

**Comment by Aces-and-Jacks** [comment]
wait, I forgot to read over chat. Thought this was something else

**Comment by Aces-and-Jacks** [comment]
Yeah, currently it isn't loading up. Stays stuck on loading screen. Not sure if that'd count as a new issue or not but current version I can't test. I'm gonna try and see which version it started on tho

**Comment by Aces-and-Jacks** [comment]
Yup, had a feeling. So the mod menu issue is still there, but I can't test with any version of `YetAnotherConfigLib` past `3.2.2+1.20` since something is making it not load on quilt. So probably ignore the loading issue since it's another mod. For everything else I'm using 
`Chat Patches 201.5.6 
Quilted Fabric API 7.7.0+0.92.2-1.20.1 
Quilt loader 0.27.0 
Mod Menu 7.2.2 
YetAnotherConfigLib 3.2.2+1.20`

**Comment by Aces-and-Jacks** [comment]
Tho I haven't played on quilt for a while. If you end up not being able to solve this I'm fine with that

**Comment by mrbuilder1961** [comment]
okay i'm going to mark this as unrelated but if anything else comes up feel free to reopen it. if you have the time, you should open an issue on the yacl github about this
