### ISSUE TITLE
Suggestion: Restoring chat history after exiting the game

### ISSUE THREAD

**Issue by balabol87** [mrbuilder1961/WheresMyChatHistory#12]
Hi.
I would like to suggest adding a function to restore the chat after restarting the game, by loading the history from the latest.log file into .minecraft logs folder, or by saving and loading back your own log (it would probably be better, because the last.org file seems to change as far as i know and each time it will not load the entire history according to the maximum message limit), or something like that, so as not to lose the chat when you full restart the game.
Maybe even such an idea was already in mind, anyway it would be great to see such a function in the future. If its implementation is possible.
This function can also be made optional with toggle on/off, although it seems to me that if it appears, then hardly anyone will want to turn it off :sunglasses:

**Comment by mrbuilder1961** [comment]
Yeah I'll probably do this eventually, if not in the next update.
