### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by jacklollz2** [mrbuilder1961/WheresMyChatHistory#120]
The contents of this have been erased.

**Comment by mrbuilder1961** [comment]
i can make it not required, but for most people it simplifies config usage for novice modded-Minecraft players. i could try and look into this but atm it's very low priority.

**Comment by jacklollz2** [comment]
It's just I don't think I've ever seen a mod require this. What if someone
is using a custom mod menu as well?

**Comment by mrbuilder1961** [comment]
i apologize, i was under the impression YACL required mod menu too. i'll just switch it to recommended.

**Comment by mrbuilder1961** [comment]
built jar is available in `/build/libs/` if you really need the jar now: https://github.com/mrbuilder1961/ChatPatches/suites/16240088395/artifacts/927512354
