### ISSUE TITLE
[please] Remove the 255-letter character limit in the chat bar

### ISSUE THREAD

**Issue by vocaloidkiss** [mrbuilder1961/WheresMyChatHistory#121]
Please remove the 255-letter character limit in the chat field

**Comment by vocaloidkiss** [comment]
And， If you don't mind，let chat bar text selectable using mouse sliding，please。
this And， If you don't mind，let chat bar text selectable using mouse sliding，please
This function can be delayed, and the first thing is to lift the restrictions.

**Comment by mrbuilder1961** [comment]
unfortunately the character limit is enforced by the server, so if i removed it users would be kicked from servers every time 256+ messages were sent.

and i have no idea what you're saying about "mouse sliding," but if you mean chat message copying just right click on a message.

**Comment by vocaloidkiss** [comment]
thanks
