### ISSUE TITLE
Copy Raw feature have formatting leftovers - 201.5.5 

### ISSUE THREAD

**Issue by Fluboxer** [mrbuilder1961/WheresMyChatHistory#122]
### Description
Basically raw copy feature is broken and it copies some leftover formatting codes
ChatUtils also had this problem (and still have it to some degree)
In my case it happens when playing on Hypixel Skyblock 
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/f8431f04-97a0-4538-b590-b69d60ad02c8)
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/381fb4bf-b5ca-4ade-a953-edfba1e16b10)

### How to reproduce
1. Get Chat Patches
2. Login to Hypixel 
3. Try to copy player's message

### Expected result
Clean message without any formatting leftovers 

### Log file link
https://pastebin.com/b9zRswZz

### Specs and Details
Required information:
- Astra Linux (5.4.0)
- 201.5.5; also tried recent version from actions tab (201.5.6)
- Fabric 0.14.22; Fabric API 0.89.0
- YACL 3.1.0; ModMenu 7.2.1
- Mods:
  [✔] 1.19-fullbright-1.0.2
  [✔] borderless-mining-1.1.8+1.20.1
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.10.106
  [✘] chat-utils-1.10.1+1.20.1.jar (disabled)
  [✔] chatpatches-201.5.6
  [✔] cloth-config-11.1.106-fabric
  [✔] coordinatelist-1.5.0-1.20
  [✔] dashloader-5.0.0-beta.2+1.20.0
  [✔] Debugify-1.20.1+2.0
  [✔] dulkirmod-fabric-1.0.1
  [✔] enhancedblockentities-0.9+1.20
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] fabric-api-0.89.0+1.20.1
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] ferritecore-6.0.0-fabric
  [✔] ImmediatelyFast-1.2.3+1.20.1
  [✔] indium-1.0.25+mc1.20.1
  [✔] language-reload-1.5.8+1.20.1
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] memoryleakfix-fabric-1.17+-1.1.2
  [✔] midnightlib-fabric-1.4.1.1
  [✔] modelfix-1.14-fabric
  [✔] modmenu-7.2.1
  [✔] moreculling-1.20.1-0.19.0
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] skyblocker-1.13.0-beta-a48247f+1.20.1
  [✔] sodium-extra-0.5.1+mc1.20.1-build.112
  [✔] sodium-fabric-mc1.20.1-0.5.2
  [✔] yet-another-config-lib-fabric-3.1.0+1.20
  [✔] Zoomify-2.11.0

Optional but suggested information:
- [chatlog.json](https://pastebin.com/ct25pMkD) 
- chatpatched.json:
- `{
  "time": false,
  "timeDate": "HH:mm:ss",
  "timeFormat": "[$]",
  "timeColor": 16733695,
  "hover": false,
  "hoverDate": "MM/dd/yyyy",
  "hoverFormat": "$",
  "hoverColor": 16777215,
  "counter": true,
  "counterFormat": "\u00268[\u00267x\u0026r$\u00268]",
  "counterColor": 16777045,
  "counterCompact": false,
  "counterCompactDistance": 0,
  "boundary": true,
  "boundaryFormat": "\u00268[\u0026r$\u00268]",
  "boundaryColor": 5636095,
  "chatLog": true,
  "chatHidePacket": true,
  "chatWidth": 0,
  "chatMaxMessages": 16384,
  "chatNameFormat": "\u003c$\u003e",
  "shiftChat": 10,
  "messageDrafting": false,
  "searchDrafting": true,
  "hideSearchButton": true,
  "vanillaClearing": false,
  "copyColor": 5636095,
  "copyReplyFormat": "/msg $ "
}`

**Comment by mrbuilder1961** [comment]
does it do the same thing when you click the Formatted button? otherwise that's intended behavior, it's supposed to keep them when clicking "Raw."

**Comment by Fluboxer** [comment]
> does it do the same thing

yes

![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/3c80f0fa-c5c0-4e40-ae81-9722afac492b)
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/69bdd05d-e11e-4748-aeb4-4ef7b7960cd0)
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/033f617e-5482-4d3b-8f7d-67baef2acb6c)

**Comment by Fluboxer** [comment]
for context: expected behavior, this is how it acts on some unaffected messages, like bz notification
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/30c090f3-364c-42bc-bb38-f68095a0ba07)
![изображение](https://github.com/mrbuilder1961/ChatPatches/assets/36457056/341bccb5-29f1-427c-b40c-dbb02e693483)
