### ISSUE TITLE
Mod Requires Modmenu - 201.5.5

### ISSUE THREAD

**Issue by the-n1n** [mrbuilder1961/WheresMyChatHistory#124]
### Description
This mod requires Mod Menu when Mod Menu Alternatives like Catalogue and Menulogue are there.

### How to reproduce
Delete Mod Menu, Run the Game

### Expected result
Runs as per normal without requiring Mod Menu or requires Mod Menu or Menulogue/Catalogue.

### Log file link
https://pastebin.com/xxuamHJW

### Specs and Details
Required information:
- Windows 11
- 201.5.5
- 0.89.0 - Loader-0.14.22-1.20.1
- YetAnotherConfigLib V3.1.1 (No Mod Menu)
- ![Screenshot 2023-09-28 200558](https://github.com/mrbuilder1961/ChatPatches/assets/67731349/4019a709-88fb-4fcf-877b-436c8ead8fe9)

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
Menulogue and Catalogue are Alternatives for Mod Menu with a nicer UI and uses the Mod Menu configuration tools.
[Menulogue](https://www.curseforge.com/minecraft/mc-mods/menulogue) and [Catalogue (Fabric)](https://www.curseforge.com/minecraft/mc-mods/catalogue-fabric)

**Comment by the-n1n** [comment]
Note, I took the screenshot after disabling Chat Patches. These all work without Mod Menu and the game loads properly. With Mod Menu installed and Chat Patches everything runs properly.

**Comment by mrbuilder1961** [comment]
i'd just need to add integration with those mods first, so if you install them you can still edit the config. that's also a very PR-able thing, if you really really want it done.
