### ISSUE TITLE
Mod refuses to launch on 1.20.2 - 201.5.5

### ISSUE THREAD

**Issue by RoonMoonlight** [mrbuilder1961/WheresMyChatHistory#125]
### Description
Chat Patches refuses to launch on 1.20.2. Need 1.20.2 support.

### How to reproduce
1. Install mod
2. Run the game
3. Incompatible mod set error appears

### Expected result
It should be able to run 1.20.2 without any issues.

### Log file link
[https://mclo.gs/OTGaqtO](Here)

### Specs and Details
Required information:
- Windows 11 22H2
- 201.5.5
- Fabric Loader 0.14.22 / Fabric API 0.89.3
- YACL 3.2.1 / Mod Menu 8.0.0

### Additional context
None.

**Comment by mrbuilder1961** [comment]
this isn't a bug, it's not compatible because 1.20.2 brought breaking changes and is conflicting heavily with the mod. join the discord if you want updates
