### ISSUE TITLE
Suggestion: Block Duplicate Messages Toggle

### ISSUE THREAD

**Issue by JustAHuman-xD** [mrbuilder1961/WheresMyChatHistory#13]
Add a option to the config to block duplicate chat messages and maybe give some sort of indicator they are there, like the dupe chat count. However instead of showing the full message and the count just blocking the message and refreshing the count. If that is possible anyway

**Comment by JustAHuman-xD** [comment]
Okay upon further looking into I see what i was missing!
If the message is only 1 line long it will do what i described above.
However if it is more than 1 line long it will not block it going into the chat!
ie. I think its a bug

**Comment by mrbuilder1961** [comment]
I'm sorry but could you send a picture of what you're explaining? I don't really understand what exactly is happening.

**Comment by JustAHuman-xD** [comment]
Yeah sorry!
So typically whenever there are duplicate messages this happens:
![image](https://user-images.githubusercontent.com/65748158/171051703-4eac8124-4b3d-4735-a18e-b46879dc420c.png)

However if the message is more than 1 line long, this happens:
![image](https://user-images.githubusercontent.com/65748158/171051759-7438eae0-c214-4469-8bd5-ba767e0e2963.png)

**Comment by JustAHuman-xD** [comment]
It will stop the last line from being repeated but the first line still gets spammed if that makes sense

**Comment by mrbuilder1961** [comment]
Oh okay thanks so much, I understood it I just wasn't sure what it looked like. I'll fix this ASAP.

**Comment by JustAHuman-xD** [comment]
Oh also another thing i noticed but i dont know if this is intended or not. 
So with the whole stacking of duplicate messages. 
If a dupe message is sent after the previous same message fades away. 
Its impossible to know that you got that message unless you open your chat
I think it would be useful to have it just show the new message with the x#

**Comment by mrbuilder1961** [comment]
That's weird, I thought i fixed that. would you mind sending a video of what you're talking about, to clarify?

**Comment by JustAHuman-xD** [comment]
It appears the latest update fixed it!
