### ISSUE TITLE
Add Setting for Playername Color

### ISSUE THREAD

**Issue by CepheidVariable** [mrbuilder1961/WheresMyChatHistory#133]
**Is your feature request related to a problem? Please describe.**
Being able to change the playername text color would help to visually breakup the message from the sender's name.

**Describe the solution you'd like**
Add a 'Playername Color' setting just like with 'Timestamp Color.'

**Comment by mrbuilder1961** [comment]
great idea! in the meantime, you can use & + a formatting code to color names. see the config -> help -> formatting codes !

**Comment by CepheidVariable** [comment]
Thank you for the advice. I did not realize that formatting codes were accepted.
