### ISSUE TITLE
1.20.4 Crashes after taking screenshot with F2

### ISSUE THREAD

**Issue by DuskScorpio** [mrbuilder1961/WheresMyChatHistory#138]
### Description
1.20.4 crashes when pressing Esc after taking screenshot with F2

### How to reproduce
Install 1.20.4 version and the mods listed below, open single player world and press F2, press Esc

### Expected result
Not crash

### Log file link
Crash report: https://mclo.gs/vJFIPAC

### Specs and Details
Required information:
- Computer OS: Windows 11 Home Single Language
- Mod version: 204.6.1
- Fabric Loader 0.15.2
- Fabric API 0.91.3+1.20.4
- YetAnotherConfigLib 3.3.1+1.20.4
- Mod Menu 9.0.0-pre.1
- List of all installed mods (can be a list *copied* from a log file **OR** a screenshot of the mods folder)
None

**Comment by mrbuilder1961** [comment]
ive determined the cause of this issue, however i'm not entirely sure how to fix it yet. ill figure it out asap, in the meantime the best solution would be to disable the chat log.
