### ISSUE TITLE
Ctrl + C when chat is open Copies chat log

### ISSUE THREAD

**Issue by Laifsyn** [mrbuilder1961/WheresMyChatHistory#14]
I want to copy the text message instead. How do I do it?

**Comment by mrbuilder1961** [comment]
I assume you mean the full message rather than the single line?

**Comment by Laifsyn** [comment]
whatever I'm writing into the chat I mean.(Like ``/fill [coords1]`` Ctrl+C > move> Ctrl+v write new coords

**Comment by mrbuilder1961** [comment]
Could you draw a diagram of what you're trying to explain? I have no idea what that command is supposed to do.

**Comment by Laifsyn** [comment]
so a summary, Ctrl+C doesn't copy chat(not chat log). 
![image](https://user-images.githubusercontent.com/99366187/172059248-ae6526d7-e1de-418e-8798-d1cacefaad69.png)

**Comment by mrbuilder1961** [comment]
I think you're misunderstanding how the copy function works. you hover over a chat message and press control + C and then it copies that line to your clipboard. It seems like you are expecting it to copy from the input box which is already a vanilla feature.

**Comment by Laifsyn** [comment]
No. Not even hovering over the input box allowed me to copy the text of the input box is what I meant. Your method is like overriding Vanilla's method to copy the inputbox content

**Comment by mrbuilder1961** [comment]
Oh okay that makes much more sense, thank you. I will look into this and see what i can do.
