### ISSUE TITLE
Action not allowed: OPEN_FILE version 204.6.1

### ISSUE THREAD

**Issue by ItzSkyReed** [mrbuilder1961/WheresMyChatHistory#142]
### Description
Crash due to "Action not allowed: OPEN_FILE"

### How to reproduce
I don't know, it just randomly crashed

### Expected result
My minecraft crashed

### Log file link

[Log](https://mclo.gs/m7bYHEo)

### Specs and Details
Required information:
All the information is in log

Optional but suggested information:
I've got default mod settings

### Additional context
I think nothing

**Comment by mrbuilder1961** [comment]
already fixed in #138, update releasing (probably) today!
