### ISSUE TITLE
Accurate duplicate counter

### ISSUE THREAD

**Issue by ItzSkyReed** [mrbuilder1961/WheresMyChatHistory#144]
**Is your feature request related to a problem? Please describe.**
Duplicate counter doesn't compare click event or hover event or may be something more, so it is not accurate

There are two commands:
`/tellraw @a {"text":"TheSameText","hoverEvent":{"action":"show_text","contents":"first message"}}`
`/tellraw @a {"text":"TheSameText","hoverEvent":{"action":"show_text","contents":"second message"}}`

but for duplicate counter they are the same while hover event is different

**Describe the solution you'd like**

Add an additional accurate mode that will compare all parts of the message

**Describe alternatives you've considered**

Perhaps you can simply not use duplicate counter if there is a hover event, click event or some other tag, for the benefit of optimizations

**Additional context**

Nothing to say

**Comment by mrbuilder1961** [comment]
yeah this is a good idea. thanks for the suggestion
