### ISSUE TITLE
remove the dependency for mod menu - 201.5.5

### ISSUE THREAD

**Issue by Kynz0** [mrbuilder1961/WheresMyChatHistory#145]
**Is your feature request related to a problem? Please describe.**
iam using quilt and i dont want to use mod menu iam using a different mod that does the same thing and supports mod menus api:
https://www.curseforge.com/minecraft/mc-mods/catalogue-fabric - the mod iam using
https://www.curseforge.com/minecraft/mc-mods/menulogue - the mod that adds compatibility with mod menu based configs and such

**Describe the solution you'd like** 
just remove the mod menu from the dependencies so i can start he mod without it please (add a suggestion to use it somewhere instead)

**Describe alternatives you've considered**
ig you could add a screen that pops up when you first start the mod that says something like "installing mod menu is highly recommended" "mod menu link"

**Additional context**
its just annoying that iam forced to have the mod menu mod installed. i get that 99% of people will use it anyway and ive only found out very recently about this new alternative as probably you are right now but please just remove it thank you :D

image for context:
![image](https://github.com/mrbuilder1961/ChatPatches/assets/90714597/b2090e74-9a58-45f3-a638-23f1c43f9a06)

**Comment by mrbuilder1961** [comment]
@abidbmt this is the original. just so you guys know this issue is fixed in newer versions, i've just been really busy and haven't had time to backport. if you can i strongly suggest updating, in the meantime i can potentially get a dev build out if you really want to fix this.

**Comment by abidbmt** [comment]
> @abidbmt this is the original. just so you guys know this issue is fixed in newer versions, i've just been really busy and haven't had time to backport. if you can i strongly suggest updating, in the meantime i can potentially get a dev build out if you really want to fix this.

Ah I see, yeah it would be very nice if you could fix it for 202.5.5 since im bound to 1.20.1

**Comment by mrbuilder1961** [comment]
should be fixed here: https://github.com/mrbuilder1961/ChatPatches/actions/runs/8911408790/artifacts/1464173009

see https://github.com/mrbuilder1961/ChatPatches/blob/1.20.2/README.md#how-to-access-beta-releases for an explanation of how to use it
