### ISSUE TITLE
(1.18.2) Config resets

### ISSUE THREAD

**Issue by MommaMeow** [mrbuilder1961/WheresMyChatHistory#15]
Hi! Sorry if this has already been reported (new to github and it's navigation).
I have everything defaulted as the mod comes (since I see no reason to adjust the colours/etc)

I have a reoccurring issue where every time I start up my Minecraft client and log into a server I play on, my chat chats/text/etc defaults to bright pink/yellow.
![image](https://user-images.githubusercontent.com/107274515/173127626-f2150efc-e64c-41df-be67-ad8a407ad5fb.png)

I have gone into the configs files in .minecraft, changed the 'reset all settings' to false/no (as well as done it thru mod menu) - this temp resolves the issue, but upon closing the client and relaunching it returns to the image above.

I have also just completely removed the config file from .minecraft which recreates itself upon opening the client, and it works for that session, but if I were to close out and reopen again, it reverts back to the image above.

I am at a loss of what I can do to keep my settings saved.

**Comment by mrbuilder1961** [comment]
Make sure your mod version is up-to-date, as I removed a few of the things you mentioned in more recent updates. Here is the most recent version file for 1.18.x, not sure if this is on CurseForge but you can find it in the latest release: https://github.com/mrbuilder1961/WheresMyChatHistory/releases/download/1.4.6.1/wmch-1.4.6.1.jar

**Comment by MommaMeow** [comment]
Holy moly, that update sure did fix it! I wasn't aware a new version came out, so I apology for wasting your time. I do appreciate everything you've done with it, and the help you've given. :)
