### ISSUE TITLE
Cant change settings using modmenu

### ISSUE THREAD

**Issue by DiablicaNati** [mrbuilder1961/WheresMyChatHistory#150]
I have this error in Minecraft 1.20.4 with fabric 0.15.7(fabric api 0.96.4), and modmenu 9.0.0
(I cant just edit setting with mod menu)
Chat Patches version is 204.6.2

![image](https://github.com/mrbuilder1961/ChatPatches/assets/83217773/35ba5f8c-e752-4326-8a69-58c28025be8c)

PS. Sorry for my bad English and sorry if I wrote this report wrong

**Comment by mrbuilder1961** [comment]
what version of yacl are you using? also can you send the log file on https://mclo.gs please?

**Comment by mrbuilder1961** [comment]
fixed a while ago, use chat patches `204.6.5` or newer
