### ISSUE TITLE
The client crashes when right-clicking on chat text (1.20.1,201.5.5)

### ISSUE THREAD

**Issue by FallingSand** [mrbuilder1961/WheresMyChatHistory#153]
### Description
The client crashes immediately when right-clicking on chat text(In multiplayer)

### How to reproduce
right click on chat text

### Expected result
Client crashes
Description: mouseClicked event handler
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1

### Log file link
https://mclo.gs/9uCc5Qy
or
https://api.mclo.gs/1/raw/9uCc5Qy

### Specs and Details
information:
- Microsoft Windows 11 22h2 x86_64 (Operating System: Windows 11 (amd64) version 10.0)
- mod version : 201.5.5
- fabric-api: Fabric API 0.91.1+1.20.1
- fabric: 0.15.6
- YetAnotherConfigLib 3.2.1 ; Mod Menu 7.2.2
- 	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		amecs: Amecs 1.3.10+mc.1.20.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.1.13
		auto_third_person: Auto Third Person 2.1
		badpackets: Bad Packets 0.4.3
		balm-fabric: Balm 7.2.1
		bedrockminer: Bedrock Miner 1.20.1-1.2.1
		beehave: beehave 0.0.3
		betterf3: BetterF3 7.0.2
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.9.0
		blockmeter: Block Meter 1.11.0
		blocktuner: BlockTuner 1.1.1
		boatiview: Boat Item View Fabric 0.0.5
		bookshelf: Bookshelf 20.1.9
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.4
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.4
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.4
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.4
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.4
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.4
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.4
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.4
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.4
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.4
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.4
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.4
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.4
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.4
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.4
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.4
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.4
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.4
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.4
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.4
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.4.0
		carpet: Carpet Mod 1.4.112+v230608
		carpet-addons-not-found: Carpet Addons Not Found 1.3.1
		carpet-ams-addition: Carpet AMS Addition 2.29.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.17
			mixinextras: MixinExtras 0.3.5
		carpet-extra: Carpet Extra 1.4.115
		carpet-fixes: Carpet Fixes 1.20-1.16.1
		carpet-org-addition: Carpet Org Addition 1.23.0
		carpet-takeneko-addition: TakeNeko Carpet Addition unspecified
		carpet-tctc-addition: Carpet TCTC Addition 2.2.212+46263e3-stable
			carpet-tctc-addition-1_20_1: Carpet TCTC Addition for 1.20.1 2.2.212+46263e3-stable
		carpet-tis-addition: Carpet TIS Addition 1.55.0
			conditional-mixin: conditional mixin 0.4.1
		carpetgamerules: Carpet Gamerules 2.2.1
		cavedust: Cave Dust 1.4.1
			kirin: Kirin UI 1.15.0
		caxton: Caxton 0.5.5+1.20.1-FABRIC
			mm: Manningham Mills 2.3
		chat_heads: Chat Heads 0.10.31
		chatpatches: Chat Patches 201.5.5
		chunksfadein: Chunks Fade In 1.0.5-1.20.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chunky: Chunky 1.3.92
		chunkyborder: ChunkyBorder 1.1.53
		clientcommands: Client Commands 2.8.5
			betterconfig: BetterConfig 1.2.1
			clientarguments: clientarguments 1.5
		clientcrafting: clientcrafting Mod 1.20.1-1.8
		clienttweaks: Client Tweaks 11.1.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		cmdkeybind: Command Macros 1.6.3-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		collective: Collective 7.30
		controlling: Controlling For Fabric 12.0.2
		cpm: Customizable Player Models 0.6.14c
		cpmsvcc: CPM SVC Compat 1.2.0
		disc_jockey: Disc Jockey 1.3.0
		discarpet: Discarpet 1.5.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.12.6
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.12.6
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.12.7.1
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			com_squareup_okhttp3_logging-interceptor: logging-interceptor 4.9.3
			com_squareup_okhttp3_okhttp: okhttp 4.9.3
			com_squareup_okio_okio: okio 2.8.0
			io_vavr_vavr: vavr 0.10.4
			org_javacord_javacord-api: javacord-api 3.8.0
			org_javacord_javacord-core: javacord-core 3.8.0
		disco: Disco — Custom Music Discs 2.0.8
		double_hotbar: Double Hotbar 1.3.1-mc1.20.1-fabric
		dynamic_fps: Dynamic FPS 3.3.3
		dynamiccrosshair: Dynamic Crosshair 7.4.4+1.20
			yaclx: YetAnotherConfigLibExtensions 1.12+1.20.2
		dynamiclights: Dynamic Lights 1.7.1+mod
		dynamictrim: DynamicTrim 1.4.1
			mixinsquared: MixinSquared 0.1.1
		easierchests: EasierChests 1.20-fabric0.83.0-1.7.1
		easiercrafting: EasierCrafting 1.20-fabric0.83.0-1.7
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.5+1.20
		easiervillagertrading: EasierVillagerTrading 1.20-fabric0.83.0-1.5.4
		eatinganimationid: Eating Animation 1.20+1.9.5
		entity_model_features: Entity Model Features 1.2.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		entityinformation: Entity Information 3.2
		essentialaddons: Essential Addons 1.2.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		explayerenderer: ExtraPlayerRenderer 2.3.1
		fabric-api: Fabric API 0.91.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.23+1802ada577
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.6
		forgeconfigapiport: Forge Config API Port 8.0.0
		g4mespeed: G4mespeed 1.4.5
			g4mespeed-ui: G4mespeed UI 0.9.10
		gca: GugleCarpetAddition 2.7.0-1.20.1
		held-item-info: Held Item Info 1.5.0
		ias: In-Game Account Switcher 8.0.2
		imblocker: IMBlockerFabric 1.0.24
		indium: Indium 1.0.30+mc1.20.4
		intricarpet: IntriCarpet 2.0.1
		inventoryhud: Inventory HUD + 3.4.18
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		invfullnot: Inventory Full Notifier 1.1.1
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemfilters: Item Filters 2001.1.0-build.59
		itemscroller: Item Scroller 0.20.0
		jade: Jade 11.7.0
		jadeaddons: Jade Addons 5.2.3
		java: OpenJDK 64-Bit Server VM 17
		joacarpet: JoaCarpet 2.1.0-SNAPSHOT
		jsmacros: Js Macros 1.9.0
			io_noties_prism4j: prism4j 2.0.0
			org_javassist_javassist: javassist 3.28.0-GA
			org_jooq_joor: joor 0.9.14
		kleeslabs: KleeSlabs 15.0.0
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		libipn: libIPN 4.0.1
		litematica: Litematica 0.15.3
		litematica-enderchest-materials: Litematica Enderchest Materials 0.0.4+1.20.1
		litematica-server-paster: Litematica Server Paster 1.2.0
		litematica_printer: Litematica Printer 2.4
		litemoretica: litemoretica 1.2.5+mc1.20.1
		loose-litematica: Loose-Litematica 0.1.0+build20230909
		magiclib: MagicLib 0.7.398+fe2125a-stable
			magiclib-1_20_1: MagicLib for 1.20.1 0.7.398+fe2125a-stable
		malilib: MaLiLib 0.16.3
		masa_gadget_mod: Masa Gadget 3.2.334+08c8f70-stable
			masa_gadget_mod-1_20_1: Masa Gadget for 1.20.1 3.2.334+08c8f70-stable
		masaadditions: MasaAdditions 1.2.0
		mcwifipnp: LAN World Plug-n-Play 1.6.9
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		minitweaks: MiniTweaks 1.4.0
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		mkb: ModernKeyBinding 1.2.1
		modmenu: Mod Menu 7.2.2
		mousetweaks: Mouse Tweaks 2.25
		moveboats: Move Boats 3.2
		moveminecarts: Move Minecarts 3.4
		nbt_ac: NBT Autocomplete 1.1.8
		nbtedit: In-game NBTEdit Reborn 5.0.3
		nbteditor: NBT Editor 1.13.0
		nbttooltips: NBT tooltips 0.1.4-1.20.x
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughanimations: NotEnoughAnimations 1.7.1
		openpartiesandclaims: Open Parties and Claims 0.20.4
		peca: Player Extend Carpet Addition 0.1.0
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.7.2
		pickblockpro: Pick Block Pro 1.7.21
		pistorder: Pistorder 1.6.3
		quickshulker: Quick Shulker 1.4.0-1.20
			shulkerutils: shulkerutils 1.0.4-1.19
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		replayfps: Replay FPS 0.2.0
		replaymod: Replay Mod 1.20.1-2.6.14
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 2.0.2
		roughlyenoughresources: Roughly Enough Resources 2.9.0
		rsmm_fabric: Redstone Multimeter Fabric 1.12.0
			amecsapi: Amecs API 1.5.0+mc1.20-pre1
		runelic: Runelic 18.0.2
		scarpet-graphics: Scarpet Graphics 0.1.5
			org_processing_core: core 3.3.7
		scroll-for-worldedit: Scroll for WorldEdit 1.1.4
		searchables: Searchables 1.0.2
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		skinlayers3d: 3d-Skin-Layers 1.6.2
		skinswapper: Skin Swapper 3.1.4
			org_apache_httpcomponents_httpclient: httpclient 4.5.10
			org_apache_httpcomponents_httpcore: httpcore 4.4.12
		sneak_through_berries: Sneak Through Berries 8.0.0+1.20.1
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sodiumss: Sodium Shader Support 0.1.0
		spark: spark 1.10.53
		sspb: Sodium Shadowy Path Blocks 3.2.1
		status-effect-bars: Status Effect Bars 1.0.3
		subtick: SubTick 2.0.0
		symbol-chat: Symbol Chat 1.20.1-1.1.2
		syncmatica: Syncmatica 1.20.1-0.3.11
		threadtweak: ThreadTweak 1.20.2-0.1.1
		tnttime: TNT Time 1.3.0
		todolist: Todo List 0.3.3
		totos-carpet-tweaks: Toto's Carpet Tweaks 0.3.2
		tweakermore: TweakerMore 3.16.0
		tweakeroo: Tweakeroo 0.17.1
		tweakmyclient: Tweak My Client 3.6.416+d193e20-beta
			tweakmyclient-1_20_1: Tweak My Client for 1.20.1 3.6.416+d193e20-beta
		urlmusicdiscs: URL Music Discs 1.1.0
			net_lingala_zip4j_zip4j: zip4j 2.11.5
		visuality: Visuality 0.7.1+1.20
		voicechat: Simple Voice Chat 1.20.1-2.5.6
		whyamionfire: Why Am I on Fire? 1.2.2
		wi_zoom: WI Zoom 1.5-MC1.20.1
		wildtoolaccess: Wild Tool Access 1.20-1.4.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		wthit: wthit 8.6.0
		xaeroarrowfix: Xaero's Minimap Arrow Fix 1.3+1.20
		xaerominimap: Xaero's Minimap 23.9.7
		xaeroplus: XaeroPlus 1.20.1
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.1
		xaeroworldmap: Xaero's World Map 1.37.8
		xaerozoomout: XaeroZoomout 1.1.0
		xpbeacons: Experience Beacons 7.5
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

### Additional context
None

**Comment by FractalGeodes** [comment]
#160 is a related issue, but the affected version and specific exception are different

**Comment by mrbuilder1961** [comment]
actually i think this and #160 are the same issue, but for whatever reason the crash report shows it slightly differently. anyway, just because #160 has info with the newer version, im going to close this as a duplicate. thanks for the info, i will make sure to take it into account when i get around to overhauling the copy menu and fixing this bug. appreciate it !!
