### ISSUE TITLE
Dupe counter does not work correctly (204.6.4)

### ISSUE THREAD

**Issue by DenysChuhlib** [mrbuilder1961/WheresMyChatHistory#157]
### Description
I installed the mod, messages in the chat are not duplicated when repeated, but the indicator of the number of repetitions is not added.
I have the latest version for 1.20.4 from [modrinth](https://modrinth.com/mod/chatpatches)

### How to reproduce
Immediately after installation

I have last fabric, last YetAnotherConfigLib, last ModeMenu

**Comment by mrbuilder1961** [comment]
Should be fixed now, available instantly here: https://github.com/mrbuilder1961/ChatPatches/actions/runs/8399545901/artifacts/1352040335
