### ISSUE TITLE
Nitpick: Literal newline in `fabric.mod.json` - 204.6.4 for 1.20.4

### ISSUE THREAD

**Issue by YoshiRulz** [mrbuilder1961/WheresMyChatHistory#159]
This doesn't seem to be a problem for the Fabric loader, but a strict parser like `jq`'s will choke on literal newlines in strings.
Since it's not literal in the source:
https://github.com/mrbuilder1961/ChatPatches/blob/dccbd01556bb03e5078d05fc6096eaf566b2156a/src/main/resources/fabric.mod.json#L7
...I'm guessing the process of expanding templates is what introduces it.

**Comment by mrbuilder1961** [comment]
Are you suggesting i escape it or just remove it?

**Comment by YoshiRulz** [comment]
It is already escaped and something is "unescaping" it.

**Comment by mrbuilder1961** [comment]
closed in upcoming release 210.6.6 for 1.21, will be for 1.20.4 in the future!

**Comment by YoshiRulz** [comment]
Ah I neglected to tell you about my discovery: The cause of this is a missing `escapeBackslash = true` in the build script, see https://github.com/FabricMC/fabric-example-mod/pull/282/files.
