### ISSUE TITLE
Hide Search Button but keep Search Field

### ISSUE THREAD

**Issue by nco2k** [mrbuilder1961/WheresMyChatHistory#164]
currently when you hide the search button, you also hide the search field. i would like to hide the search button but keep the search field.

**Comment by mrbuilder1961** [comment]
i think this would just be really awkward to have, if you want to change any of the search settings or hide it or bring it back you have to go into the config to un-hide it, just to do something else, it seems unnecessarily complicated. also i think the search box without an icon or button to its left to support it looks really ugly, so i'm going to have to pass on this :(

theoretically if a lot of people want this i can reconsider in the future but only time will tell.
