### ISSUE TITLE
Context Menu doesnt always close - 204.6.4

### ISSUE THREAD

**Issue by nco2k** [mrbuilder1961/WheresMyChatHistory#165]
### Description
when you right click on a message to open the context menu, the context menu usually goes away when you left click somewhere else. but when you left click on a playername, timestamp, link, chat field, search field etc. the context menu stays open.

### How to reproduce
right click on a message, then left click on a playername, timestamp, link, chat field, search field etc.

### Expected result
the context menu should close.

### Specs and Details
- fabric-api-0.97.0+1.20.4.jar
- chat_heads-0.10.32-fabric-1.20.3.jar
- chatpatches-204.6.4.jar
- YetAnotherConfigLib-3.4.1+1.20.4-fabric.jar
- modmenu-9.2.0-beta.2.jar (725.53 KiB) Primary

![Context](https://github.com/mrbuilder1961/ChatPatches/assets/26080123/3b4e7aa1-5ba6-469f-b677-e6732d771b42)

**Comment by mrbuilder1961** [comment]
please edit this and replace everything with the filled out bug report template, that's what it's for.

**Comment by mrbuilder1961** [comment]
fixed in the upcoming hotfix!
