### ISSUE TITLE
Catalogue Support

### ISSUE THREAD

**Issue by abidbmt** [mrbuilder1961/WheresMyChatHistory#169]
**Is your feature request related to a problem? Please describe.**
I want to only use the "Catalogue" mod as a mod menu but this mod is the only mod that depends on it

**Describe the solution you'd like**
Support Catalogue so that only one of both mods are required

**Comment by mrbuilder1961** [comment]
have you tried? i already added compatibility a few months ago and   it's even suggested in the logs.

**Comment by abidbmt** [comment]
> have you tried? i already added compatibility a few months ago and it's even suggested in the logs.

Yes, Fabric launcher immediately stops the game saying that i NEED to have Mod Menu installed

**Comment by abidbmt** [comment]
Im sorry I just realised I should have also maybe specified the minecraft version and chat patches version
MC Version: 1.20.1
Mod version: 201.5.5

**Comment by mrbuilder1961** [comment]
thanks, see #145.
