### ISSUE TITLE
I want to use multiple colors for time stamps.

### ISSUE THREAD

**Issue by KozukiYOMA** [mrbuilder1961/WheresMyChatHistory#170]
**Is your feature request related to a problem? Please describe.**
I want to use multiple colors for time stamps.

**Describe the solution you'd like**
The timestamps will be able to have different colors depending on the location.

**Describe alternatives you've considered**
Add the ability to change the color of timestamps in the chat by &.

**Comment by mrbuilder1961** [comment]
im like 60% sure you can already do this if you edit the timestamp format option and just add some &\<code\> s in there.. but there is a chance letter ones won't work. lmk what happens

**Comment by KozukiYOMA** [comment]
If you try to add & in the timestamp, the & and the letters after it will disappear.
It would be great if it would stop disappearing and change color.

Furthermore, it would be nice if you could just change the color, since the timestamp itself disappears when forced to change it by config.

**Comment by YOMA8338** [comment]
Furthermore, it would be nice if you could just change the color, since the timestamp itself disappears when forced to change it by config.

**Comment by mrbuilder1961** [comment]
looking back at this, not sure what you can't figure out. i just tried it and it worked here:
![image](https://github.com/mrbuilder1961/ChatPatches/assets/66807297/349871fe-66c5-4716-831a-6e413a5198e0)

the only thing that isnt supported is more than one custom hex color, and that will likely come in the future

**Comment by KozukiYOMA** [comment]
The color could be changed.
I would like to be able to change the color without using '' if possible.

**Comment by KozukiYOMA** [comment]
I don't know if it's because I'm changing the color, but I'm getting crashes. I will submit this as a separate issue, but I will post it here as well.
[crash-2024-06-25_19.09.30-client.txt](https://github.com/user-attachments/files/15969144/crash-2024-06-25_19.09.30-client.txt)
Sorry if this is unrelated.

**Comment by mrbuilder1961** [comment]
> The color could be changed.
> 
> I would like to be able to change the color without using '' if possible.

well it solves your problem and it already works so not sure what else id do. hope this helped!
