### ISSUE TITLE
Various things have disappeared.

### ISSUE THREAD

**Issue by KozukiYOMA** [mrbuilder1961/WheresMyChatHistory#171]
I thought I enabled timestamps, but they are not showing up,
Dupe counter is shown but fixed at 2.
https://github.com/mrbuilder1961/ChatPatches/assets/167823145/92cecc80-21b1-42ba-97a1-7e467d6efea7
Since the speed is doubled to reduce capacity, we recommend slowing down the video speed if it is too fast.

**Comment by mrbuilder1961** [comment]
i believe this issue has shown up with one or two other people recently.

could you give some more information and fill out the bug report template please?

also, is the server you're on public? if so i can try to test future fixes on it.

thanks for the report!

**Comment by KozukiYOMA** [comment]
Sorry for the delay, but this problem does not occur in 1.20.6.
The server I was playing on is a Japanese server called "24san.org".

**Comment by KozukiYOMA** [comment]
Suddenly the duplicate counter stopped working in 1.20.6.
It worked before...
In addition, ChatHeads suddenly stopped working. I don't know why...

I don't remember putting in any mods to replace the chat messages or the chat itself...

**Comment by mrbuilder1961** [comment]
> Suddenly the duplicate counter stopped working in 1.20.6. It worked before... In addition, ChatHeads suddenly stopped working. I don't know why...
> 
> I don't remember putting in any mods to replace the chat messages or the chat itself...

the fact chat heads is also not working leads me to believe this is an unrelated issue. you also seemed to re-open this issue at #179 and that has more info so i'm closing this as a duplicate
