### ISSUE TITLE
Shift chat doesn't move hover events - 206.6.5

### ISSUE THREAD

**Issue by sternschnaube** [mrbuilder1961/WheresMyChatHistory#172]
Disabled:
![image](https://github.com/mrbuilder1961/ChatPatches/assets/120551916/5c004f7f-9749-478d-99e4-091a56b5b088)

Activated:
![image](https://github.com/mrbuilder1961/ChatPatches/assets/120551916/c65ceaa2-4b30-41ff-b39f-18c73034b515)

**Comment by mrbuilder1961** [comment]
please fill out the bug report template with more info.

**Comment by sternschnaube** [comment]
### Description
Shift chat option doesn't move click events.

### How to reproduce
Just install the mod / alter chat height from vanilla. 
(The mod changes the height already by 10 pixel.)

### Expected result
Normal click function as before.

### Log file link
Not necessary, just install the mod alone.

### Specs and Details
Required information:
- Computer OS: W10
- Mod version: v206.6.5
- Fabric and API versions: v0.98.0
- YetAnotherConfigLib and Mod Menu versions (if installed): v4.4.2 and v10.0.0

**Comment by mrbuilder1961** [comment]
is this still present in 206.6.6?

**Comment by sternschnaube** [comment]
I can verify the next days.

**Comment by mrbuilder1961** [comment]
well? did you find out?

**Comment by sternschnaube** [comment]
Tested v211.6.7 on MC 1.21.
Everthing works as intended now, thanks 😄
