### ISSUE TITLE
Chat patches 204.6.5 recommends menulogue which is missing

### ISSUE THREAD

**Issue by 1MiloAC** [mrbuilder1961/WheresMyChatHistory#173]
### Description
My current fabric latest crash log is stating that chatpatches is missing a dependency called menulogue, but I can find absolutely no reference to this anywhere Minecraft Fabric 1.20.4
[latest.log](https://github.com/mrbuilder1961/ChatPatches/files/15315975/latest.log)

**Comment by mrbuilder1961** [comment]
i just tested this the other day and it seemed to be working fine, what other mods do you have installed? put the log on https://mclo.gs and i can take a look. it's just an informative message to show that those mods are compatible, it isn't a real error

**Comment by mrbuilder1961** [comment]
log error isn't related to chat patches, see above for warning explanation
