### ISSUE TITLE
Too wide space between username and message - 204.6.5

### ISSUE THREAD

**Issue by HypedditSkip** [mrbuilder1961/WheresMyChatHistory#174]
![kuva](https://github.com/mrbuilder1961/ChatPatches/assets/57301435/54fb7e50-8ae9-43be-9854-d13d6d47af65).

Tested with disabling the mod and issue went away. Config should be ok (for example default setting on "playername text"

- Windows 10
- 204.6.5
- Not sure where I can check since installed with Modrinth app (likely most recent stable 1.20.4 as of 22.5.2024) and API 0.97.0+1.20.4
- YetAnotherConfigLib 3.4.2+1.20.4-fabric and Mod Menu 9.2.0-beta.2
- ![kuva](https://github.com/mrbuilder1961/ChatPatches/assets/57301435/116367c6-7d6a-425f-9711-ad3f05682342)

Optional but suggested information:
- ![kuva](https://github.com/mrbuilder1961/ChatPatches/assets/57301435/f9663b47-bd9b-4b58-bc8d-82360fc167fc)

**Comment by mrbuilder1961** [comment]
since this is a compatibility issue, to find the problem mod you need to do a binary search. here's an attached tutorial from the fabric discord bot, let me know what the mod is and if it is even still happening. **make sure you keep chat patches and its required dependencies installed during testing.**

> A binary search can be used to quickly find a specific mod causing trouble, which can be especially useful when logs don't give a conclusive answer to your issue.
>
> Start by removing or disabling half of your mods, then test if the problem still occurs. If it does, remove half of the remaining mods and test again. If it doesn't, add back half of the mods you just removed.
>
> Keep in mind you don't have to stick strictly to halves each time, and may have to enable some library mods like Fabric API out of order.
>
> By repeating this on an increasingly smaller set of mods, you'll find the problematic mod within a few iterations.

**Comment by mrbuilder1961** [comment]
- if you're on a server with [StyledChat](https://github.com/Patbox/StyledChat/tree/1.21) (i don't think you specifically are) then it may also cause this issue, in my limited testing

still waiting on an update tho

**Comment by mrbuilder1961** [comment]
it's been a while with no response, if you find the conflicting mod please reopen this and comment it here. until then i can't reliably reproduce it
