### ISSUE TITLE
210.6.5 Cannot open settings

### ISSUE THREAD

**Issue by KozukiYOMA** [mrbuilder1961/WheresMyChatHistory#177]
### Description
Crashes when opening settings from mod menu in Catalogue
Error when trying to open from MODMenu

### How to reproduce
Open with Fabric 0.15.11-1.20.6
Open ChatPatches settings

### Expected result
Setup screen opens normally.

### Log file link
[latest.log](https://pastebin.com/8vDcuLF5)

### Specs and Details
Required information:
- Windows11pro 23h2 (10.0.22631.3737) 
- chatpatches-210.6.5
- Fabric and API versions: 0.15.11-1.20.6
- YetAnotherConfigLib: 3.4.2 Mod Menu: 10.0.0
- ![image](https://github.com/mrbuilder1961/ChatPatches/assets/167823145/44ffac86-daef-4356-9dff-97bf82b38ee7)
- ![image](https://github.com/mrbuilder1961/ChatPatches/assets/167823145/e2e249cf-f492-4c49-86c4-6b298f3f2986)
(Those with black lines are mods that have been disabled.)

Optional but suggested information:
- [chatpatches.json](https://github.com/user-attachments/files/15934493/chatpatches.json)

### Additional context
Updated ChatPatches and MRU.
About Error
![image](https://github.com/mrbuilder1961/ChatPatches/assets/167823145/cd765dd0-5de3-4ebd-9e93-bbc3bd1c6752)

**Comment by mrbuilder1961** [comment]
It looks like there is a conflict with a slight change I didn't notice, you can just use [`206.6.5`](https://modrinth.com/mod/chatpatches/version/206.6.5) as it's functionally identical. thanks for the report!

dev note: `class_2960.method_60655` is `Identifier.of(String,String)` in 1.21, but in 1.20.6 it's `method_43902` even tho they are the same method.

**Comment by mrbuilder1961** [comment]
temp solution: https://github.com/mrbuilder1961/ChatPatches/actions/runs/9635532818
how to use: https://github.com/mrbuilder1961/ChatPatches#How_to_access_beta_releases
