### ISSUE TITLE
Duplicate counter does not work, possibly due to conflict with Figura. 206.6.5~210.6.5

### ISSUE THREAD

**Issue by KozukiYOMA** [mrbuilder1961/WheresMyChatHistory#179]
### Description
Duplicate counter does not work.
When using 206.6.5, it stopped working at some point.
I added a lot of mods along the way, so it could be a conflict, but I couldn't find any related mods. I thought the developer might be able to figure it out, so I posted this.

### How to reproduce
Because it is expected to be filled with images,
I have put the introduction images separately for 1.20.6 and 1.21 at the bottom. You can reproduce it by installing the image with the extension "jar".

### Expected result
Duplicate counting works,
chat becomes compact.

### Log file link
[latest.log(1.21)](https://pastebin.com/BAbU25uL)
↑By the way, this is the log of the crash when I clicked on inventory 🤣
The latest.log for 1.20.6 was too long to prepare.

### Specs and Details
Required information:
- OS: Windows11 pro 23h2
- ChatPatches Version: 206.6.5 or 210.6.5
- 1.21.0: Fabric 0.15.11 FabricAPI 0.100.3
  1.20.6: Fabric 0.15.11 FabricAPI 0.99.4
- YetAnotherConfigLib: 1.20.6: 3.4.2
- ModList: JAR file in the bottom image

### Additional context
For Fabric 0.15.11-1.21.0
![image](https://github.com/mrbuilder1961/ChatPatches/assets/167823145/1da7a360-8c6a-4b91-a0fa-c6af051303ee)
![image](https://github.com/mrbuilder1961/ChatPatches/assets/167823145/1908a272-38e9-4397-9f9e-ab19c9d3a170)

**Comment by mrbuilder1961** [comment]
follow this tutorial explanation please: https://github.com/mrbuilder1961/ChatPatches/blob/1.21/README.md#how-to-find-mods-causing-compatibility-issues-binary-search

**Comment by KozukiYOMA** [comment]
Perhaps it is compatibility with Figura.
I discovered this by accident.
FiguraMC/Figura/issues/201

**Comment by mrbuilder1961** [comment]
interesting, thanks for the find. i had no idea there was this little network of issues relating to chat patches, but i'm happy to see at least one or two were not related to it. i will look into this when i have some free time!

**Comment by mrbuilder1961** [comment]
> Perhaps it is compatibility with Figura. I discovered this by accident. [FiguraMC/Figura/issues/201](https://github.com/FiguraMC/Figura/issues/201)

I was just looking at this and the author tagged their issue with 'fixed' (see [this commit](https://github.com/FiguraMC/Figura/commit/6671952ad587e06ad3d9becb111a1275030cc362)) so I'm going to go out on a limb and assume it was on Figura's end. 

i'm going to close this issue, but if something happens please update me and feel free to reopen this! thanks for being proactive in the other GitHubs, i really appreciate it 😁
