### ISSUE TITLE
Chat log: Non-ASCII characters turn into "?"

### ISSUE THREAD

**Issue by Qonsyuma** [mrbuilder1961/WheresMyChatHistory#18]
When typing in a script like Cyrillic, the text instead of being "хелоѵ", ends up being "?????" in the chat log.
An example JSON entry:
```json
{
	"translate": "chat.type.text",
	"with": [
		{
			"insertion": "SomeName23",
			"clickEvent": {<...>},
			"hoverEvent": {<...>},
			"text": "SomeName23"
		},
		{
			"text": "?????"
		}
	]
}
```
( less important stuff has been abbreviated with <...> )

**Comment by mrbuilder1961** [comment]
This seems like a language or serialization issue, so it might be a little more difficult to fix. I'll look into this.

**Comment by mrbuilder1961** [comment]
Working on a bug fix, so far in development it seems to have fixed itself so maybe it's just a 1.19 text serializing issue. I'll update if anything new comes up

**Comment by Qonsyuma** [comment]
Huh, that sounds like good news! x)

**Comment by mrbuilder1961** [comment]
Unfortunately it still seems to be broken, I have one more trick up my sleeve to try and fix this. So sorry for the inconvenience.

**Comment by mrbuilder1961** [comment]
I have a potential solution that I can try soon, but it would be released as a separate hotfix.
I think saving to file a hex representation of the character and then restoring it could work (ex, `§` as `/0167`).

**Comment by mrbuilder1961** [comment]
Reinvestigating this.

**Comment by mrbuilder1961** [comment]
Will be fixed tonight!! Very sorry for the huge wait, it was an issue with text encoding.

**Comment by mrbuilder1961** [comment]
You can use the update by getting the artifact from the Actions page.
