### ISSUE TITLE
Chat log throws `ConcurrentModificationException` randomly - 210.6.5.1 - 1.21

### ISSUE THREAD

**Issue by proxsyi** [mrbuilder1961/WheresMyChatHistory#181]
Sometimes when I hit pause whilst using this mod, It's only happened on servers, my game will just crash. It also crashes on the launch of a server sometimes. The logs point to this mod as the problem and when I remove it my game works just fine. I will leave the crash report and logs attached. 

[latest.log](https://mclo.gs/gmmYtPU)
[crash-2024-06-27_20.20.01-client.txt](https://mclo.gs/tM4ksbj)

I actually like this mod so please fix this or tell me how to.

I'm on 1.21 with all the mod requirements and the latest version of all my mods at the time of making this.

**Comment by lastedito** [comment]
Happens to me too

**Comment by mrbuilder1961** [comment]
thanks for the report, in the meantime you can disable the chatlog in the config to stop the crashes.

**Comment by mrbuilder1961** [comment]
i've just committed a rudimentary attempt at a fix, let me know if it helps: https://github.com/mrbuilder1961/ChatPatches/actions/runs/10519408218/artifacts/1845406439 (see [this](https://github.com/mrbuilder1961/ChatPatches?tab=readme-ov-file#how-to-access-beta-releases))!

**Comment by mrbuilder1961** [comment]
if that doesn't work, [follow these instructions](https://github.com/mrbuilder1961/ChatPatches?tab=readme-ov-file#how-to-find-mods-causing-compatibility-issues-binary-search) just in case it's some odd compatibility issue.

**Comment by mrbuilder1961** [comment]
feel free to reopen this if it isn't fixed in 214.6.10 and newer, but make sure to provide more context and logs!
