### ISSUE TITLE
Crashes for some reason - Mod: 210.6.6 - MC: 1.21.0

### ISSUE THREAD

**Issue by KozukiYOMA** [mrbuilder1961/WheresMyChatHistory#184]
### Description
I get a crash that I don't understand.
ChatCrashes?

### How to reproduce
I don't know at what point it happens.

### Expected result
No crashes

### Log file link
[latest.log](https://mclo.gs/pX2YQAF)
[crashlog](https://mclo.gs/3VPn7Xu)

### Specs and Details
Required information:
- Windows11 23h2
- ModVersion: 210.6.6
- Fabric0.15.11-1.21
- Fabric API0.100.6+1.21 
- YetAnotherConfigLib versions3.5.0+1.21
- Mod Menu-11.0.1
- Catalogue 1.10.1
- Menulogue 1.0.6

**Comment by mrbuilder1961** [comment]
okay so it seems the dev build still didnt fix it. does this server also have styledchat installed?

**Comment by KozukiYOMA** [comment]
It's probably in there.
And this problem was solved by disabling the ability to save chat logs.

**Comment by KozukiYOMA** [comment]
↑
I want to display this on the #180 side lol.

**Comment by mrbuilder1961** [comment]
you're right these are actually duplicate issues, thanks for pointing that out
