### ISSUE TITLE
"Search..." text draws over suggestion box - 210.6.5.1 - 1.21

### ISSUE THREAD

**Issue by TheRedstoneShark** [mrbuilder1961/WheresMyChatHistory#186]
### Description
The "Search..." text in the search bar is drawn over the command suggestion box, making it a little hard to read, and overall just doesn't look good or make sense. I think this applies to all versions of Minecraft/the mod.

![Demonstration](https://github.com/user-attachments/assets/28760039-3153-41b0-b7b8-9f440bc28b1e)

### How to reproduce
Open chat (with t or /) and start typing a command that will cause the suggestion box to show up.

### Expected result
I would expect the suggestion box to be drawn over the "Search..." text, making it darker like the rest of the search bar.

### Log file link
https://mclo.gs/qhqTEH8

### Specs and Details
- Microsoft Windows 10 Home, Version: 10.0.19045 Build 19045
- chatpatches-210.6.5.1
- Fabric 1.21, fabric-api-0.100.7+1.21, YetAnotherConfigLib-3.5.0+1.21

### chatpatches.json
- https://pastebin.com/2zqqAZud

**Comment by mrbuilder1961** [comment]
fixed in 211.6.7!
