### ISSUE TITLE
`shiftChat` mixins don't target `ChatHud#toChatLineY`, causing an issue with ChatShot - 210.6.5.1

### ISSUE THREAD

**Issue by L9Tigrotto** [mrbuilder1961/WheresMyChatHistory#187]
### Description
Using [ChatPatches](https://modrinth.com/mod/chatpatches) with [ChatShot](https://modrinth.com/mod/chatshot) all of the copy buttons on the right side of the chat got misaligned, so when trying to copy a line you are actually copying the line above.

This is a duplicate report, [see the original](https://github.com/DeDiamondPro/ChatShot/issues/5). The author understood what the problem is.

> this is because ChatPatches doesn't update the toChatLineY function so it would return the correct line for a corresponding y value, without this it is impossible to get the correct line for where your mouse is...

### How to reproduce
Install ChatPatches and ChatShot, every ChatShot button is misaligned if chat margin is > 0 (default 10).

### Specs and Details
Required information:
- Mod version : 210.6.5.1

**Comment by mrbuilder1961** [comment]
thanks for the report!! i'll get on this asap, i appreciate it

**Comment by mrbuilder1961** [comment]
this should fix the misalignment, please let me know if it works, and if it doesn't please update me with a description and log file! thanks (:

link: https://github.com/mrbuilder1961/ChatPatches/actions/runs/10034073360
how to use: https://github.com/mrbuilder1961/ChatPatches?tab=readme-ov-file#how-to-access-beta-releases

**Comment by KiberAndy** [comment]
> this should fix the misalignment, please let me know if it works, and if it doesn't please update me with a description and log file! thanks (:
> 
> link: https://github.com/mrbuilder1961/ChatPatches/actions/runs/10034073360 how to use: https://github.com/mrbuilder1961/ChatPatches?tab=readme-ov-file#how-to-access-beta-releases

I also use these 2 mods and had the same problem. 
Version 210.6.6 solves this, but the copy icon has become a little lower, although it’s possible to click, it’s strange that it’s lower, it’s just cognitive dissonance xD

**Comment by mrbuilder1961** [comment]
lower as in correctly shifted? or you're not used to it being shifted? just clarifying 😅

**Comment by KiberAndy** [comment]
> lower as in correctly shifted? or you're not used to it being shifted? just clarifying 😅

It looks unusual and seems wrong, because in the regular version everything is smooth, but with a problem, and in Beta it’s a little lower, but without a problem

**Comment by mrbuilder1961** [comment]
okay so i believe that's because ChatShot's developer still needs to adjust their mod to have compatibility when chat patches is installed. i'm going to close this as completed bc [ChatShot#5](https://github.com/DeDiamondPro/ChatShot/issues/5) was reopened and that's being tracked there.

**Comment by DeDiamondPro** [comment]
> okay so i believe that's because ChatShot's developer still needs to adjust their mod to have compatibility when chat patches is installed. i'm going to close this as completed bc [ChatShot#5](https://github.com/DeDiamondPro/ChatShot/issues/5) was reopened and that's being tracked there.

I have published my fix
