### ISSUE TITLE
`JsonParseException`: This value needs to be parsed as component - 1.20.4

### ISSUE THREAD

**Issue by howaxyz** [mrbuilder1961/WheresMyChatHistory#189]
The game crashed whilst unexpected error
Error: com.google.gson.JsonParseException: This value needs to be parsed as component
Code: -1073740791

[crashlog](https://mclo.gs/tInclOF)

Version minecraft: 1.20.4
Version mod: 204.6.5

**Comment by Fhxa3** [comment]
This also happens in later versions

[crash-2024-07-26_11.44.52-client.txt](https://github.com/user-attachments/files/16386282/crash-2024-07-26_11.44.52-client.txt)


Version minecraft: 1.21
Version mod: 210.6.5.1

I also tried your new build but the problem persists 
Version mod: 210.6.6

**Comment by mrbuilder1961** [comment]
> The game crashed whilst unexpected error Error: com.google.gson.JsonParseException: This value needs to be parsed as component Code: -1073740791
> 
> [crashlog](https://mclo.gs/tInclOF)
> 
> Version minecraft: 1.20.4 Version mod: 204.6.5

this seems like your chat log is corrupted. if you don't care about the contents you can just delete it, otherwise you could upload it to pastebin or something and i can take a look


> This also happens in later versions
> 
> [crash-2024-07-26_11.44.52-client.txt](https://github.com/user-attachments/files/16386282/crash-2024-07-26_11.44.52-client.txt)
> 
> Version minecraft: 1.21 Version mod: 210.6.5.1
> 
> I also tried your new build but the problem persists Version mod: 210.6.6

that's a different issue already being tracked at #180.

**Comment by DenysChuhlib** [comment]
Hi! I have this problem too

**Comment by DenysChuhlib** [comment]
I deleted the old `chatlog.json` file, but even without the file, this error occurs

**Comment by DenysChuhlib** [comment]
I left only the necessary dependencies and modmenu and the problem does not occur, I am trying to find the mod that causes this incompatibility

**Comment by DenysChuhlib** [comment]
It's very strange that I enabled the mods in small amounts and after fully enabling the problem went away, I also updated the `Plasmo Voice` mod to the new version but unfortunately I don't remember the old version

**Comment by DenysChuhlib** [comment]
I reverted to an older version plasmo voice, but the problem no longer occurs. This is very strange..

**Comment by DenysChuhlib** [comment]
I tried to restore everything as it was from backups, but I could no longer reproduce the error

**Comment by mrbuilder1961** [comment]
if you don't have the issue anymore that's okay, but if you still have a log from when you did experience it please send it on https://mclo.gs!

**Comment by DenysChuhlib** [comment]
Unfortunately, I no longer have the logs

**Comment by mrbuilder1961** [comment]
is anyone still experiencing this issue in later versions in chat patches 211.6.9?
