### ISSUE TITLE
Minor issue with Sounds mod - v204.6.5 - 1.20.4

### ISSUE THREAD

**Issue by Kistras** [mrbuilder1961/WheresMyChatHistory#192]
### Description
When using [ChatPatches](https://github.com/mrbuilder1961/ChatPatches) with [Sounds](https://github.com/IMB11/Sounds) a loud sound is played when a chat is opened. Volume of the sound seems to depend on amount of messages in chat.

ChatPatches appears to fully redraw/resend messages once chat window is opened. This only happens if the search field is empty (so if it contains anything this issue doesn't happen).

This issue can be resolved by interacting with either of both mods: 
- By setting a really low sound cooldown in Sounds mod, like 0.01 seconds. This still plays one sound, which doesn't happen normally;
- By inputting a wildcard (`[^$]+`) into search field of ChatPatches mod, which resolves the issue entirely.

### How to reproduce

1. Install ChatPatches and Sounds with dependencies;
2. Load into a game;
3. Open chat;
4. Get earraped.

### Expected result
No sound would be played.

### Log file link
https://mclo.gs/XcgkK5Z

### Specs and Details
- Windows 10 Pro 22H2 (hardware in logs)
- chatpatches 204.6.5
- sounds 1.1.3+1.20.4
- yet_another_config_lib_v3 3.4.2+1.20.4-fabri
- fabric-api 0.97.1+1.20.4
- fabric 0.16.0
- modmenu 9.2.0

### Additional context
This issue will be posted on github pages of both mods.
[Sounds issue page](https://github.com/IMB11/Sounds/issues/93)

**Comment by Kistras** [comment]
Video for reference. Warning - might be loud.

https://github.com/user-attachments/assets/3ff25b60-31be-4591-ac27-94019aace13b

**Comment by mrbuilder1961** [comment]
unfortunately i dont think theres anything i can really do on my part because the method that Sounds injects to trigger the mention is a critical one that i can't avoid, and it seems like the dev has already proposed/added a solution. i hope you can live without chat sounds 😅 sorry about this though :/
