### ISSUE TITLE
Please save case sensitive toggle between launches

### ISSUE THREAD

**Issue by AdielHub** [mrbuilder1961/WheresMyChatHistory#197]
I almost never need case sensitive mode, because i search for more generic info about earlier chats, but every time i boot up minecraft i need to disable it
![image](https://github.com/user-attachments/assets/7d6c303b-3d07-4684-9363-d5ec47e6b4d3)

I'd like the status of these three toggles to be saved in the config file, or add an option to save the toggles between sessions

Thank you !

**Comment by mrbuilder1961** [comment]
thanks, this is already being tracked at #149. just give it a thumbs up or something and i'll get to work on it when i can!
