### ISSUE TITLE
WMCH - 1.18.1 - Version 1.4.1 - Un-launchable Crash

### ISSUE THREAD

**Issue by LOLboy199** [mrbuilder1961/WheresMyChatHistory#2]
The newest version of WMCH does not work. 
Not sure how to help, since I don't code, I've attached my crash report. 
Also according to the mod 'not enough crashes' the crash was caused by 'NullPointerException' and 'RuntimeException'. Yet again, don't know a thing about code, so maybe that is pointless and doesn't help at all. 

[crash-2022-01-07_22.25.50-server.txt](https://github.com/mrbuilder1961/WheresMyChatHistory/files/7832550/crash-2022-01-07_22.25.50-server.txt)

![image](https://user-images.githubusercontent.com/89465021/148631626-2b5160ac-5b47-4d6e-bfb0-9a39af3e83a3.png)

![image](https://user-images.githubusercontent.com/89465021/148631643-1a98ce02-71b0-48fd-bb41-dc36686e33e4.png)

Love the mod and appreciate the cool updates. I know it must take a lot of effort for all this... so good luck

**Comment by mrbuilder1961** [comment]
okay i think i have a fix, but to double check could you send your config file?
on windows, it's located by default at `%appdata%\.minecraft\config\wmch.json` (copy/paste it into the Run program).

i think it probably has something to do with the config from v1.4, as i changed the field names so it might still be broken.

**Comment by LOLboy199** [comment]
Woops. Sorry I just saw this. Yeah I can send it if you still need it. I just downloaded the 1.4.2 file and it all seems to be working fine. 
You work fast, very impressive
