### ISSUE TITLE
Team color formatting dissapears when far away from player - 1.21 - 211.6.9

### ISSUE THREAD

**Issue by MarkHarrisMedia** [mrbuilder1961/WheresMyChatHistory#202]
I would love if I could somehow, not change the color of player names in the chat??? I really liked how it was when the player names were colored the same color as the team they are on. Is there a way to fix this? Thank you !! - Mark

**Comment by mrbuilder1961** [comment]
if the color is set to white then it shouldn't have any effect, can you send a screenshot and your log?

**Comment by Mat0u5** [comment]
I think the issue is that when the player is not loaded, their name color in chat shows up as white. 
In this image, the player Mat0u6 (my alt) sends a message while being right next to me, and their team color shows up just fine.
Then i teleport them a thousand blocks away, and when they send the next message, their color in chat is just plain white, even though they are still in the dark red team
![image](https://github.com/user-attachments/assets/cb3c99e2-2239-4e95-9ad7-3e78012895f3)

Mod Version: 211.6.9  *(1.21)*

**Comment by mrbuilder1961** [comment]
hmmm that's super odd, thanks for the ss. could you send your log file from that if there were any errors in it?

**Comment by Mat0u5** [comment]
No errors, only odd thing about it is that when the player is far away the message gets logged twice for some reason.
The first message at 18:06:43 was while being close to the player and their name showed up with the team color. Then i tp them away, and each of the subsequent messages get logged twice (i only receive one message in chat, not both)
```
[18:06:43] [Render thread/INFO]:
[CHAT] <{MINECRAFT_USERNAME}> I'm typing this while being close to the player
[18:06:59] [Render thread/INFO]:
[System] [CHAT] Teleported {MINECRAFT_USERNAME} to 1000.500000, 100.000000, 0.500000
[18:07:10] [Render thread/INFO]:
[CHAT] <{MINECRAFT_USERNAME}> And now i am veeery far
[18:07:10] [Render thread/INFO]:
[CHAT] <{MINECRAFT_USERNAME}> And now i am veeery far
[18:07:25] [Render thread/INFO]:
[CHAT] <{MINECRAFT_USERNAME}> and my name shows up as white :(
[18:07:25] [Render thread/INFO]:
[CHAT] <{MINECRAFT_USERNAME}> and my name shows up as white :(
```

**Comment by mrbuilder1961** [comment]
wow that's unexpected, i'll see if i can reproduce this. do you have a separate mod that's replacing the name with {MC_USER} or is that something else? thanks for all the info!

**Comment by Mat0u5** [comment]
I don't know what does that tbh, i was using a fresh 1.21 instance on modrinth and i only used chatpatches + dependencies.
Might just be modrinth itself formatting the logs somehow, but i'm not sure

**Comment by mrbuilder1961** [comment]
okay, thanks for all the info so far, i'll be sure to look into this asap. @MarkHarrisMedia is this the same issue you were experiencing or was it a user error that you figured out?

**Comment by mrbuilder1961** [comment]
also does the server you're on have the voice chat mod installed?

**Comment by mrbuilder1961** [comment]
documented further [here](https://discord.com/channels/1077285607375638529/1240418481296379966)!

test this build while waiting for the published release: https://github.com/mrbuilder1961/ChatPatches/actions/runs/12344157887/artifacts/2323779784
