### ISSUE TITLE
Add 'Chat Heads' Compatibility

### ISSUE THREAD

**Issue by voximir-p** [mrbuilder1961/WheresMyChatHistory#205]
**Is your feature request related to a problem? Please describe.**
When this mod is used with the [Chat Heads](https://modrinth.com/mod/chat-heads) mod, the Chat Heads mod will no longer be working.

**Describe the solution you'd like**
I want you to add compatibility for the [Chat Heads](https://modrinth.com/mod/chat-heads) mod.

**Describe alternatives you've considered**
Deleting this mod.

**Additional context**
No.

**Comment by mrbuilder1961** [comment]
you gotta be more specific, chat patches is compatible with chat heads. if you're talking about #163, there is no feasible solution there and the authors aren't interested in trying to fix it right now.
