### ISSUE TITLE
Save chatlogs to a separate file after x days

### ISSUE THREAD

**Issue by ghzeni** [mrbuilder1961/WheresMyChatHistory#207]
**Is your feature request related to a problem? Please describe.**
I'm using the chatlogs to process auction house data in a server i'm playing, but I don't have older data because it overwrites itself constantly.

**Describe the solution you'd like**
An option for chatlog to be saved to a separate file every few days

**Describe alternatives you've considered**
An option in the mod menu like `save chatlog before it expires` and maybe an option to parse the filename as we wish?

**Additional context**
I imagine something like this:

![image](https://github.com/user-attachments/assets/4b1d9af1-791c-4e64-9f1d-e7b167f0d7a3)

**Comment by mrbuilder1961** [comment]
if you can't just increase the max messages option, you can always backup your current log when it gets full in the chat log section of the config. isn't that much easier?

**Comment by ghzeni** [comment]
> if you can't just increase the max messages option, you can always backup your current log when it gets full in the chat log section of the config. isn't that much easier?

I ended up creating a whole separate mod for this, turns out your rights but also I didn't need to save everything 😁

**Comment by mrbuilder1961** [comment]
woah good for you!

**Comment by mrbuilder1961** [comment]
okay ima close this then

**Comment by ghzeni** [comment]
thank you, mr builder!! Happy new year! :smile:
