### ISSUE TITLE
Crash on startup!

### ISSUE THREAD

**Issue by Tempest-5ky** [mrbuilder1961/WheresMyChatHistory#21]
Pretty self-explanatory! Game crashes on startup, removing this mod fixes it.
Minecraft version is 1.18.2, mod version 1.5.0

Crashlog: https://mclo.gs/NGa2vJk
Seems to be a mixin error, specifically wmch.mixins.json:ChatHudMixin

**Comment by mrbuilder1961** [comment]
Can you check if it's solely this mod or this mod in combination with others? Your mod list is pretty long so there's a chance another mod is causing a conflict.

**Comment by Tempest-5ky** [comment]
Checked, good idea!
Seems to have been an incompat with MoreChatHistory (https://www.curseforge.com/minecraft/mc-mods/more-chat-history) which I had kept because it shows more messages than this mod.

**Comment by mrbuilder1961** [comment]
Great, it sounds like everything is working now. I'll make a note to increase the maximum (custom) messages limit, 4096 does seem a bit low. Do you think 16384 is a good limit or should i go higher? My only concern is too much memory consumption but idk if that's would even be an issue. Maybe the short `MAX_VALUE` (32,767) is better. Whatever the community thinks, let me know!
