### ISSUE TITLE
Add separate colour options for decorative text

### ISSUE THREAD

**Issue by HuiYangaliu** [mrbuilder1961/WheresMyChatHistory#210]
Timestamp text and timestamp decoration text use the same color, I want to split them into timestamp text color and timestamp decoration text color; similarly I want player names to be sorted into playername color and playername decoration color

now：
![image_45](https://github.com/user-attachments/assets/dc8515af-7efe-4b0e-9713-785a0455cb8f)
i want：
![image_47](https://github.com/user-attachments/assets/085ad39e-b5df-46ec-b06d-049fe283a7cf)

**Comment by mrbuilder1961** [comment]
what would you have to input to get the same result as the picture?

**Comment by HuiYangaliu** [comment]
The pictures were made in photoshop, just describing what effect I wanted

**Comment by mrbuilder1961** [comment]
im asking because you could achieve the second option already by using `&7| <&2$&7>` for the player name text option, assuming you aren't on a scoreboard team that forces your player name to be white.

**Comment by HuiYangaliu** [comment]
Thanks for letting me know
