### ISSUE TITLE
Does this work on 1.19.1+?

### ISSUE THREAD

**Issue by srnyx** [mrbuilder1961/WheresMyChatHistory#25]
Hi, on Modrinth it says `1.19 only`, is that referring to 1.19.0? Or does it mean 1.19.x (1.19.0+)?
I don't think it's the latter since the dependency for Minecraft is set to `1.19`, but I just wanted to make sure.

**Comment by mrbuilder1961** [comment]
Currently it only supports 1.19.0, but 1.19.1 is coming out soon.
