### ISSUE TITLE
Triangle brackets missing from playernames despite being enabled?

### ISSUE THREAD

**Issue by Skeithh** [mrbuilder1961/WheresMyChatHistory#28]
Using wmch 1.5.0 for 1.18.2
Recently updated and i found that I was missing the triangle brackets despite them being on in the config? it makes it very difficult to read the text. Earlier versions dont have this problem.

**Comment by mrbuilder1961** [comment]
kindly provide a screenshot, mod list, and what you have the name string set as.

**Comment by Skeithh** [comment]
Sorry for the wait, here's the additional info
[modlist.txt](https://github.com/mrbuilder1961/WheresMyChatHistory/files/9438728/modlist.txt)
.
![image](https://user-images.githubusercontent.com/74820899/187049218-3af66616-d5b2-4e16-8e08-f7e2e7c10c50.png)
![image](https://user-images.githubusercontent.com/74820899/187049230-83655937-dd18-4e1c-b8b2-8127f31280ce.png)

**Comment by mrbuilder1961** [comment]
Does it still look like that even if you customize it (for example, set the string to `[$]`) ?

**Comment by Skeithh** [comment]
Yeah, that was the first one I tried actually but it didn't do anything

**Comment by mrbuilder1961** [comment]
Okay thanks!

**Comment by mrbuilder1961** [comment]
Could you send your `wmch.json` config file or the text inside it as well please?

**Comment by Skeithh** [comment]
Here's the contents as I can't upload a .json file

{
  "time": false,
  "timeStr": "[HH:mm:ss]",
  "timeFormat": "",
  "timeColor": 16733695,
  "hover": true,
  "hoverStr": "yyyy dd, MM, @ HH:mm:ss.SSSS",
  "counter": false,
  "counterStr": "\u00268(\u00267x\u0026e$\u00268)",
  "counterColor": 16777045,
  "saveChat": false,
  "boundary": true,
  "boundaryStr": "\u003c]\u003d\u003d\u003d---{ SESSION BOUNDARY LINE }---\u003d\u003d\u003d[\u003e",
  "boundaryColor": 43690,
  "nameStr": "<$>",
  "maxMsgs": 1024
}

**Comment by mrbuilder1961** [comment]
Try deleting the config file and letting the mod regenerate it, tell me if that does anything

**Comment by Skeithh** [comment]
deleted and regenerated, still nothing

**Comment by Skeithh** [comment]
was running into more issues so i was hopping between versions, and it seems like version 1.4.5 also has this issue for me.
Version 1.4.4 doesn't, but that one does have that annoying bug where it puts `<SYSTEM>` in the place of other player's names and then moves their user outside of it, so that's not a viable downgrade d:

In addition, it seems to not play nice with drogtor the nickinator, as in it does not display the nicknames and color changes to the client? It worked once on a fresh install, but upon restarting the game to allow myself to have a config to edit again to remove the timestamps it once again broke.

**Comment by mrbuilder1961** [comment]
i can't seem to reproduce it on my end, could you attach the mod file that you've been using while experiencing this bug?

**Comment by Skeithh** [comment]
It's really strange, and I'm really confused as I'm the one running into issues. none of the other players on my server have reported similar problems despite having the exact same modset. 
[wcmh stuff.zip](https://github.com/mrbuilder1961/WheresMyChatHistory/files/9534642/wcmh.stuff.zip)

**Comment by mrbuilder1961** [comment]
okay thanks, i'll check this out later today and see if i can reproduce it. now it sounds more like a conflict, maybe with the nickname mod you mentioned previously.

**Comment by mrbuilder1961** [comment]
I'm going to close this until any further developments come up, until then I hope it starts working properly!
