### ISSUE TITLE
Bug, Timestamp duplication

### ISSUE THREAD

**Issue by Otifus** [mrbuilder1961/WheresMyChatHistory#29]
![2022-10-29_11 37 21](https://user-images.githubusercontent.com/104933617/198822476-da8513a7-754a-41b8-8918-a757c6e40ba4.png)
Timemstamps are duplicated, if you turn off the function, then both are deleted at once.
And yes, I uninstalled wmch.json before installing this version 1.19.2-1.5.3

Fabric 1.19.2
Fabric API ver 0.59.0
ClothConfig ver 8.2.88
ModMenu ver 4.0.6

**Comment by mrbuilder1961** [comment]
Could you provide a video of the bug in-action? I can't seem to reproduce it. Also, please provide a mod list/log.

**Comment by Otifus** [comment]
https://user-images.githubusercontent.com/104933617/198874870-fd20048d-6213-4ef9-8695-0604baff453d.mp4


I already found the cause of the duplication, the reason for this was the Meteor Client, and the Chat Player Head function, which displays the player skin's head icon before the message, there was no conflict in previous versions of the your mod, so I did not pay attention to this before creating this ticket, so this is not a bug, but a conflict of functions, I apologize for the inconvenience, I think the issue can be closed :persevere:

**Comment by mrbuilder1961** [comment]
Good job on figuring it out, so I should probably list Meteor Client as "conflicting" on the mod hosting sites. Is it only with Chat Heads in Meteor, or are there other functions that also cause issues?

**Comment by Otifus** [comment]
in fact all the options inside the BetterChat function conflict and can cause either displacement or duplication, some of them do the same things as the mod, only worse or in a more limited version, so there is no point in them, you can safely mark the whole BetterChat as conflicting, I didn’t find any problems with all other functions in Meteor and your mod works as it should , there is the only other option that I haven’t checked, there are separate Fabric mods for displaying head icons in the chat, like Player Heads, and I don’t know if there is a conflict with it, I think I can check it tomorrow and write about it

**Comment by mrbuilder1961** [comment]
Okay I fixed the issue and marked it incompatible. Thanks so much
