### ISSUE TITLE
[WMCH-1.18.x-1.4.2] Disableing Timestamps still adds a space to the left of messages

### ISSUE THREAD

**Issue by jpeterik12** [mrbuilder1961/WheresMyChatHistory#3]
As you can see, I have disabled the timestamps, but the messages are still pushed over. The second line is a newline from a tellraw, which is correctly positioned.
![image](https://user-images.githubusercontent.com/31190190/148694797-af663270-9bc9-4cdd-9bb0-3cde72b03f71.png)

**Comment by mrbuilder1961** [comment]
okay, i believe know exactly how to fix this. bugfix should be out within a couple of hours

**Comment by mrbuilder1961** [comment]
Fixed in [release 1.4.3](https://github.com/mrbuilder1961/WheresMyChatHistory/releases/tag/1.4.3)!
