### ISSUE TITLE
Game crashes on start - 1.19.2, 1.5.3 - BUG

### ISSUE THREAD

**Issue by srnyx** [mrbuilder1961/WheresMyChatHistory#30]
### Description
The game crashes when I try to launch it with Where's My Chat History? installed.

### Expected result
The game should launch without it crashing.

### Log file link
https://paste.srnyx.xyz/keyanoxeje.yaml

### Specs and Details
- **Computer OS:** Windows 10
- **Minecraft version:** 1.19.2
- **Fabric and API versions:** 0.14.10 (F), 0.64.0 (API)
- **Cloth Config and Mod Menu versions:** 8.28.8 (CC), 4.0.6 (MM)
- **List of all installed mods:** Provided in [Log file link](https://paste.srnyx.xyz/keyanoxeje.yaml)
- **`wmch.json` file:** https://paste.srnyx.xyz/unenavotes.json

**Comment by mrbuilder1961** [comment]
Try running without Essential; they're incompatible.

**Comment by srnyx** [comment]
> Try running without Essential; they're incompatible.

That fixes it, do you plan on adding support for Essential?
Also, you should add `essential-container` to the incompatible mods list.

**Comment by mrbuilder1961** [comment]
Thanks for the suggestion, i'll make sure to do that.
It might be possible, but Essential completely overwrites the ChatHud and is very invasive with its mixins so I doubt it would work.
