### ISSUE TITLE
Jist of bug - mc version and/or mod version - BUG

### ISSUE THREAD

**Issue by 2-Spaced** [mrbuilder1961/WheresMyChatHistory#31]
### Description
Crashes with Essential on 1.19.2

### How to reproduce
When I launch Minecraft With this mod whilst using essential (and the needed dependencies with quilted standard libraries instead of fabric api) it crashes

### Log file link
https://mclo.gs/bDDKK8W

### Specs and Details
Required information: 
- Windows 10 pro 21H1
- 1.19.2
- [WMCH [1.19.1-1.19.2]](https://modrinth.com/mod/wmch/version/1.19.2-1.5.3)
- Newest quilt version and qfapi-4.0.0-beta.17_qsl-3.0.0-beta.19_fapi-0.64.0_mc-1.19.2
- Cloth Config 8.2.88 and Mod Menu 4.0.6 
- list of all installed mods:
![image](https://user-images.githubusercontent.com/108649837/198989536-565a8b42-1121-446a-8b7a-2dde4dc71297.png)

**Comment by mrbuilder1961** [comment]
https://github.com/mrbuilder1961/WheresMyChatHistory#incompatibilities
