### ISSUE TITLE
Crash - 1.19.2-1.5.3

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#32]
### Description
Mod crashes on startup

### How to reproduce
1.Installed the mod
2.crash on startup

### Expected result
Mod to run

### Log file link
https://mclo.gs/hAv62pj

### Specs and Details
Required information: 
- Mac OS
- 1.19.2
- Fabric (0.14.10) and Fabric API 0.66.0
- Cloth Config (8.2.88) and Mod Menu (4.1.0)
- list of all installed mods 
- 1.19.x-wmch-1.19.2-1.5.3.jar
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
accurate-maps-1.0-BETA+1.19.jar
advancedtooltips-1.6.0+1.19.jar
advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
alternate-current-mc1.19-1.4.0.jar
AmbientEnvironment-fabric-1.19.2-8.0+3.jar
AmbientSounds_FABRIC_v5.2.8_mc1.19.2.jar
amecs-1.3.8+mc.1.19-rc2.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.3.49-fabric.jar
ArrowCam-1.0.1(1).jar
audio_engine_tweaks-1.2.3-1.19 build 3.jar
auditory-0.0.4-1.19.x.jar
autohud-2.3.2+1.19.1.jar
bedrockwaters-1.7.3+1.19.2.jar
bendy-lib-fabric-2.1.1.jar
better-dark-mode-2.1.0.jar
BetterAnimationsCollection-v4.0.4-1.19.2-Fabric.jar
betterbeds-1.2.0.jar
betterbiomeblend-1.19.0-1.3.6-fabric.jar
bettercommandblockui-0.2.0-1.19.2.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
bettermounthud-1.2.0.jar
BetterPingDisplay-Fabric-1.19.2-1.1.1.jar
betterstats-1.4.3.jar
BetterThirdPerson-Fabric-1.19-1.8.1.jar
BiomeParticleWeather-v4.0.2-1.19-Fabric.jar
Blanket Client tweaks-1.1.2.jar
block-entity-extended-rendering-2.0.0.jar
blur-2.6.0.jar
Bookshelf-Fabric-1.19.2-16.1.11.jar
brokenleadwarner-1.0.0+1.19.2.jar
CameraOverhaul-1.3.1-fabric-universal.jar
Capes-1.4.5+1.19.jar
cardinal-components-api-5.0.2.jar
catalogue-fabric-1.6.3-1.19.2.jar
cave_dust-1.2.0.jar
cem-0.7.1.jar
chat_heads-0.7.1-fabric-1.19.1.jar
chat-coords-0.2.2233.jar
chatcalc-3.0.12.jar
chime-1.3.0.jar
CITResewn-1.1.2+1.19.2.jar
ClearDespawn-fabric-1.19.2-1.1.10.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.15.jar
colormatic-3.1.2+mc.1.19.jar
colour-my-servers-1.0.2.jar
compact-scoreboard-1.0.0.jar
compacthelpcommand-fabric_1.19.2-1.7.jar
completeconfig-2.0.0.jar
condensed_creative-2.0.0+1.19-fabric.jar
configured-fabric-2.0.0-1.19.2.jar
continual-music-1.0.jar
continuity-2.0.1+1.19.jar
Controlling-fabric-1.19.2-10.0+7.jar
coord_book-1.2.1+1.19.jar
cr-compass-ribbon-fabric-2.8.2+1.19.1.jar
CraftPresence-1.19.2-Release-1.9.5-universal.jar
CreativeCore_FABRIC_v2.8.9_mc1.19.2.jar
ctm-fabric-1.0.0+1.19.jar
ctrlq-fabric-mc1.18+-1.8.jar
cyanide-fabric-1.19-3.0.0.jar
dark-graph-1.0.2.jar
DeathFinder-v4.1.2-1.19.2-Fabric.jar
Debugify-2.8.0.jar
DetailArmorBar-2.6.2+1.19-fabric.jar
disguiseheads-fabric-1.0.1-mc1.19.2.jar
DistinguishedPotions-v4.0.1-1.19.2-Fabric.jar
do-a-barrel-roll-2.2.1+1.19.2-fabric.jar
DripSounds-1.19-0.3.0.jar
dyed-fabric-1.19.2-1.1.0.jar
dynamic-fps-2.2.0.jar
dynamiccrosshair-3.11+1.19.2.jar
dynamiccrosshair-compat-1.11+1.19.2.jar
ears-fabric-1.19-1.4.6.jar
eating-animation-1.9.jar
effective-1.4.jar
elytra-recast-2.2.1.jar
ElytraPhysics-1.1.1.jar
emoji-type-2.0.1+1.19.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.8.jar
enhanced-searchability-mc1.19-3.0.1+build.9.jar
enhancedblockentities-0.7.2+1.19.2.jar
entity_texture_features_fabric_1.19.x-4.1.1.jar
entity-view-distance-1.0.2+1.19.jar
entityculling-fabric-1.5.2-mc1.19.jar
Essential-fabric_1-19.jar
exordium-fabric-1.0.2-mc1.19.2.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
fabric-api-0.66.0+1.19.2.jar
fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar
fabricskyboxes-0.6.0+mc1.19.2.jar
fabrishot-1.9.1.jar
fallingleaves-1.12.4+1.19.2.jar
Female-Gender-Mod-fabric-1.19.2-3.0.1.jar
ferritecore-5.0.0-fabric.jar
firstperson-fabric-2.2.0-mc1.19.2.jar
ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric.jar
FPS-Monitor-1.19-1.3.0-Fabric.jar
GoogleChat-0.4.2.jar
grabcraft-litematic-1.19.1-fabric0.58.5-0.5.jar
graphutil-fabric-1.0.0-mc1.19.jar
hatlist-1.3.jar
highlight-1.0.0-fabric.jar
Highlighter-1.19.1-fabric-1.1.4.jar
hitboxplus-1.19.2-0.2.0.jar
HorseDebug-1.2.4.jar
Iceberg-1.19.1-fabric-1.0.46.jar
illuminations-1.10.11.jar
indium-1.0.9+mc1.19.2.jar
inventory-control-tweaks-1.3.18+MC1.19-1.19.2.jar
inventoryfullalert-1.1.0-1.19.jar
iris-mc1.19.2-1.4.0.jar
item-model-fix-1.0.3+1.19.jar
ItemPhysicLite_FABRIC_v1.5.2_mc1.19.1.jar
Jade-1.19.1-fabric-8.2.3.jar
jsonem-0.1.2+1.19.jar
krypton-0.2.1.jar
lambdabettergrass-1.3.0+1.19.jar
lambdynamiclights-2.1.2+1.19.jar
lazy-language-loader-0.3.1.jar
lazydfu-0.1.3.jar
LetSleepingDogsLie-1.19.2-1.1.1.jar
libjf-3.2.0.jar
lighty-1.0.5+1.19.1.jar
litematica-fabric-1.19.2-0.12.5.jar
lithium-fabric-mc1.19.2-0.10.1.jar
lunade-fastanim-1.5.6-1.19.jar
make_bubbles_pop-0.0.2-1.19.jar
malilib-fabric-1.19.2-0.13.0.jar
mazeworld-1.19.2-1.1.0.jar
mbp-1.4.jar
mcmouser-1.19-fabric-1.0.0.jar
memoryleakfix-1.19.1-0.7.0.jar
menulogue-fabric-1.0.1-1.19.2.jar
MerchantMarkers-1.19.1-fabric-1.2.3.jar
microdurability-0.3.6+1.19.jar
midnightcontrols-1.7.1+1.19.jar
midnightlib-fabric-1.0.0.jar
minihud-fabric-1.19.2-0.23.3.jar
modelfix-1.8-fabric (1).jar
modmenu-4.1.0.jar
moreculling-1.19.1-0.10.0.jar
moremcmeta-1.19-3.0.5-fabric.jar
MouseTweaks-fabric-mc1.19-2.22.jar
movement-vision-1.3.0.jar
multiple-server-lists-mc1.19.1-3.0.2+build.10.jar
nether-coords-1.19.x-1.1.2.jar
niceload-0.1.3.jar
NoChatReports-FABRIC-1.19.2-v1.13.11.jar
notenoughanimations-fabric-1.6.2-mc1.19.2.jar
optigui-1.1.6.jar
organized-tabs-1.0.1.jar
ostOverhaul-0.2.6-1.19.jar
PetOwner-1.8.3-1.19+.jar
PickUpNotifier-v4.2.0-1.19.2-Fabric.jar
player-animation-lib-fabric-0.4.0-test1.jar
pling-1.5.0.jar
polymer-all-0.2.18+1.19.2.jar
PresenceFootsteps-1.6.3.jar
puzzle-1.4.0-1.19.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
raised-fabric-1.19.2-1.1.3.jar
reacharound+1.19-1.1.0.jar
recursive-resources-2.2.1+1.19.jar
reeses_sodium_options-1.4.7+mc1.19.2-build.59.jar
remember-my-txt-1.0.0+MC1.19.jar
rer-2.6.0.jar
resourcepackchecker-1.19.2-1.0.0.jar
respackopts-4.0.2.jar
roughly-searchable-2.5.0+1.19.jar
RoughlyEnoughItems-9.1.568.jar
RoughlyEnoughProfessions-fabric-1.19-1.1.2.jar
RoughlyEnoughTrades-1.19-1.0.jar
satin-1.9.0.jar
sheepconsistency-1.0.4.jar
show-me-your-skin-1.3.4+1.19.jar
Smooth Swapping 0.5 (1.19.2)-0.5.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.11+mc1.19.2-build.68.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.0.16.jar
starlight-1.1.1+fabric.ae22326.jar
statssearch-1.19.1-fabric0.58.5-1.0.1.jar
status-effect-bars-1.0.1+1.19.jar
talkbubbles-1.0.2.jar
TerraBlender-fabric-1.19.2-2.0.1.129.jar
testworld-1.0.0.jar
third-person-maps-1.4.0+1.19.jar
thorium-1.3.2.jar
tooltipsplus-1.3.0+1.19.jar
tooltiptweaks-1.1.0.jar
toomanybinds-0.3.2+1.19.jar
transparent-5.1.2+1.19-fabric.jar
visualoverhaul-4.1.1.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.11-all.jar
waveycapes-fabric-1.2.2-mc1.19.2.jar
waxednotwaxed-1.1.3.jar
weaponmaster-multi-fabric-1.19-3.0.2.jar
whats-that-slot-fabric-1.3.1+1.19.2.jar
wmitaf-fabric-mc1.19-3.1.1.jar
worldtime-1.19.1-fabric0.58.5-1.3.1.jar
YetAnotherConfigLib-1.6.0.jar
Optional: 
- `wmch.json` file (NOT PASTED)
- `chatlog.json` file (NOT PASTED)

### Additional context
Worked on quilt. Took out the ones I didn't port over but still doesn't work

**Comment by mrbuilder1961** [comment]
It's because of Essential, but I have a hotfix releasing soon to add compatibility. I'm going to leave this open until then for anyone else with the same issue to see.
