### ISSUE TITLE
Cant set colors to #ffffff in config? - 1.19.2 - BUG

### ISSUE THREAD

**Issue by slushieuwu** [mrbuilder1961/WheresMyChatHistory#33]
### Description
Im able to change the colors in the config to anything, and it works just fine. But if i try to set it to solid white (#ffffff) and save the config, then it just resets to the color it was last set to

### How to reproduce
1. Open the config in Modmenu
2. Try to set a color value to solid white (#ffffff)
3. Save and quit the config menu
4. Type in chat, and see that the color you changed looks exactly the same as before you changed it
5. Open config again, color was set back to what it was instead of white

### Expected result
Expected for #ffffff to save in the config

### Log file link
https://mclo.gs/DySzvbA

### Specs and Details
Required information: 
- Computer OS: Windows 10
- Minecraft version: 1.19.2
- Fabric and API versions: Quilt 0.17.6 and QFAPI 4.0.0-beta.19
- Cloth Config and Mod Menu versions (if installed): Cloth Config API 8.2.88 and Modmenu 4.1.0
- list of all installed mods (can be a list *copied* from a log file **OR** a screenshot): lotta mods :ioa:
![image](https://user-images.githubusercontent.com/86991346/201789908-4cce1185-de2e-4482-a3f1-c06081037ba3.png)

Optional: 
- `wmch.json` file (NOT PASTED)
- `chatlog.json` file (NOT PASTED)

### Additional context
Anything else that could possibly be relevant to this issue. A recommended use for this box is what happened leading up to the incident.

**Comment by mrbuilder1961** [comment]
I have a mod update coming out tonight that should fix this issue, thanks for the bug report.
