### ISSUE TITLE
Ability to add the world/server name to the session boundary? - SUGGESTION

### ISSUE THREAD

**Issue by slushieuwu** [mrbuilder1961/WheresMyChatHistory#34]
**Is your feature request related to a problem? Please describe.**
Nope, just think it would be nice

**Describe the solution you'd like**
The ability to add the world/server name to the session boundary by adding a character (probably $) in place of where you want the name to appear, so when you join a world/server it says the name of the one you joined

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~
Cant think of anything else

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by mrbuilder1961** [comment]
That's a great idea! I'll make sure to look into this when I add more suggestions.

**Comment by srnyx** [comment]
@mrbuilder1961 this needs to be added to the `Boundary text`'s tooltip
Currently just says this:
![img](https://us-east-1.tixte.net/uploads/srnyx.is-from.space/java_P5n3z7Um4N.png)
