### ISSUE TITLE
Allow support of `\n` - SUGGESTION

### ISSUE THREAD

**Issue by srnyx** [mrbuilder1961/WheresMyChatHistory#36]
Allow `\n` for new lines in text options (such as `Boundary text`). Would be super useful to more easily separate sessions.

**Comment by mrbuilder1961** [comment]
Are you sure this doesn't already work? I say this because I haven't explicitly tried to prevent this from happening.

**Comment by srnyx** [comment]
> Are you sure this doesn't already work? I say this because I haven't explicitly tried to prevent this from happening.

Yeah, I tried using `\n` in the session separator text input, but it just showed `\n` instead of parsing to a new line.
