### ISSUE TITLE
No session boundary when using chat log - 1.19.2/1.5.5 - BUG

### ISSUE THREAD

**Issue by arschfidel0815** [mrbuilder1961/WheresMyChatHistory#39]
### Description
When using the chat log option, the old chat history gets pasted in correctly, but there is no session boundary inserted between the old and the new messages.
I'm not 100% sure if this is a bug or just the intended functionality, but I personally would expect the session boundary to also appear when the game has been closed between sessions.

### How to reproduce
1. Enable the chat log option
2. Make sure the session boundary option is also enabled
3. Type some chat message
4. Save the world
5. Close the game
6. Reopen the game
7. Load the same world
8. Look into the chat

### Expected result
I expect the session boundary to be inserted between old chat history and new messages when using the chat log option and closing the game between the sessions.

### Log file link
https://mclo.gs/6rZ4o5M

### Specs and Details
Required information: 
- OS: Linux (Manjaro)
- Minecraft version: 1.19.2
- Fabric: 0.14.10; Fabric API: 0.67.1
- Cloth Config: 8.2.88; Mod Menu: 4.1.1
- Mods:   [✔] 1.19.x-wmch-1.19.2-1.5.5   [✔] cloth-config-8.2.88-fabric   [✔] fabric-api-0.67.1+1.19.2   [✔] modmenu-4.1.1

### Additional context
(I've just tested the mod in singleplayer, not multiplayer - maybe that's the problem?)

**Comment by mrbuilder1961** [comment]
this is an intended feature, but you're right that's a good idea.
