### ISSUE TITLE
If certain setting of no chat reports is used, all text formatting disappears in player messages  - 1.19.2/1.5.5 - BUG

### ISSUE THREAD

**Issue by JustLetterV** [mrbuilder1961/WheresMyChatHistory#40]
### Description
If certain setting of no chat reports is used, all text formatting disappears in player messages.

Left side of this screenshot "Convert to game message" setting in no chat reports settings is set to "no" and right side "yes".
![kuva](https://user-images.githubusercontent.com/75657829/203878077-38de03a0-9644-4eb9-8427-9967a033fed0.png)

### How to reproduce
1. Open game with mods listed below.
2. Go to no chat reports config and set "Convert to game message" to "Yes" (all other settings are default in wmch and no chat reports).
3. Use tellraw command in command block:
tellraw \@a {"extra":[{"color":"blue","text":"blue_text"},{"text":" "},{"bold":true,"text":"bold_text"},{"text":" "},{"hoverEvent":{"action":"show_text","contents":{"text":"cool hover text"}},"text":"this_should_have_hover_text"}],"text":" no_color "}
4. As you can see, all colors and text formatting is correctly showing up.
5. Next add "\<username\>" to start of that tellraw message or just use this command in command block: 
tellraw \@a {"extra":[{"color":"blue","text":"blue_text"},{"text":" "},{"bold":true,"text":"bold_text"},{"text":" "},{"hoverEvent":{"action":"show_text","contents":{"text":"cool hover text"}},"text":"this_should_have_hover_text"}],"text":"\u003cUniOnHeikoille\u003e no_color "}
6. All colors and text formatting is gone.
7. Done.

### Expected result
All colours and text formatting should've showed up correctly.

### Log file link
there's nothing in log files 

### Specs and Details
Required information: 
- Windows 11 (22H2)
- 1.19.2
- Fabric Loader v0.14.10 & Fabric API v0.67.1+1.19.2
- Cloth Config v8.2.88 & Mod Menu v4.1.1
- Mods:  
[✔] 1.19.x-wmch-1.19.2-1.5.5   
[✔] cloth-config-8.2.88-fabric   [
[✔] fabric-api-0.67.1+1.19.2   
[✔] modmenu-4.1.1   
[✔]NoChatReports-FABRIC-1.19.2-v1.13.12

- `wmch.json` file (NOT PASTED)
default settings
- `chatlog.json` file (NOT PASTED)

### Additional context
Anything else that could possibly be relevant to this issue. A recommended use for this box is what happened leading up to the incident.

**Comment by JustLetterV** [comment]
I just turned "Convert to game message" setting to false for now

**Comment by mrbuilder1961** [comment]
does this always happen with all messages when CtGM is on, or just when player messages are sent?

**Comment by JustLetterV** [comment]
Only when [this](https://github.com/mrbuilder1961/WheresMyChatHistory/blob/6ef595408b0635b94ed01c80cb445b5086b32255/src/main/java/mechanicalarcane/wmch/mixin/MessageHandlerMixin.java#L53) is true eg. when message starts with "\<player\> any text".

**Comment by mrbuilder1961** [comment]
ok, seems like it's not rebuilding the output message correctly. i'll look into this
