### ISSUE TITLE
Cleaner 'Chat log toggle' - 1.19.2 - SUGGESTION

### ISSUE THREAD

**Issue by heldheld** [mrbuilder1961/WheresMyChatHistory#42]
**Is your feature request related to a problem? Please describe.**
I absolutely LOVE the 'Chat log toggle' option to re-add the chat log from the previous game session, but I don't like the fact that when I load up the first world after starting up the game, it immediately shows the log as if it was just sent in chat (which I understand it effectively is). It immediately clutters up the screen when you enter a world. This is especially jarring in a Single Player world as it kinda breaks the immersion for me.

**Describe the solution you'd like**
Have the chat log not show up as if it was just sent upon entering your first world after starting up the game. Just have it there when you open chat. I'm not sure if there's a way to force close the chat or if there's another way to do this but I'd love a clean look. If this could be combined with the Session Boundary that would be even better. Joining different hubs in minigame servers always shows the Session Boundary which is fine but if that would not show up as being just sent but only when you open chat it would look a lot cleaner.

**Describe alternatives you've considered**
As I've not seen any other mod restore Chat history after re-launching the game, there's not really any alternative to consider right now.

**Additional context**
.

**Comment by mrbuilder1961** [comment]
it sounds like you just don't want the restored messages to display as if they were just received? that's a good idea, i agree it is somewhat off-putting. 
about the session boundary with the chat log, that's also being discussed in #39.
however, the boundaries showing up in minigames could potentially be fixed, although i'm not sure if that would be worth the implementation or even wanted.

regardless, i can fix the main issue in a couple of days. thanks!

**Comment by heldheld** [comment]
> it sounds like you just don't want the restored messages to display as if they were just received?

That is exactly correct.


> regardless, i can fix the main issue in a couple of days. thanks!

Amazing! I'm looking forward to it :)
