### ISSUE TITLE
Add chat heads - 1.19.2 - SUGGESTION

### ISSUE THREAD

**Issue by stantios** [mrbuilder1961/WheresMyChatHistory#43]
**Is your feature request related to a problem? Please describe.**
As you have implemented chat features from other mods, I thought maybe you could include [this mod](https://modrinth.com/mod/chat-heads).

**Describe the solution you'd like**
Add a way to see Chat Heads

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mrbuilder1961** [comment]
I only added other mod features because they were all different version/loader types and weren't compatible together, and especially since chat heads already works flawlessly together with this mod, that would just be blatant copying. 

just install chat heads alongside this and you'll be good.

**Comment by stantios** [comment]
I would first off just like to say that I'm sorry for suggesting this idea and secondly [MoreChatHistory](https://modrinth.com/mod/morechathistory) is a Fabric mod and is on 1.19.2 as well so, couldn't you say that you copied this mod?

**Comment by mrbuilder1961** [comment]
I guess, but adding one method to increase a number vs adding a whole new feature that already exists in another mod just seems like a waste of time. but I do see your point.

**Comment by stantios** [comment]
I've checked out your mod and it seems that you can increase the chat history more (Greater than 16,384) so I think your mod is better and is more configurable.

**Comment by mrbuilder1961** [comment]
once a good amount of people join, i would probably have a vote on the discord server, or alternatively set up a vote on some website
