### ISSUE TITLE
chat display size - 1.19.2 - SUGGESTION

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#44]
**Is your feature request related to a problem? Please describe.**
Well whenever I open chat and it's been a while the chat shows all the way to the top taking up half the screen. I know there's a "maximum chat messages" thing but wasn't sure if that meant all messages or chat size. 

**Describe the solution you'd like**
An option to adjust chat size visually. Like so it doesn't take up half your screen

**Describe alternatives you've considered**
Blank...

**Additional context**
Pretty much said it all I think

**Comment by mrbuilder1961** [comment]
if you're talking about the chat window height, have you tried the minecraft options -> chat settings -> focused chat height?

**Comment by Aces-and-Jacks** [comment]
thanks. Didn't know about that
