### ISSUE TITLE
"Click to copy chat into clipboard" - 1.19.2-1.19.3 - SUGGESTION

### ISSUE THREAD

**Issue by Scarlaid** [mrbuilder1961/WheresMyChatHistory#45]
**Is your feature request related to a problem? Please describe.**
Might be only me but sometimes I want to copy some people chat and paste them somewhere else to store, like someone private message me a coordinate and I wanna save it into a Discord server or a note on Windows.

**Describe the solution you'd like**
And option (toggle-able of course) to allow players to copy the chat with just a single click

**Describe alternatives you've considered**
No alternatives could be found, for now

**Additional context**
![image](https://user-images.githubusercontent.com/90851437/206943921-c7ad6592-a676-4a1f-ae81-f9de00e44f36.png)
![image](https://user-images.githubusercontent.com/90851437/206943935-6ce97d3d-86e1-48cb-80d8-03747987fb8f.png)

*from another mod which I likely dont like until they really rewrite the whole chat stacking system*

**Comment by mrbuilder1961** [comment]
Have you tried the `/copymessage index <int>` command?

**Comment by Scarlaid** [comment]
> Have you tried the `/copymessage index <int>` command?

I actually haven't as I haven't read the full mod description, but since you mentioned it, having such feature clickable than using a command is more, convenient, I guess? 🤔

**Comment by mrbuilder1961** [comment]
Potentially, but your suggestion isn't clear as to where you would click to copy and what would be copied. All of the chat having this hover effect would be annoying, and copying the entire chat is as one string is pretty useless.

**Comment by Scarlaid** [comment]
> All of the chat having this hover effect would be annoying

Sadly this is what my suggestion was all about, same function described with the given pictures.
The best idea I would think of is:
- Only render the click-to-copy tooltip when hover around the timestamp, which won't annoy people when they hover over the chat.
- Add a small Unicode icon after the chat so when you click on it it would copy the chat with something like "Copied to Clipboard" as an Action Bar or Chat Annoucement (?)

Sorry for not being specific

**Comment by mrbuilder1961** [comment]
Actually I think I could implement something better, some menu with a list of chat messages you can search and filter through, then select and copy from. It would take a couple more months though, with finals and other issues to sort out first.

**Comment by Scarlaid** [comment]
Okay that's so much better than mine 🙌
Worth to wait so take your time, I guess

**Comment by mrbuilder1961** [comment]
See the new comment on #4.
