### ISSUE TITLE
session boundary? - 1.19.2 and 1.5.6 - BUG

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#46]
### Description
<img width="922" alt="Screen Shot 2022-12-18 at 4 43 30 PM" src="https://user-images.githubusercontent.com/106651342/208321152-838e23c5-e610-4693-8c61-0d591422af3a.png">
is this supposed to be a session boundary area?

### How to reproduce
Go into a single player world
see previous messages

### Expected result
A boundary line appearing for each time you join the world

### Log file link
https://mclo.gs/Fsa8eqU

### Specs and Details
Required information: 
- Mac OS
- 1.19.2
- Quilt 0.17.8 but probably same as most recent fabric and api 0.68.0
- Cloth Config v8 and Mod Menu 4.1.2 versions (if installed)
- list of all installed mods (can be a list *copied* from a log file **OR** a screenshot)

1.19.x-wmch-1.19.2-1.5.6.jar
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
accurate-maps-1.0-BETA+1.19.jar
AdaptiveTooltips-1.0.1-fabric-1.19.2.jar
advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
aimobs-1.0.1.jar
alternate-current-mc1.19-1.4.0.jar
AmbientEnvironment-fabric-1.19.2-8.0+3.jar
AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
amecs-1.3.8+mc.1.19-rc2.jar
antighost-1.19.1-fabric0.58.5-1.1.5.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
ArrowCam-1.0.1(1).jar
audio_engine_tweaks-1.2.3-1.19 build 3.jar
auditory-0.0.4-1.19.x.jar
autohud-2.5+1.19.1.jar
bedrockwaters-1.7.3+1.19.2.jar
bedrodium-0.2.1.jar
bendy-lib-fabric-2.1.1.jar
better-end-sky-0.1.1.jar
BetterAnimationsCollection-v4.0.5-1.19.2-Fabric.jar
betterbeds-1.2.0.jar
betterbiomeblend-1.19.0-1.3.6-fabric.jar
bettercommandblockui-0.3.0-1.19.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
bettermounthud-1.2.0.jar
BetterPingDisplay-Fabric-1.19.2-1.1.1.jar
betterstats-2.1+1.19.2.jar
BetterThirdPerson-Fabric-1.19-1.9.0.jar
BiomeParticleWeather-v4.0.0-1.19-Fabric.jar
Blanket Client tweaks-1.1.2.jar
block-entity-extended-rendering-2.0.0.jar
blur-2.6.0.jar
boathud-1.1.1.jar
Bookshelf-Fabric-1.19.2-16.2.16.jar
brb-1.6.0-fabric.jar
brokenleadwarner-1.0.0+1.19.2.jar
CameraOverhaul-1.3.1-fabric-universal.jar
Capes-1.4.5+1.19.jar
cardinal-components-api-5.0.2.jar
catalogue-fabric-1.7.0-1.19.2.jar
cave_dust-1.2.0.jar
celesteconfig-1.0.0.jar
celestial_1.19_fabric-1.3.3.jar
cem-0.7.1.jar
chat_heads-0.7.1-fabric-1.19.1.jar
chat-coords-0.2.2233.jar
chatcalc-3.0.12.jar
chime-1.3.0.jar
chunksfadein-2.1.0-1.19.jar
CITResewn-1.1.2+1.19.2.jar
ClearDespawn-fabric-1.19.2-1.1.10.jar
clientsidenoteblocks-2.2+1.19.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.22.jar
colormatic-3.1.2+mc.1.19.jar
colour-my-servers-1.0.2.jar
compact-scoreboard-1.0.0.jar
compacthelpcommand-fabric_1.19.2-1.7.jar
completeconfig-2.1.0.jar
condensed_creative-2.0.2+1.19-fabric.jar
configured-fabric-2.0.0-1.19.2.jar
continual-music-1.0.jar
continuity-2.0.1+1.19.jar
Controlling-fabric-1.19.2-10.0+7.jar
cr-compass-ribbon-fabric-2.8.2+1.19.1.jar
CraftPresence-2.0.0-alpha.1+1.19.2-universal.jar
CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
cyanide-fabric-1.19.2-3.0.1.jar
dark-graph-1.0.2.jar
DeathFinder-v4.1.2-1.19.2-Fabric.jar
deathlog-0.2.11+1.19.jar
Debugify-2.8.0.jar
DetailArmorBar-2.6.2+1.19-fabric.jar
disguiseheads-fabric-1.0.1-mc1.19.2.jar
DistinguishedPotions-v4.0.1-1.19.2-Fabric.jar
do-a-barrel-roll-2.3.1+1.19.2-fabric.jar
DripSounds-1.19-0.3.0.jar
dyed-fabric-1.19.2-1.1.0.jar
dynamic-fps-2.2.0.jar
dynamiccrosshair-4.0+1.19.2.jar
dynamiccrosshair-compat-2.0+1.19.2.jar
ears-fabric-1.19-1.4.6.jar
eating-animation-1.9.jar
effective-1.6+1.19.2.jar
elytra-recast-2.2.1.jar
ElytraPhysics-1.1.1.jar
emi_loot-0.5.0+1.19.jar
emi-0.5.2+1.19.2.jar
emiffect-0.1.4+1.19.2.jar
EMITrades-fabric-1.0.2+mc1.19.2.jar
emoji-type-2.0.1+1.19.jar
emuno-1.0.0.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.13.jar
enhanced_attack_indicator-1.0.4+1.19.jar
enhanced-searchability-mc1.19-3.0.1+build.9.jar
enhancedblockentities-0.7.2+1.19.2.jar
entity_texture_features_fabric_1.19.2-4.2.0.jar
entity-view-distance-1.0.2+1.19.jar
entityculling-fabric-1.5.2-mc1.19.jar
EquipmentCompare-1.19-fabric-1.3.1.jar
exordium-fabric-1.0.2-mc1.19.2.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
fabricskyboxes-0.6.1+mc1.19.2.jar
fabrishot-1.9.1.jar
fallingleaves-1.13.0+1.19.2.jar
Female-Gender-Mod-fabric-1.19.2-3.0.1.jar
ferritecore-5.0.3-fabric.jar
find-1.2.jar
firstperson-fabric-2.2.0-mc1.19.2.jar
ForgeConfigAPIPort-v4.2.9-1.19.2-Fabric.jar
FPS-Monitor-1.19-1.3.0-Fabric.jar
fsb-interop-1.1.3+mc1.19.2-build.25.jar
grabcraft-litematic-1.19.1-fabric0.58.5-0.5.jar
graphutil-fabric-1.0.0-mc1.19.jar
hatlist-1.3.jar
highlight-1.0.0-fabric.jar
Highlighter-1.19.1-fabric-1.1.4.jar
hitboxplus-1.19.2-0.2.2.jar
HorseDebug-1.2.4.jar
Iceberg-1.19.1-fabric-1.0.46.jar
indium-1.0.9+mc1.19.2.jar
inspecio-1.6.0+1.19.jar
inventory-control-tweaks-1.3.19+MC1.19-1.19.2.jar
inventoryfullalert-1.1.0-1.19.jar
iris-mc1.19.2-1.4.5.jar
item-model-fix-1.0.3+1.19.jar
ItemPhysicLite_FABRIC_v1.5.2_mc1.19.1.jar
Jade-1.19.1-fabric-8.6.3.jar
JadeAddons-1.19.2-fabric-3.0.0.jar
jsonem-0.1.2+1.19.jar
keymap-0.7.0-beta.1+1.19.2-fabric.jar
Kiwi-1.19.1-fabric-8.1.2.jar
krypton-0.2.1.jar
lambdabettergrass-1.3.0+1.19.jar
lambdynamiclights-2.1.2+1.19.jar
lazy-language-loader-0.3.1.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.19.2-fabric-1.3.3.jar
LetSleepingDogsLie-1.19.2-1.1.1.jar
lighty-1.0.5+1.19.1.jar
litematica-fabric-1.19.2-0.12.5.jar
lithium-fabric-mc1.19.2-0.10.4.jar
lunade-fastanim-1.5.6-1.19.jar
make_bubbles_pop-0.0.2-1.19.jar
malilib-fabric-1.19.2-0.13.0.jar
mazeworld-1.19.2-1.1.0.jar
mbp-1.4.jar
memoryleakfix-1.19.1-0.7.0.jar
menulogue-fabric-1.0.1-1.19.2.jar
MerchantMarkers-1.19.1-fabric-1.2.3.jar
microdurability-0.3.6+1.19.jar
midnightcontrols-1.7.1+1.19.jar
midnightlib-quilt-1.0.0-patch1.jar
MiniEffects-1.19.2-fabric-5.1.0.jar
minihud-fabric-1.19.2-0.23.3.jar
modelfix-1.8-fabric (1).jar
modmenu-4.1.2.jar
monsters-in-the-closet-1.0.3+1.19.jar
moreculling-1.19.1-0.10.1.jar
moremcmeta-1.19-3.0.5-fabric.jar
motionblur-1.0.1+mc1.19.jar
mouserate-framerate-1.0.3+1.19.jar
MouseTweaks-fabric-mc1.19-2.22.jar
movement-vision-1.4.0.jar
multiple-server-lists-mc1.19.1-3.0.2+build.10.jar
nether-coords-1.19.x-1.1.2.jar
niceload-0.1.3.jar
nicer-skies-1.0.0-1.19.2.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
notebook-2.0.0+1.19-alpha.jar
notenoughanimations-fabric-1.6.2-mc1.19.2.jar
ok_zoomer-5.0.0-beta.9+1.19.jar
optigui-1.1.6.jar
ostOverhaul-0.2.6-1.19.1.jar
PetOwner-1.8.3-1.19+.jar
PickUpNotifier-v4.2.0-1.19.2-Fabric.jar
player-animation-lib-fabric-0.4.0.jar
pling-1.5.0.jar
polymer-all-0.2.22+1.19.2.jar
PresenceFootsteps-1.6.3.jar
Prism-1.19.2-fabric-1.0.3.jar
puzzle-1.4.0-1.19.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar
quilt_loading_screen-4.0.0+1.19.jar
quilt-kotlin-libraries-1.0.0+kt.1.7.20+flk.1.8.5.jar
quiltgoslightlyfasterlol-0.0.3.jar
raised-fabric-1.19.2-1.1.4.jar
reacharound+1.19-1.1.0.jar
recursive-resources-2.2.2+1.19.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
remember-my-txt-1.0.0+MC1.19.jar
replaymod-1.19.2-2.6.9.jar
resourcepackchecker-1.19.2-1.0.0.jar
satin-1.9.0.jar
Screencapper-1.19-1.2.1.jar
screenshot_viewer-1.1.2-fabric-mc1.19x.jar
sheepconsistency-1.0.4.jar
show-me-your-skin-1.3.5+1.19.jar
SillInfoFabric.jar
smarthud-3.1.1+1.19.2.jar
Smooth Swapping 0.6 (1.19.2)-0.6.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.14+mc1.19.2-build.80.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.0.18.jar
stackcalc-revived-1.1.0.jar
starlight-1.1.1+fabric.ae22326.jar
statssearch-1.19.1-fabric0.58.5-1.0.1.jar
status-effect-bars-1.0.1+1.19.jar
statuseffecttimer-1.1.1+1.19.jar
super-secret-revival-1.2+1.19.jar
superfancyclouds-0.0.1+1.19.jar
TerraBlender-fabric-1.19.2-2.0.1.130.jar
testworld-1.0.0.jar
text-utilities-fabric-1.19.2-1.2.0.jar
third-person-maps-1.4.0+1.19.jar
thorium-1.3.2.jar
title-fix-1.0.1+MC1.17.1.jar
titlefixer-1.0+1.18.jar
tnttime-mc1.19.2-1.1.0.jar
tooltipsplus-1.3.0+1.19.jar
tooltiptweaks-1.1.0.jar
toomanybinds-0.3.2+1.19.jar
toomanyplayers-1.19-1.1.4.jar
transparent-5.1.2+1.19-fabric.jar
visualoverhaul-4.1.1.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.15-all.jar
wake-up-time-1.2.0.jar
waveycapes-fabric-1.2.2-mc1.19.2.jar
waxednotwaxed-1.1.3.jar
whats-that-slot-fabric-1.3.1+1.19.2.jar
whydoesmyglasssoundlikethat-1.0.jar
wmitaf-fabric-mc1.19-3.1.1.jar
world-name-gen-0.1.2+1.19.jar
worldtime-1.19.1-fabric0.58.5-1.3.1.jar
YetAnotherConfigLib-1.7.1.jar

Optional: 
- `wmch.json` file (NOT PASTED)
- `chatlog.json` file (NOT PASTED)

### Additional context
Anything else that could possibly be relevant to this issue. A recommended use for this box is what happened leading up to the incident.

**Comment by mrbuilder1961** [comment]
Yes, in the latest update the boundary line text default is `[$]`, where the $ is replaced with the world/server name. Currently the $ is required to be in the option.

If you want to get your old config settings back, look for `wmch_old.json` in the config folder and copy away.

However, looking at your log, there was an error trying to access your config file. did you notice anything different about your settings?

_note for me: optional boundary world $ (maybe others later), add file.separator to util const paths_

**Comment by Aces-and-Jacks** [comment]
oh didn't realize it was separated by world name, guess I confused myself with the world name being test and the first text being test. And I didn't notice anything different with setting other than the new links
