### ISSUE TITLE
Error while executing client-sided command - 1.19.2, 1.5.6

### ISSUE THREAD

**Issue by srnyx** [mrbuilder1961/WheresMyChatHistory#49]
### Description
When trying to execute a **SERVER** command (no idea why it says client-sided), it fails to execute and I get this error: https://paste.srnyx.xyz/ejacezilar.properties
This happens with every command by the way.

### How to reproduce
I'm not exactly sure, to be honest, maybe it's another mod conflicting?

### Expected result
The command should be executed. But instead, this is sent in chat:
`Cannot invoke "com.mojang.brigadier.CommandDispatcher.execute(String, Object)" because "net.fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispatcher" is null`

### Log file link
Here's the relevant messages from `latest.log` (I'm too lazy to obfuscate private information, and I think the 2 errors at the end are the cause): https://paste.srnyx.xyz/begodozadi.csharp

### Specs and Details
- Computer OS: Windows 11
- Minecraft version: 1.19.2
- Fabric version: 0.14.11
- Fabric API version: 0.70.0
- Cloth Config version: 8.2.88
- Mod Menu version: 4.1.2
- List of all installed mods: https://paste.srnyx.xyz/henabimufa.css
- `wmch.json` file: https://paste.srnyx.xyz/xiruyabone.json
- `chatlog.json` file: https://paste.srnyx.xyz/raw/umohifokow

### Additional context
I've confirmed it's Where's My Chat History? that is causing this issue (disabling it fixes it).

**Comment by mrbuilder1961** [comment]
Is the WMCH jar file from curseforge/modrinth?

**Comment by srnyx** [comment]
> Is the WMCH jar file from curseforge/modrinth?

Yes, CurseForge

**Comment by mrbuilder1961** [comment]
This is so odd, I thought I fixed this already. I can't use my computer for a couple days, so if you really want a fix you can follow the build instructions on the README for a fix now.
