### ISSUE TITLE
Suggestion: Add the ability to copy/reply messages

### ISSUE THREAD

**Issue by EGOIST1372** [mrbuilder1961/WheresMyChatHistory#5]
Add the ability to copy a certain part/whole part of message that already is sent in chat history. useful for commands and numbers and messages that you want to copy but you can't in vanilla or replying to someone in chat just by 2 clicks:
can achieve by adding right click ability on messages so a small pop up menu opens that has several options like reply, select all, select word, copy and etc.

**Comment by mrbuilder1961** [comment]
That's a great idea! I don't think I'll add replying, that seems more like a plugin/server-side mod sorta thing; but I love the idea to copy/select messages. Maybe I could somehow work that into the search function... 🤷‍♂️

**Comment by EGOIST1372** [comment]
that's great news :D
thanks

**Comment by mrbuilder1961** [comment]
I think I have the hard part of this feature done for the next update, not much more left to do!

**Comment by mrbuilder1961** [comment]
[Fixed in the latest release!](https://github.com/mrbuilder1961/WheresMyChatHistory/releases/tag/1.4.5-1.18.x) Feel free to reopen this if any problems arise.
