### ISSUE TITLE
incompatible fabric loader on quilt - 1.19.3 and 1.5.7

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#51]
### Description
<img width="912" alt="Screen Shot 2023-01-09 at 2 36 40 PM" src="https://user-images.githubusercontent.com/106651342/211393553-d56f3ed6-ab49-4be2-a5ca-3cbe2f40820a.png">

### How to reproduce
Download mod on quilt with recent quilt fabric api update
doesn't work

### Expected result
For the mod to work

### Log file link
https://mclo.gs/Tis9A0U

### Specs and Details
Required information: 
- Computer OS: MacOS
- Minecraft version: 1.19.3
- Fabric and API versions: quilt 0.17.8 and Quilted Fabric API  5.0.0-alpha.9+0.72.0-1.19.3
- Cloth Config and Mod Menu versions (if installed): 9.0.94 and 5.0.2
- list of all installed mods (can be a list *copied* from a log file **OR** a screenshot)
Optional: 
- `wmch.json` file (NOT PASTED)
- `chatlog.json` file (NOT PASTED)

### Additional context
Mod dependency probably needs to be updated

**Comment by mrbuilder1961** [comment]
is there a newer version of quilt that has fabric loader `0.14.12`?

**Comment by Aces-and-Jacks** [comment]
oh wait I got that confused. It's not the fabric api but the fabric loader itself. My mistake
