### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by mrbuilder1961** [mrbuilder1961/WheresMyChatHistory#53]
# 👀
(new, better name and icon plus preview images coming soon!)

**Comment by mrbuilder1961** [comment]
I forgot to mention that once this is completed, references to the current name (`wmch`, Where's My Chat History, etc.) will be invalidated. I will make sure to replace and update everything, but note that **I will be changing the repository name as well**.
Just in case this is referenced anywhere and you really need to know, the new name is going to be "Chat Patches" and the id will be `chatpatches`.

**Comment by mrbuilder1961** [comment]
Last minute decision, id is actually going to be `chat_patches`.

**Comment by Aces-and-Jacks** [comment]
confused me when I first saw this on curseforge. Had to read description to remember
