### ISSUE TITLE
"[ChatLog()] Couldn't create file connections" even when chat saving is disabled - 1.19.2 / 1.5.7

### ISSUE THREAD

**Issue by SplendidAlakey** [mrbuilder1961/WheresMyChatHistory#54]
### Description

An error appears in the logs, mentioning failing to locate `chatlog.json`, even if it's not supposed to exist, due to saveChat option being set to false.

### How to reproduce

1. Install the mod and launch the game to generate configs
2. Close the game, edit `wmch.json` to disable saveChat feature
3. Re-launch the game and open `latest.log`, find the line that says "[ChatLog()] Couldn't create file connections", even though it's not supposed to even try

Note: the error will appear, if you have saveChat enabled, as well. I believe this is also not supposed to happen, because there's no chat to speak of yet, we are only in the main menu.

### Expected result

Don't attempt to log chat at all, if the feature is disabled. If that's already the case, then suppress the errors.

Don't attempt to log chat in main menu.

### Log file link

https://gist.github.com/SplendidAlakey/fbbdbd6deb8d0651db5150bbc713d0d3

### Specs and Details

Required information: 
- Win10
- 1.19.2
- 0.14.13 + 0.73.0
- Cloth Config and Mod Menu aren't installed
- no other mods
Optional: 
- [wmch.zip](https://github.com/mrbuilder1961/WheresMyChatHistory/files/10474202/wmch.zip)
- `chatlog.json` doesn't exist

### Additional context

-

**Comment by mrbuilder1961** [comment]
This has already been fixed in the 1.19.3 mod version and will be backported shortly!

**Comment by mrbuilder1961** [comment]
Closed with https://github.com/mrbuilder1961/WheresMyChatHistory/commit/0465ef758b77143aba1177af9334d6c954178130.
