### ISSUE TITLE
Duplicate counter doesn't seem to recognise differently formatted text - WMCH 193.1.1

### ISSUE THREAD

**Issue by JustLetterV** [mrbuilder1961/WheresMyChatHistory#56]
### Description
Duplicate counter doesn't regognise text formatting in messages and treats differently formatted messages as same messages.

### How to reproduce
1. Go to singleplayer world
2. Use command -> `/tellraw @p {"text":"❤this is a message (maybe)","color":"yellow"}`
![image](https://user-images.githubusercontent.com/75657829/213951802-c32bca8c-704f-412e-93f5-3df375575687.png)
3. Use command -> `/tellraw @p {"text":"❤this is a message (maybe)","color":"red"}`
![image](https://user-images.githubusercontent.com/75657829/213951840-99a53767-9274-4e22-8275-802c9ba14b7c.png)
4. Use command -> `/tellraw @p {"text":"❤this is a message (maybe)","underlined":true,"color":"yellow"}`
![image](https://user-images.githubusercontent.com/75657829/213952148-6b115f2b-dfa0-47a9-bb5d-f4d17241351b.png)

### Expected result
Duplicate counter would treat differently formatted messages as different messages

### Log file link
nothing in the log file

### Specs and Details
Required information:
- Windows 11
- WMCH 193.1.1
- FabricAPI 0.73.0+1.19.3 
- YetAanotherConfigLib 2.2.0
- Mod Menu 5.0.2
- no other mods
### Optional:
- `wmch.json` file default settings

**Comment by mrbuilder1961** [comment]
this is an intended feature

**Comment by JustLetterV** [comment]
Okay, later after I submitted this issue I thought about that, makes more sense afterward, thank you for the reply!
