### ISSUE TITLE
Few suggestions related to config - WMCH 193.1.1

### ISSUE THREAD

**Issue by JustLetterV** [mrbuilder1961/WheresMyChatHistory#57]
**Is your feature request related to a problem? Please describe.**
These suggestions are not related to any problems.
Suggestions:
1. Make `playername text` option match vanilla by default. (<$>)
2. Change `Boundary text` option type to [ListOption](https://docs.isxander.dev/yet-another-config-lib/home#lists) and treat new entries in list as new line of text. Also allow the use of empty lines somehow, maybe some kind of placeholder for empty line? For example "{empty}".

These changes would make WMCH more user friendly since first suggestion makes this mod more vanilla like and that's what most players are used to. Second suggestion would allow more user friendly way to add new lines for 'Boundary text' option.

Thank you for reading ❤️ 

**Describe the solution you'd like**
Already described above.

**Describe alternatives you've considered**
Already described above.

**Additional context**
No additional context.

**Comment by mrbuilder1961** [comment]
i agree with the first one.
however, for the second one you can just use `\n`. But if that isn't already stated directly in the description tooltip, I will add it.

**Comment by JustLetterV** [comment]
That isn't stated directly in the description tooltip, but there is information about formatting codes so anyone can find that information if they're looking for it. Thank you for the reply :)
