### ISSUE TITLE
Can't open config - v193.2.1

### ISSUE THREAD

**Issue by penpen-uwu** [mrbuilder1961/WheresMyChatHistory#60]
### Description
I cant open the config for the mod in mod menu mod in fabric

### How to reproduce
1. Open mod menu

### Expected result
There should be the config button

**Comment by MenacingPerson** [comment]
Yeah it disappeared

**Comment by MenacingPerson** [comment]
In fact, the config file itself does not exist on a new instance of mc.

**Comment by mrbuilder1961** [comment]
Please provide a log file and if any config file exists, that as well.

**Comment by MenacingPerson** [comment]
Seems to be some mod conflicts - on a new mc instance it does get a button, but with other mods:

https://mclo.gs/2Z3lXEG

**Comment by mrbuilder1961** [comment]
could you try with this provided version and attach the log again? i need to see what kind of compatibility issue this is.
(mediafire because github doesn't accept jars: https://www.mediafire.com/file/2ygq5uf1s5khke4/chatpatches-193.2.2.jar/file)

**Comment by Juras99** [comment]
Same situation here - no config button in the mod menu. The config file itself does not appear in the directory.

**Comment by mrbuilder1961** [comment]
Try the main jar in `libs/` from the just-published version [here](https://github.com/mrbuilder1961/ChatPatches/suites/10649844823/artifacts/532129473).

**Comment by Juras99** [comment]
It is indeed working with the version you've provided, thank you.

**Comment by MenacingPerson** [comment]
Yeah it works on the latest version from modrinth. This can be closed I think.
