### ISSUE TITLE
timestamp doesn't show - 192.2.0

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#61]
### Description

![2023-01-31_02 50 31](https://user-images.githubusercontent.com/106651342/215699887-1427636f-2342-46c2-a937-7d12f716a70a.png)

![2023-01-31_02 52 21](https://user-images.githubusercontent.com/106651342/215699906-ac206145-2423-4778-803e-4ec4a1768d9c.png)

### How to reproduce
1. Install on 1.19.2 
2. Change any reference to previous name format in files
3. No timestamp

### Expected result
Timestamp to show

### Log file link
https://mclo.gs/XPRgsZc

### Specs and Details
Required information:
- MacOS 12.4
- 192.2.0 (1.19.2)
- Quilt 0.17.10 and Quilted fabric api 4.0.0-beta.27+0.73.0-1.19.2
- YetAanotherConfigLib: 2.2.0-for-1.19.2 and Mod Menu: 4.1.2
betterbeds-1.2.0.jar
betterbiomeblend-1.19.0-1.3.6-fabric.jar
bettercommandblockui-0.3.1-1.19.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
bettermounthud-1.2.0.jar
BetterPingDisplay-Fabric-1.19.2-1.1.1.jar
betterstats-2.1.1+1.19.2.jar
BetterThirdPerson-Fabric-1.19-1.9.0.jar
BiomeParticleWeather-v4.0.0-1.19-Fabric.jar
Blanket Client tweaks-1.1.2.jar
block-entity-extended-rendering-2.0.0.jar
blur-2.6.0.jar
boathud-1.1.2.jar
Bookshelf-Fabric-1.19.2-16.2.17.jar
bounced-1.19.2-1.0.4.jar
brb-1.6.0-fabric.jar
brokenleadwarner-1.1.0+1.19.2.jar
CameraOverhaul-1.4.0-fabric-universal.jar
Capes-1.4.5+1.19.jar
cardinal-components-api-5.0.2.jar
cardinalboats_1.19_1.2.3.jar
catalogue-fabric-1.7.0-1.19.2.jar
cave_dust-1.2.0.jar
celesteconfig-1.0.0.jar
celestial_1.19_fabric-1.3.3.jar
cem-0.7.1.jar
chat_heads-0.9.0-fabric-1.19.2.jar
chat-coords-0.2.2233.jar
chatcalc-3.0.12.jar
chatpatches-192.2.0.jar
chime-1.3.0.jar
chunksfadein-v3.0.7-1.19.jar
CITResewn-1.1.2+1.19.2.jar
ClearDespawn-fabric-1.19.2-1.1.10.jar
clientsidenoteblocks-2.2+1.19.jar
cloth-config-8.2.88-fabric.jar
collective-1.19.2-6.43.jar
colormatic-3.1.2+mc.1.19.jar
colour-my-servers-1.0.2.jar
compact-scoreboard-1.0.0.jar
completeconfig-2.1.0.jar
condensed_creative-2.0.2+1.19-fabric.jar
configured-fabric-2.0.0-1.19.2.jar
continual-music-1.0.jar
continuity-2.0.1+1.19.jar
Controlling-fabric-1.19.2-10.0+7.jar
cr-compass-ribbon-fabric-2.8.2+1.19.1.jar
CraftPresence-2.0.0-alpha.3+1.19.2.jar
CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
cyanide-fabric-1.19.2-3.0.1.jar
damagevignette-1.1.2.jar
dark-graph-1.0.3.jar
darkness-fabric-mc119-2.0.101.jar
DeathFinder-v4.1.2-1.19.2-Fabric.jar
deathlog-0.2.11+1.19.jar
Debugify-2.8.0.jar
DetailArmorBar-2.6.2+1.19-fabric.jar
disguiseheads-fabric-1.0.1-mc1.19.2.jar
DistinguishedPotions-v4.0.1-1.19.2-Fabric.jar
do-a-barrel-roll-2.6.1+1.19.2-fabric.jar
DripSounds-1.19-0.3.0.jar
dyed-fabric-1.19.2-1.1.0.jar
dynamic-fps-2.2.0.jar
dynamiccrosshair-5.0+1.19.2-fabric.jar
dynamiccrosshair-compat-3.1+1.19.2.jar
ears-fabric-1.19-1.4.6.jar
eating-animation-1.9.jar
effective-1.6+1.19.2.jar
elytra-recast-2.2.1.jar
ElytraPhysics-1.1.1.jar
emi_loot-0.6.0+1.19.jar
emi-0.6.3+1.19.2.jar
emiffect-0.1.4+1.19.2.jar
EMITrades-fabric-1.0.2+mc1.19.2.jar
emoji-type-2.0.1+1.19.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.14.jar
enhanced_attack_indicator-1.0.4+1.19.jar
enhanced-searchability-mc1.19-3.0.1+build.9.jar
enhancedblockentities-0.7.2+1.19.2.jar
Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar
entity_texture_features_fabric_1.19.2-4.3.1.jar
entity-view-distance-1.0.2+1.19.jar
entityculling-fabric-1.5.2-mc1.19.jar
EquipmentCompare-1.19-fabric-1.3.1.jar
exordium-fabric-1.0.2-mc1.19.2.jar
explosive-enhancement-1.0.1-1.19.2.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
fabricskyboxes-0.6.2+mc1.19.2.jar
fabrishot-1.9.1.jar
fallingleaves-1.13.0+1.19.2.jar
Female-Gender-Mod-fabric-1.19.2-3.0.1.jar
ferritecore-5.0.3-fabric.jar
find-1.2.jar
firstperson-fabric-2.2.2-mc1.19.2.jar
FogLooksGoodNow-1.1.1.jar
ForgeConfigAPIPort-v4.2.10-1.19.2-Fabric.jar
FPS-Monitor-1.19-1.3.0-Fabric.jar
FpsReducer2-fabric-1.19.2-2.1.jar
fsb-interop-1.1.3+mc1.19.2-build.25.jar
geckolib-quilt-1.19-3.1.40.jar
grabcraft-litematic-1.19.1-fabric0.58.5-0.5.jar
graphutil-fabric-1.0.0-mc1.19.jar
hatlist-1.3.jar
highlight-1.0.0-fabric.jar
Highlighter-1.19.1-fabric-1.1.4.jar
hitboxplus-1.19.2-0.2.2.jar
HorseDebug-1.2.4.jar
Iceberg-1.19.1-fabric-1.0.46.jar
indium-1.0.9+mc1.19.2.jar
infineffect-1.0.jar
inspecio-1.6.0+1.19.jar
inventory-control-tweaks-1.3.19+MC1.19-1.19.2.jar
inventoryfullalert-1.1.0-1.19.jar
iris-mc1.19.2-1.5.0.jar
item-model-fix-1.0.3+1.19.jar
ItemPhysicLite_FABRIC_v1.5.2_mc1.19.1.jar
Jade-1.19.1-fabric-8.7.3.jar
JadeAddons-1.19.2-fabric-3.0.0.jar
jsonem-0.1.2+1.19.jar
keymap-0.7.0-beta.1+1.19.2-fabric.jar
Kiwi-1.19.1-fabric-8.1.2.jar
krypton-0.2.1.jar
lambdabettergrass-1.3.0+1.19.jar
lambdynamiclights-2.2.0+1.19.2.jar
lazy-language-loader-0.3.1.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.19.2-fabric-1.3.3.jar
LetSleepingDogsLie-1.19.2-1.1.1.jar
lighty-1.1.0+1.19.1.jar
litematica-fabric-1.19.2-0.12.6.jar
lithium-fabric-mc1.19.2-0.10.4.jar
loadingscreentips-1.1.0.jar
logcleaner-1.0.0.jar
lootbeams-2.0.5.jar
lunade-fastanim-1.5.7.jar
macos-input-fixes-1.2.jar
make_bubbles_pop-0.0.2-1.19.jar
malilib-fabric-1.19.2-0.13.0.jar
mazeworld-1.19.2-1.1.0.jar
memoryleakfix-1.19.1-0.7.0.jar
menulogue-fabric-1.0.1-1.19.2.jar
MerchantMarkers-1.19.1-fabric-1.2.3.jar
microdurability-0.3.6+1.19.jar
midnightcontrols-1.7.4+1.19.jar
midnightlib-quilt-1.0.0-patch1.jar
minihud-fabric-1.19.2-0.23.3.jar
MixinConflictHelper-1.2.0.jar
modelfix-1.8-fabric (1).jar
modmenu-4.1.2.jar
monsters-in-the-closet-1.0.3+1.19.jar
moreculling-1.19.1-0.14.0.jar
MoreCullingExtra-1.1-backport_1.19.2.jar
moremcmeta-1.19-3.0.5-fabric.jar
motionblur-1.0.1+mc1.19.jar
mouserate-framerate-1.0.3+1.19.jar
MouseTweaks-fabric-mc1.19-2.22.jar
movement-vision-1.4.0.jar
multiplayer-button-1.0.0.jar
multiple-server-lists-mc1.19.1-3.0.2+build.10.jar
nether-coords-1.19.x-1.1.2.jar
niceload-0.1.3.jar
nicer-skies-1.2.0+1.19.2.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
notebook-2.0.0+1.19-alpha.jar
notenoughanimations-fabric-1.6.2-mc1.19.2.jar
ok_zoomer-5.0.0-beta.9+1.19.jar
optigui-1.1.6.jar
owo-lib-0.9.3+1.19.jar
PetOwner-1.8.3-1.19+.jar
PickUpNotifier-v4.2.0-1.19.2-Fabric.jar
player-animation-lib-fabric-0.4.2.jar
pling-1.5.0.jar
pocketwatch-1.0.0+1.19.jar
polymer-all-0.2.25+1.19.2.jar
PresenceFootsteps-1.6.4.jar
Prism-1.19.2-fabric-1.0.3.jar
puzzle-1.4.2-1.19.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
qfapi-4.0.0-beta.27_qsl-3.0.0-beta.29_fapi-0.73.0_mc-1.19.2.jar
quilt_loading_screen-4.0.0+1.19.jar
quilt-kotlin-libraries-1.0.2+kt.1.8.0+flk.1.9.0.jar
quiltgoslightlyfasterlol-0.0.3.jar
raised-fabric-1.19.2-1.1.4.jar
reacharound+1.19-1.1.2.jar
recursive-resources-2.2.2+1.19.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
remember-my-txt-1.0.0+MC1.19.jar
replaymod-1.19.2-2.6.9.jar
resourcepackchecker-1.19.2-1.0.0.jar
satin-1.9.0.jar
screenshot_viewer-1.1.2-fabric-mc1.19x.jar
sheepconsistency-1.0.4.jar
show-me-your-skin-1.3.7+1.19.jar
SillInfoFabric.jar
Smooth Swapping 0.6 (1.19.2)-0.6.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
Sort-1.0.2.jar
soundphysics-fabric-1.19.2-1.0.18.jar
spark-1.10.17-fabric.jar
stackcalc-revived-1.1.0.jar
stairautojump-0.0.6.jar
starlight-1.1.1+fabric.ae22326.jar
statssearch-1.19.1-fabric0.58.5-1.0.1.jar
status-effect-bars-1.0.1+1.19.jar
statuseffecttimer-1.1.1+1.19.jar
super-secret-revival-1.2+1.19.jar
superfancyclouds-0.0.1+1.19.jar
TerraBlender-fabric-1.19.2-2.0.1.136.jar
testworld-1.0.0.jar
text-utilities-fabric-1.4.2+1.19.2.jar
third-person-maps-1.4.0+1.19.jar
thorium-1.3.2.jar
titlefixer-1.0+1.18.jar
tnttime-mc1.19.2-1.1.0.jar
tooltipsplus-1.3.0+1.19.jar
tooltiptweaks-1.1.0.jar
toomanybinds-0.3.3+1.19.jar
toomanyplayers-1.19-1.1.4.jar
transparent-5.1.2+1.19-fabric.jar
usageticker-1.0.0-1.19.2.jar
visualoverhaul-4.1.1.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.27-all.jar
wake-up-time-1.2.0.jar
waveycapes-fabric-1.3.0-mc1.19.2.jar
whats-that-slot-fabric-1.3.1+1.19.2.jar
whydoesmyglasssoundlikethat-1.0.jar
wmitaf-fabric-mc1.19-3.1.1.jar
world-name-gen-0.1.2+1.19.jar
worldtime-1.19.1-fabric0.58.5-1.3.1.jar
YetAnotherConfigLib-2.2.0-for-1.19.2.jar

Optional:
- `chatpatches.json` file (pasted like: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
Anything else that could possibly be relevant to this issue. A recommended use for this box is what happened leading up to the incident.

**Comment by mrbuilder1961** [comment]
could you paste your config file?

**Comment by Aces-and-Jacks** [comment]
<img width="1136" alt="Screen Shot 2023-01-31 at 12 08 48 PM" src="https://user-images.githubusercontent.com/106651342/215832911-865078b9-d259-4cc4-b2d0-53f48a7e5d0f.png">

**Comment by mrbuilder1961** [comment]
is the config file named `chatpatches.json`? do any other options not save?

**Comment by Aces-and-Jacks** [comment]
I renamed it to chatpatches.json when I updated the mod

**Comment by Aces-and-Jacks** [comment]
I can try deleting the config and see if that works

**Comment by Aces-and-Jacks** [comment]
huh...worked

**Comment by Aces-and-Jacks** [comment]
guess I should've tried that first. However I did not think of that at the time. Sorry for the trouble

**Comment by Aces-and-Jacks** [comment]
tho I renamed the config so shouldn't that make it update?

**Comment by mrbuilder1961** [comment]
that's weird, maybe it was in the wrong order or something. glad it's resolved though
