### ISSUE TITLE
disconnect from server when I type - 192.2.1

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#63]
### Description
I type and I get disconnected

### How to reproduce
join server, type, get disconnected

### Expected result
Not to get disconnected

### Log file link
https://mclo.gs/3I7viPe

### Specs and Details
Required information:
- MacOS
- 192.2.1
- Quilt 0.17.11 and API 4.0.0-beta.28+0.73.2-1.19.2
- YetAanotherConfigLib 2.2.0-for-1.19.2 and Mod Menu 4.1.2
- list of all installed mods (can be a list *copied* from a log file **OR** a screenshot)

Optional:
- `chatpatches.json` file (pasted like: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
I wasn't sure if it had to do with this mod but saw a mixing relating to this mod so wasn't sure. It can also be that the server has something on it that makes it compatible with bedrock, since it works on normal servers

**Comment by Aces-and-Jacks** [comment]
if it isn't caused by this mod you can just close this

**Comment by Aces-and-Jacks** [comment]
ok not caused by this mod, so never mind

**Comment by Aces-and-Jacks** [comment]
figured it out I think. All good

**Comment by Aces-and-Jacks** [comment]
disregard that last one. I don't get kicked anymore but chat messages don't show

**Comment by Aces-and-Jacks** [comment]
ok it's some weird server thing for that type of server. I'll just stop commenting about it. you can ignore this

**Comment by mrbuilder1961** [comment]
i went through your log just in case and i didn't find any errors relating to chat patches
