### ISSUE TITLE
Suggestion summary - Config option for logging of restored chat

### ISSUE THREAD

**Issue by TechPro424** [mrbuilder1961/WheresMyChatHistory#65]
**Is your feature request related to a problem? Please describe.**
The log is unnecessarily spammed with "chat restored" messages

**Describe the solution you'd like**
I'd like a config option for enabling/disabling the logging of "chat restored" messages

**Comment by mrbuilder1961** [comment]
Good idea, I think I'll just disable it from logging entirely though

**Comment by TechPro424** [comment]
@mrbuilder1961 it's still logging in latest.log though

**Comment by mrbuilder1961** [comment]
can you attach a log file? when i tested it there were no restored logs

**Comment by TechPro424** [comment]
https://mclo.gs/p9tmFvU

**Comment by mrbuilder1961** [comment]
the fix hasn't been backported to 1.19.2 yet
