### ISSUE TITLE
Compatibility with figura and certain servers - 192.2.1

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#66]
### Description
Whenever I join on certain servers like `visit.uncensoredlibrary.com` with figura installed it causes an error when chatting

### How to reproduce
Install chat patches and figura and go onto `visit.uncensoredlibrary.com`
Unable to chat

### Expected result
I'm able to chat

### Log file link
Don't paste the whole log here!! Just copy and paste it into a site like `mclo.gs` or `pastebin.com`. Logs are located in the Minecraft directory folder, under `/logs` and `/crash-reports`.

### Specs and Details
Required information:
- MacOS
- 192.2.1
- Quilt 0.18.3 and 4.0.0-beta.29+0.75.1-1.19.2 API
- YetAanotherConfigLib 2.2.0-for-1.19.2 and Mod Menu 4.1.2
- list of all installed mods (can be a list *copied* from a log file **OR** a screenshot)

Optional:
- `chatpatches.json` file (pasted like: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
https://github.com/Kingdom-of-The-Moon/FiguraRewriteRewrite/issues/66 has all the logs and context

**Comment by mrbuilder1961** [comment]
that error only occurs when Chat Patches doesn't modify messages, which should be never even if all of the modules are disabled. could you provide a screenshot or video as well?

**Comment by Aces-and-Jacks** [comment]
A screen shot of chat patches with figura on the server?

**Comment by mrbuilder1961** [comment]
yes, a few messages would be great

**Comment by Aces-and-Jacks** [comment]
<img width="922" alt="Screen Shot 2023-03-11 at 3 57 26 PM" src="https://user-images.githubusercontent.com/106651342/224511362-b3f94bd1-4ecb-4247-b275-b0ee11cbcb13.png">
<img width="966" alt="Screen Shot 2023-03-11 at 3 57 56 PM" src="https://user-images.githubusercontent.com/106651342/224511364-c3
<img width="922" alt="Screen Shot 2023-03-11 at 3 58 14 PM" src="https://user-images.githubusercontent.com/106651342/224511367-1386d81f-24cc-4328-9252-1b22e0afc39b.png">
24d877-145a-4313-b5db-2ba43a4566c9.png">

**Comment by Aces-and-Jacks** [comment]
ok that appeared wrong

**Comment by Aces-and-Jacks** [comment]
<img width="922" alt="Screen Shot 2023-03-11 at 3 57 26 PM" src="https://user-images.githubusercontent.com/106651342/224511385-878e8752-bf10-4172-b1ec-34384f013ec7.png">

this

<img width="966" alt="Screen Shot 2023-03-11 at 3 57 56 PM" src="https://user-images.githubusercontent.com/106651342/224511395-82ba0996-25d0-45cc-a87c-dc24ae81cf03.png">

this

<img width="922" alt="Screen Shot 2023-03-11 at 3 58 14 PM" src="https://user-images.githubusercontent.com/106651342/224511396-5d6fff53-89c6-496f-9361-3d3880572b02.png">

**Comment by Aces-and-Jacks** [comment]
Tried typing a . and it didn't send

**Comment by Aces-and-Jacks** [comment]
<img width="922" alt="Screen Shot 2023-03-11 at 4 02 00 PM" src="https://user-images.githubusercontent.com/106651342/224511500-54ce3cf3-1a3d-42fb-b168-395dec04f35f.png">

this and

<img width="922" alt="Screen Shot 2023-03-11 at 4 02 21 PM" src="https://user-images.githubusercontent.com/106651342/224511503-c966859e-4804-4280-96ba-c9fe4c22ea68.png">

are without figura

**Comment by Aces-and-Jacks** [comment]
<img width="922" alt="Screen Shot 2023-03-11 at 4 06 20 PM" src="https://user-images.githubusercontent.com/106651342/224511647-33718742-72fb-43bf-9119-48a9434c3e5e.png">

This and

<img width="922" alt="Screen Shot 2023-03-11 at 4 06 33 PM" src="https://user-images.githubusercontent.com/106651342/224511649-a63dfbb8-dd73-4ea2-b461-ce177f1e9056.png">

are with figura but not chat patches

**Comment by Aces-and-Jacks** [comment]
So first one is with both installed, second is chat patches and not figura, third is figura but not chat patches

**Comment by mrbuilder1961** [comment]
and what kind of things does figura do to the chat?

**Comment by Aces-and-Jacks** [comment]
@lenrik1589

**Comment by Aces-and-Jacks** [comment]
I don't really know

**Comment by mrbuilder1961** [comment]
in the meantime, you can try disabling the duplicate message counter.
i'll also try and add some sort of error catching so it doesn't prevent chatting if errors occur in the future.

**Comment by lenrik1589** [comment]
> and what kind of things does figura do to the chat?

Figura is a avatar creation mod that provides different ways to interact with client
Figura does several things to the chat box:
- It provides a way for user to intercept contents of a message that has arrived on client
- It preprocesses message to replace all occurrences of username with name set by it's avatar as well as to add it's badges (like figura user badge and other special badges)
- lastly it allows users to use emojis provided with mod in the same style that discord does (i.e. `I :heart: you` will be changed to `I ♥ you` if emojis are enabled)
both badges and custom emojis are made using custom fonts
that is all (as far as i remember, though for more accurate answer it would probably be best to ask @Francy-chan)

**Comment by mrbuilder1961** [comment]
ok thanks for the info, i pushed a few commits that should hopefully fix the issue. @Aces-and-Jacks could you see if the error still occurs using the main jar from https://github.com/mrbuilder1961/ChatPatches/suites/11501286023/artifacts/594346079 ?

**Comment by Aces-and-Jacks** [comment]
the jar under libs? The one that isn't source?

**Comment by Aces-and-Jacks** [comment]
Yup works now. Thought it didn't since there was an error, tho the chat still showed text, but went out and back in, and it worked.

**Comment by Aces-and-Jacks** [comment]
Wasn't sure if you wanted this closed until the fix was released or not so I'll just close

**Comment by mrbuilder1961** [comment]
so just to be clear, are messages normal again or do they look like vanilla?

**Comment by Aces-and-Jacks** [comment]
<img width="922" alt="Screen Shot 2023-03-12 at 4 26 03 PM" src="https://user-images.githubusercontent.com/106651342/224571620-9b9fa923-e31f-4acd-805b-f09cab73a271.png">

yup, works

**Comment by Aces-and-Jacks** [comment]
Do you plan on back porting this to 1.19.2?

**Comment by mrbuilder1961** [comment]
probably at some point but not for at least a couple weeks
