### ISSUE TITLE
Could you make the chat duplication stacker act more like the compact chat mod?

### ISSUE THREAD

**Issue by Bswuave** [mrbuilder1961/WheresMyChatHistory#67]
![2023-03-13_00 11 26](https://user-images.githubusercontent.com/126287004/224613434-dc1a5206-59ed-4e7a-8792-d5106c66d033.png)

 Okay so as the image above shows this is how it currently works, but could you make it so every message that is the exact same stacks still instead of checking lines? Just like the title says, how the mod compact chat does it ! I think it would make this mod a lot smoother looking :)
 Especially on bigger servers with a lot of chat!

**Comment by mrbuilder1961** [comment]
does compact chat have a github or open source link i can take a look at?

**Comment by Bswuave** [comment]
> does compact chat have a github or open source link i can take a look at?

Indeed there is! here is another example btw, see here how these two messages are similar but didn't stack? 
![2023-03-13_08 27 20](https://user-images.githubusercontent.com/126287004/224715821-e0569b3e-46f0-4935-a786-382397f77a91.png)

here is the github link: https://github.com/cbyrneee/compact-chat

**Comment by Bswuave** [comment]
Another example here being how all these pings are different, lets use the auto clicker H and T message at the top, it would stack with the auto clicker message H and T on the bottom. If thats possible, I think it will make spammy chats alot cleaner
![2023-03-13_08 39 45](https://user-images.githubusercontent.com/126287004/224719225-189f4bc7-3652-4247-be4c-cac403b0e74e.png)

**Comment by mrbuilder1961** [comment]
does compact chat condense the messages within a certain amount, or just if it has ever been said before?
ex. if i had a 20 message long convo w/ someone and said "hi" at the beginning and then said "hi" to someone else who joined after the first convo, would it always condense "hi" into one message or only based on the message amount between them?

**Comment by Bswuave** [comment]
> does compact chat condense the messages within a certain amount, or just if it has ever been said before? ex. if i had a 20 message long convo w/ someone and said "hi" at the beginning and then said "hi" to someone else who joined after the first convo, would it always condense "hi" into one message or only based on the message amount between them?

I honesty don't know! I didn't get to use the mod long enough, I just saw that it smoothly can do something like that. frankly i would say yes though, so yea the hi from the beggining of your convo would condense with the hi at the end of your convo! That is what I was trying to explain above, yes!

**Comment by Bswuave** [comment]
Now idk maybe after so long like 30 lines of messages it would reset though, but I'd like to see for it to condense more recent messages :)

**Comment by Bswuave** [comment]
as of right now it literally checks every line, so if I had two messages condense and someone said something like HI! and then someone sent the same message again after they said HI! it would NOT condense (first photo in the thread for reference), I would like to see it condense :)
Sorry for so many replies, Im trying to give the best explanation I can!

**Comment by Bswuave** [comment]
Another thing that means it would do is it would literally move that duplicate message into one single message. I wish I had a gif to use, I might be able to grab one

**Comment by Bswuave** [comment]
[https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMTBlOGZiODUxMGRiMTk5Y2ViNzJjMWIzNGE0MDYyNWI5MzE4MmIwMyZjdD1n/b0DTrOE46dIfzi3ZEo/giphy.gif](url)

**Comment by Bswuave** [comment]
[<div style="width:100%;height:0;padding-bottom:57%;position:relative;"><iframe src="https://giphy.com/embed/b0DTrOE46dIfzi3ZEo" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/b0DTrOE46dIfzi3ZEo">via GIPHY</a></p>](url)

**Comment by Bswuave** [comment]
[https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTljNGU0ZTNkYWFmZmQ4OWUwMWM5YzY3MWI2M2Y5MzEzMDdjNjdiOSZjdD1n/gFJYlGkcoyS8Jjh9DN/giphy.gif](url)

**Comment by Bswuave** [comment]
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTljNGU0ZTNkYWFmZmQ4OWUwMWM5YzY3MWI2M2Y5MzEzMDdjNjdiOSZjdD1n/gFJYlGkcoyS8Jjh9DN/giphy.gif

**Comment by Bswuave** [comment]
![Example 1](https://user-images.githubusercontent.com/126287004/224887175-b3be68fd-bc06-4b9f-b24b-7261a0284400.gif)
I wish I could zoom in for you. But you kinda kinda see whats happening in the chat at the bottom
