### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mrbuilder1961/WheresMyChatHistory#69]
I'm unsure if this is related to chat patches mixing thing but had a problem with chat not working after running a certain command for spark. I made an issue on spark but I was going to also post the log here incase it had to do with chat patches. 

https://mclo.gs/h8CeqES

**Comment by mrbuilder1961** [comment]
what version of the mod are you using? a similar issue was discussed and supposedly fixed at #66, and that fix i believe was for mod versions 194.3.0 (mc 1.19.3-4)

**Comment by Aces-and-Jacks** [comment]
192.2.1

**Comment by Aces-and-Jacks** [comment]
oh, didn't realize that fix was for 1.19.3

**Comment by Aces-and-Jacks** [comment]
I'll try on that version and check

**Comment by Aces-and-Jacks** [comment]
well it was a weird issue that I accidentally caused but it might be related to that so I'll close for now and reopen if I come by it again. Sorry for the trouble and thanks for the response
