### ISSUE TITLE
suggestion to toggle military timestamp format

### ISSUE THREAD

**Issue by Bswuave** [mrbuilder1961/WheresMyChatHistory#70]
Can you make it to where we have the option to turn off the military format for the timestamps? Also at the moment whatever prefix you have saved for the time stamps, they reset after you exit the minecraft client.  Is there a way we can make that permanent or is that a bug?

**Comment by mrbuilder1961** [comment]
for the military time issue, go to the config -> help -> date/time formatting link, click and open the link, and look for the table that explains what text characters do what.

about the config not saving, that should not be happening at all. what mod version are you using and what mods do you have installed? actually, if you can attach a link on https://mclo.gs of the log when the config doesn't save, that would help fix the issue.

**Comment by Bswuave** [comment]
> for the military time issue, go to the config -> help -> date/time formatting link, click and open the link, and look for the table that explains what text characters do what.
> 
> about the config not saving, that should not be happening at all. what mod version are you using and what mods do you have installed? actually, if you can attach a link on https://mclo.gs of the log when the config doesn't save, that would help fix the issue.

Ahhh gotcha I was able to change it thank you! and I'm a scrub, I don't know how to find all that... unfortunately

**Comment by mrbuilder1961** [comment]
if i don't have any logs or version information then there's really nothing i can do until that information is provided.

**Comment by Bswuave** [comment]
> if i don't have any logs or version information then there's really nothing i can do until that information is provided.

Uh well I mean it could be I'm using flower symbols instead of brackets. Also its the lastest version. I personally don't mind and if anything this could be closed. But that's all the info I can really give aha

**Comment by mrbuilder1961** [comment]
ok, until any specifics are given i'm going to close this. feel free to attach a link to a log from when the issue occurred and i will reopen it (assuming it wasn't fixed already).
