### ISSUE TITLE
 Game crashed when chat opens on latest version of chatpatches

### ISSUE THREAD

**Issue by ghost** [mrbuilder1961/WheresMyChatHistory#73]
### Description
I was playing in my highly unstable modpack and tried to open chat after updating chatpatches (I was 2 version below latest before updating) and my minecraft crashed

### How to reproduce
Open chat

### Expected result
Crash with code:
The game crashed whilst ticking screen
Error: java.lang.IllegalAccessError: class obro1961.chatpatches.gui.ChatSearchScreen tried to access protected method 'void net.minecraft.client.gui.widget.ClickableWidget.setFocused(boolean)' (obro1961.chatpatches.gui.ChatSearchScreen and net.minecraft.client.gui.widget.ClickableWidget are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @58134517)

### Log file link
[latest.log](https://github.com/mrbuilder1961/ChatPatches/files/11184533/latest.log)

### Specs and Details
All of this in latest.log

**Comment by ghost** [comment]
Additional information:I can send messages, but only directly, without opening chat UI

**Comment by mrbuilder1961** [comment]
not entirely sure why this is happening, but in the meantime you can disable the chat search screen in the config. sorry about that, i'll try and figure this out soon

**Comment by ghost** [comment]
OK, thank you for the answer!

**Comment by mrbuilder1961** [comment]
assuming this builds successfully, try out the main jar from this link and lmk if you're still experiencing the issue: https://github.com/mrbuilder1961/ChatPatches/suites/12120118846/artifacts/638812155

**Comment by ghost** [comment]
No, I still experiencing this issue.  194.4.3 don't fixes it. It appears that I have this issue in my other, very small modpack. Maybe latest log from there can help?

**Comment by mrbuilder1961** [comment]
yeah, that log as a https://mclo.gs link would be great!

**Comment by ghost** [comment]
https://mclo.gs/IoS5nSL

**Comment by mrbuilder1961** [comment]
oh sorry im stupid, i only removed one part i was supposed to rather than all of them. i'll fix this tonight

**Comment by ghost** [comment]
That's ok, we all make mistakes. In programming it's a common thing. Good luck with working on your mod. It's very helpful and just great!

**Comment by mrbuilder1961** [comment]
ok try this one, should fix the issue: https://github.com/mrbuilder1961/ChatPatches/suites/12145070039/artifacts/640529483

**Comment by mrbuilder1961** [comment]
sorry it keeps auto-closing

**Comment by MultiverShaun** [comment]
Hi, I had this same issue on Quilt 1.19.3. The jar in the build above works for me!

**Comment by mrbuilder1961** [comment]
great! @variety754 could you confirm the second fie is working for you?

**Comment by ghost** [comment]
Yes, it's working!
