### ISSUE TITLE
Chat Heads - 1.19.4

### ISSUE THREAD

**Issue by RaptaG** [mrbuilder1961/WheresMyChatHistory#74]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Implement Chat Heads or similar function

**Describe alternatives you've considered**
Well you can always install Chat Heads separately.

**Additional context**

Modrinth URL of the mentioned mod: https://modrinth.com/mod/chat-heads

**Comment by mrbuilder1961** [comment]
potentially in the future if this is really wanted but see #43

**Comment by RaptaG** [comment]
Didn't read the closed issues sorry

**Comment by RaptaG** [comment]
Also, how will you know if this is really wanted in the future?
