### ISSUE TITLE
Suggestion for when you open chat to start typing it doesn't choose the search bar first

### ISSUE THREAD

**Issue by Bswuave** [mrbuilder1961/WheresMyChatHistory#76]
Im not sure if it was intended or not so I don't know if its a bug, but its annoying always having to click on the text bar when I want to send a message again instead of it just taking me to the text bar first. Another thing is when I open chat with the slash "/" it doesn't bring out the slash anymore when it should. Im assuming thats a bug though

**Comment by mrbuilder1961** [comment]
the auto-selecting the search bar is unintentional, i'll try and fix that soon. but what versión are you using because i thought already fixed the / not showing up when you type it?

**Comment by Bswuave** [comment]
> the auto-selecting the search bar is unintentional, i'll try and fix that soon. but what versión are you using because i thought already fixed the / not showing up when you type it?

194.4.0 !

**Comment by mrbuilder1961** [comment]
ok both of these issues should be fixed in 194.3.3, which will be released in about 15 minutes!
