### ISSUE TITLE
Make chat links clickable - 1.19.4

### ISSUE THREAD

**Issue by RaptaG** [mrbuilder1961/WheresMyChatHistory#77]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make URLs sent in the chat clickable

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mrbuilder1961** [comment]
that's a great idea! will definitely add this!

**Comment by RaptaG** [comment]
Nice!

**Comment by Bswuave** [comment]
wait were they already not??

**Comment by mrbuilder1961** [comment]
i don't think so, but if it isn't then at the very least i'm going to make them clearly highlighted so you know you can click them
