### ISSUE TITLE
Chat Search HUD Removes No Chat Reports Signing Mode Button - 1.19.4

### ISSUE THREAD

**Issue by MultiverShaun** [mrbuilder1961/WheresMyChatHistory#78]
### Description
When the chatSearchScreen config option is set to true, the No Chat Reports Signing Mode button located on the right end of the chat HUD (as shown below), as well as the encryption button, are not shown.
![image](https://user-images.githubusercontent.com/68468439/232530239-f50bf914-f956-4cec-992d-5b5a040b6078.png)

### How to reproduce

1. Ensure that Chat Patches and No Chat Reports are both installed, and that the Chat Patches chatSearchScreen config option is set to true
2. Open chat and notice that there is no Signing Mode button in the HUD
3. Set the chatSearchScreen config option to false
4. Notice how the Signing Mode button appears in the chat HUD

### Expected result
The signing mode button remains visible even if the chatSearchScreen config option is set to true

### Log file link
No log file errors

### Specs and Details
Required information:
- Microsoft Windows 11 10.0.22621
- Chat Patches 194.4.3 (1.19.4)
- Quilt Loader 0.18.10 (QFAPI 6.0.0-beta.3 and QSL 5.0.0-beta.2)
- YetAnotherConfigLib 2.4.1, ModMenu 6.1.0
- Mods: ![image](https://user-images.githubusercontent.com/68468439/232528821-8db4ca9a-8623-4fb9-a938-4a7e779d98c5.png)

### Additional context
N/A

**Comment by mrbuilder1961** [comment]
this is probably going to take a while to fix, bc the searchable chat screen is completely different from the vanilla one and NCR modifies the vanilla one. 
in the meantime, if any NCR settings aren't working you probably need to disable the new screen under Settings -> HUD

**Comment by MultiverShaun** [comment]
Got it, thanks!

**Comment by mrbuilder1961** [comment]
should be fixed this weekend!
