### ISSUE TITLE
weird text color and shading

### ISSUE THREAD

**Issue by EGOIST1372** [mrbuilder1961/WheresMyChatHistory#8]
the time stamp color and shading is weird 
latest 1.18.2 version
![image](https://user-images.githubusercontent.com/86555131/158546466-cb8282b6-bbfc-445e-8bae-bd361726c555.png)

**Comment by mrbuilder1961** [comment]
- does this happen for any color you set the timestamp to?
- what is the current timestamp color?
- is the boundary line also behaving weird or is it just black?

**Comment by EGOIST1372** [comment]
All parameters were default
I deleted the config file and it got fixed
It's better to mention on changelog in curseforge that config file in config folder should get delete if you update from an old version even 1.18.1 considered old in this case
you can close the issue after reading it
![image](https://user-images.githubusercontent.com/86555131/158620356-8379a667-a531-4dbf-9025-02f164c6e446.png)

**Comment by mrbuilder1961** [comment]
that's really odd, but i'm glad it fixed.
