### ISSUE TITLE
Lunar Client-style chat message appearance animation 

### ISSUE THREAD

**Issue by Nukecraft5419** [mrbuilder1961/WheresMyChatHistory#82]
**Is your feature request related to a problem? Please describe.**
I would like that animation to make the chat better 

**Describe the solution you'd like**
An animation when making chat messages inspired by that mod in Lunar Client

**Describe alternatives you've considered**
https://www.curseforge.com/minecraft/mc-mods/better-chat

**Additional context**
And all on the mod page I put the link

**Comment by JustAHuman-xD** [comment]
This is a duplicate suggestion, close and see #75

**Comment by Nukecraft5419** [comment]
Thank you very much I hope you will I am migrating to your mod for my modpack
