### ISSUE TITLE
Again : Search option - 194.4.5

### ISSUE THREAD

**Issue by NoltoxGit** [mrbuilder1961/WheresMyChatHistory#83]
There is always a problem following my isssue  https://github.com/mrbuilder1961/ChatPatches/issues/81.

Now there is no more magnifying glass to search, but there is still the grey background that is integrated with it :
![image](https://user-images.githubusercontent.com/75265787/235683930-8b3a957b-db7c-4c75-a20f-ac42073d16d3.png)

**Comment by mrbuilder1961** [comment]
fixed in about 15 minutes!
