### ISSUE TITLE
Vanilla chat clearing

### ISSUE THREAD

**Issue by Soochaehwa** [mrbuilder1961/WheresMyChatHistory#85]
### Description
I turned off the chat log toggle, but chat logs remain

![2023-05-06_21 02 23](https://user-images.githubusercontent.com/43947445/236623320-dc43097c-f529-448f-8e4f-be48b319c855.png)

![2023-05-06_21 02 06](https://user-images.githubusercontent.com/43947445/236623302-da7f343e-9abe-45bd-9f57-7b8b07a37d29.png)

![2023-05-06_21 02 12](https://user-images.githubusercontent.com/43947445/236623294-c88d2f5f-1a75-4053-b919-d93653adfa24.png)

### Specs and Details
Required information:
- Computer OS: windwos11
- Mod version: 194.4.6
- Fabric and API versions: 0.14.19 / 0.80.0+1.19.4
- YetAnotherConfigLib and Mod Menu versions (if installed): 2.5.1+1.19.4
- List of all installed mods: 
![1571](https://user-images.githubusercontent.com/43947445/236623350-4ef37d58-e067-49bf-a176-7b1efa3850a8.png)

**Comment by mrbuilder1961** [comment]
are those screenshots from the same game session or did you take one, exit the game, and then take another one?

**Comment by Soochaehwa** [comment]
I don't know what you mean by same game session, but
This is a screenshot taken after reconnecting to the server without exit the game.
What I want is to have the chat history disappear when I reconnect to the server like vanilla, but isn't the chat log toggle that feature?

**Comment by mrbuilder1961** [comment]
oh sorry, there's been a misunderstanding. the chat log toggle refers to saving messages from the chat history to a file, so when you close and reopen the game later, it will re-add all of your messages to stay in the chat.

i think what you want is for the in-game history to clear like vanilla. currently this isn't toggleable, because most people think it's very annoying.

**Comment by Soochaehwa** [comment]
If so, are there any plans to add that feature in the future?
