### ISSUE TITLE
Using arrow keys for chat history switches focus

### ISSUE THREAD

**Issue by Reizaru404** [mrbuilder1961/WheresMyChatHistory#86]
it is very inconvenient when you scroll through the previous commands with the arrows on the keyboard and cannot edit them because the search bar is highlighted instead of the command line

**Comment by mrbuilder1961** [comment]
when i open the chat and try to use the arrow keys it only selects the chat field, could you send a video or gif of the issue please?

**Comment by Reizaru404** [comment]
I checked it again and noticed that the chat may or may not stand out. It also happens that no input field is highlighted. This happens if you scroll a lot with the up and down arrows. My problem is that when you open the chat, press up ONCE for the previous command and try to change it, nothing comes out. You can't print. It's quite inconvenient.

**Comment by Reizaru404** [comment]
https://github.com/mrbuilder1961/ChatPatches/assets/93148626/bc9416d3-6492-472e-bd62-7678791d76d8

**Comment by mrbuilder1961** [comment]
ohhh i see what you mean. will be fixed in the future 👍

**Comment by mrbuilder1961** [comment]
was it fixed already or something?

**Comment by mrbuilder1961** [comment]
i was working on the new update and realized what you were talking about, this is pretty annoying so i'll try to fix it.

**Comment by mrbuilder1961** [comment]
release for this isnt going to be out for a little bit, so here is a link to the hotfix: https://github.com/mrbuilder1961/ChatPatches/suites/13337267304/artifacts/729047236
