### ISSUE TITLE
Config wont save

### ISSUE THREAD

**Issue by RimonsVirginity** [mrbuilder1961/WheresMyChatHistory#9]
im not sure if this is just me but i try to change the config and every time I reload my game it resets my settings

**Comment by mrbuilder1961** [comment]
Could you provide a log file or a video please? I'll try my best but this is a somewhat vague problem.

**Comment by RimonsVirginity** [comment]
yes, here is the best way i can describe it. 
all i want is the server chat history and the time stamps. but every time i restart my game it messes with the chat layout and messes with colors 
here is a video: https://youtu.be/KUUh6L6Jdeo

**Comment by RimonsVirginity** [comment]
yea, here is a video. brief description: all i want is the time stamps and history, it keeps reseting my config and messing with the chat format
https://youtu.be/0NIdZkly56w

*if you cant watch it, just give it like a min to upload*

**Comment by RimonsVirginity** [comment]
> yea, here is a video. brief description: all i want is the time stamps and history, it keeps reseting my config and messing with the chat format https://youtu.be/0NIdZkly56w
> 
> _if you cant watch it, just give it like a min to upload_

and yes i have tried just setting the others to false, it does the same thing

**Comment by mrbuilder1961** [comment]
Okay I think I have an understanding of the problem, but just to clarify you only want the timestamp and chat history feature but when you save the config it messes up the chat formatting?

**Comment by RimonsVirginity** [comment]
> Okay I think I have an understanding of the problem, but just to clarify you only want the timestamp and chat history feature but when you save the config it messes up the chat formatting?

yes, i have an issue with the saving part of it.  it just won't save my settings in my config. Evertime i restart my game it resets the config file

**Comment by mrbuilder1961** [comment]
Okay so I think what's happening is when you go to edit the config file, you delete the settings you want disabled. The mod is then most likely trying to get the data of those missing options and then regenerates the file and mistakenly overwrites the old settings. Could you try setting all of the options you don't want (`hover`, `boundary`) to `false` instead of deleting them from the file? Also, make sure the mod version is the latest for your Minecraft version, let me know if that works.

**Comment by RimonsVirginity** [comment]
> Okay so I think what's happening is when you go to edit the config file, you delete the settings you want disabled. The mod is then most likely trying to get the data of those missing options and then regenerates the file and mistakenly overwrites the old settings. Could you try setting all of the options you don't want (`hover`, `boundary`) to `false` instead of deleting them from the file? Also, make sure the mod version is the latest for your Minecraft version, let me know if that works.

somehow i managed to fix it by keeping the boundaries
![image](https://user-images.githubusercontent.com/89324357/168485928-eff8d53b-4d39-4245-9ccb-e5830373696b.png)
 i dont know why this fixes it but i guess it does?

**Comment by RimonsVirginity** [comment]
> Okay so I think what's happening is when you go to edit the config file, you delete the settings you want disabled. The mod is then most likely trying to get the data of those missing options and then regenerates the file and mistakenly overwrites the old settings. Could you try setting all of the options you don't want (`hover`, `boundary`) to `false` instead of deleting them from the file? Also, make sure the mod version is the latest for your Minecraft version, let me know if that works.

i have tried this but it reset upon restart

**Comment by mrbuilder1961** [comment]
Could you try deleting the file and reloading Minecraft so it can regenerate it and then altering the settings?
