### ISSUE TITLE
Incompatible with YACL v3.x

### ISSUE THREAD

**Issue by RosivDamotil** [mrbuilder1961/WheresMyChatHistory#91]
### Description
When starting a world in Minecraft (online server to be precise) it saves and quits the client.
Error message (below) is the only hint to the problem.
Nothing visible at all.

### How to reproduce
Start Minecraft, start a world -> Minecraft shuts down.

### Expected result
Minecraft enters the world.

### Log file link
[2023-06-10-5.log](https://github.com/mrbuilder1961/ChatPatches/files/11714525/2023-06-10-5.log)

### Specs and Details
Required information:
- macOS 13.4
- Mod version 194.4.6
- Fabric 0.14.21 and API 0.83.0 versions 
- Mod Menu 6.2.2 version
- List of all installed mods (can be a list *copied* from a log file **OR** a screenshot of the mods folder)

3dskinlayers-fabric-1.5.3-mc1.19.4.jar
advancementinfo-1.19.4-fabric0.76.0-1.3.1.jar
AdvancementPlaques-1.19.4-fabric-1.4.9.jar
AmbientSounds_FABRIC_v5.2.19_mc1.19.4.jar
anvilrestoration-1.19.4-2.0.jar
appleskin-fabric-mc1.19.4-2.4.3.jar
architectury-8.1.87-fabric.jar
areas-1.19.4-4.3.jar
balm-fabric-1.19.4-6.0.2.jar
BetterF3-6.0.2-Fabric-1.19.4.jar
betterthanmending-1.3.0.jar
BetterTridents-v6.0.0-1.19.4-Fabric.jar
Bookshelf-Fabric-1.19.4-18.0.4.jar
BuildGuide-1.19.4-0.3.3.jar
carryon-fabric-1.19.4-2.0.5.20.jar
cem-0.7.3.jar.disabled
chat_heads-0.10.14-fabric-1.19.4.jar
chatpatches-194.4.6.jar.disabled
cloth-config-10.0.96-fabric.jar
collective-1.19.4-6.54.jar
completeconfig-2.3.1.jar
continuity-3.0.0-beta.2+1.19.3.jar
Controlling-fabric-1.19.4-11.1.5.jar
copperhopper-0.2.0+1.19.4.jar
crawl-0.11.5.jar
CreativeCore_FABRIC_v2.10.12_mc1.19.4.jar
cyclepaintings-1.19.4-3.2.jar
DarkPaintings-Fabric-1.19.4-15.0.1.jar
elytraslot-fabric-6.2.1+1.19.4.jar
enchantment-lore-1.3.1+MC1.19.3-1.19.4.jar
enhancedblockentities-0.8+1.19.3.jar.disabled
enhancedblockentities-0.81.19.4.jar
entity_model_features_fabric_1.19.4-0.2.9.jar
entity_texture_features_fabric_1.19.4-4.4.4.jar
fabric-api-0.83.0+1.19.4.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
fabricskyboxes-0.7.1+mc1.19.4.jar
fallingleaves-1.15.0+1.19.4.jar
FallingTree-1.19.4-3.12.2.jar
firstperson-fabric-2.2.3-mc1.19.4.jar
ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric.jar
fsb-interop-1.3.1+mc1.19.4-build.33.jar
Iceberg-1.19.4-fabric-1.1.9.jar
idwtialsimmoedm-0.2.0+1.19.4.jar
indium-1.0.18+mc1.19.4.jar
infinitetrading-1.19.4-4.0.jar
iris-mc1.19.4-1.6.3.jar
Jade-1.19.4-fabric-10.3.1.jar
justmobheads-1.19.4-7.1.jar
justplayerheads-1.19.4-3.1.jar
Kambrik-6.0.0-beta.2+1.19.4-fabric.jar
LegendaryTooltips-1.19.4-fabric-1.4.3.jar
libraryferret-fabric-1.19.4-4.0.0.jar
lithium-fabric-mc1.19.4-0.11.1.jar
mcw-paintings-1.0.4-mc1.19.4fabric.jar
midnightlib-fabric-1.3.0.jar
MobPlaques-v6.0.0-1.19.4-Fabric.jar
modmenu-6.2.2.jar
namepain-1.4.0 fabric-1.19.4.jar
nostrip-1.2.3-1.19+.jar
open-parties-and-claims-fabric-1.19.4-0.17.3.jar
peek-1.19.4-1.0.5.jar
phosphor-fabric-mc1.19.x-0.8.1.jar.disabled
plushie-mod-1.2.1.jar
PresenceFootsteps-1.8.2.jar
Prism-1.19.3-fabric-1.0.4.jar
PuzzlesLib-v6.0.9-1.19.4-Fabric.jar
realisticbees-1.19.4-3.4.jar
reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
RoughlyEnoughItems-11.0.617.jar
scaffoldingdropsnearby-1.19.4-3.0.jar
Searchables-fabric-1.19.4-1.0.3.jar
show-me-your-skin-1.6.3+1.19.4.jar
sodium-extra-0.4.18+mc1.19.4-build.100.jar
sodium-fabric-mc1.19.4-0.4.10+build.24.jar
soundphysics-fabric-1.19.4-1.1.1.jar
stackables-1.1.1+1.19.4.jar
stacker-3.1.0-1.19.4.jar
starlight-1.1.1+fabric.ae22326.jar
status-effect-bars-1.0.2.jar
TexelsPaintings-fabric-1.19.4-8.2.0.jar
Time To Live 0.5 (1.19.4)-0.5.jar
trade-cycling-fabric-1.19.4-1.0.5.jar
travelers-backpack-1.19.4-8.4.4.jar
trinkets-3.6.0.jar
VillagersPlus_1.10_(FABRIC)_for_1.19.4.jar.disabled
voicechat-fabric-1.19.4-2.4.8.jar
voidtotem-fabric-1.19.4-2.3.0.jar
waveycapes-fabric-1.3.2-mc1.19.3.jar
waystones-fabric-1.19.4-13.1.0.jar
Xaeros_Minimap_23.4.4_Fabric_1.19.4.jar
XaerosWorldMap_1.30.3_Fabric_1.19.4.jar
yet-another-config-lib-fabric-3.0.0-beta.2+1.19.4.jar
your-reputation-0.2.1+jade.1.19.jar
youre-in-grave-danger-1.6.0.jar

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
Run on Mac in PrismLauncher. Latest versions.

**Comment by mrbuilder1961** [comment]
your issue was formatted terribly and in an unhelpful way, please update it according to the new template provided in the edit. thank you.

**Comment by mrbuilder1961** [comment]
i apologize that was pretty rude of me. in the future, i would just appreciate following the provided templates to get any issues resolved sooner. thanks!

**Comment by RosivDamotil** [comment]
Never mind.
Guess you were right anyway. ;)

**Comment by mrbuilder1961** [comment]
it's because Chat Patches `v194.4.6` isn't updated to use the latest version of YetAnotherConfigLib yet. until the next update releases, you will have to use YACL `v2.5.1-1.19.4`. sorry for the inconvenience 🫤

**Comment by Bswuave** [comment]
> it's because Chat Patches `v194.4.6` isn't updated to use the latest version of YetAnotherConfigLib yet. until the next update releases, you will have to use YACL `v2.5.1-1.19.4`. sorry for the inconvenience 🫤

speaking of, is there a version for 1.20 in the works ?

**Comment by mrbuilder1961** [comment]
yes, it will be updated soon! if you want more updates and details, you should [join the discord](https://discord.gg/3MqBvNEyMz)!
