### ISSUE TITLE
Chat doesnt show up - 194.5.0

### ISSUE THREAD

**Issue by AlfmanOO7** [mrbuilder1961/WheresMyChatHistory#96]
### Description
No **chat** messages will appear when I or others type in chat. My messages still get through (have checked using a linked discord channel), but all I see in my chat is my join message and some server messages (like /msg, /away, etc). This is only a server issue, I get chat messages fine on singleplayer (see attached image)
![issues](https://github.com/mrbuilder1961/ChatPatches/assets/62825044/ddeddd9f-91ae-42f4-9adb-ed557ddcfb0a)

### How to reproduce
join any server
send/receive messages
nothing appears

### Expected result
you see the chat messages

### Log file link
https://mclo.gs/FnK6a4S

### Specs and Details
Required information:
- Windows 10 Pro
- 194.5.0
- Quilt Loader 0.19.2 Beta 7 (MC1.19.4) & QFAPI 6.0.0 Beta 9
- YACL 3.0.4 & ModMenu 6.2.3
- Mods:
3D Skin Layers
Adaptive Tooltips
Advancement Plaques
AdvancementsInfo
Ambient Sounds
Animatica
Appleskin
Architectury
Armor Chroma for Fabric
AuthMe
Auto Clicker
Better F3
Better Mount HUD
Better Ping Display
Better Statistics Screen
Blur
Bobby
Borderless Mining
Camera Overhaul
Camera Utils
Chat Heads
Chat Patches
CITResewn
Client Side Noteblocks
Cloth Config
Colorful Hearts
Colorful Subtitles
Colour My Servers
Complete Config
Continue (Button)
Continuity
CreativeCore
Dark Loading Screen
Death Log
Do a Barrel Roll
Durability Notifier
Dynamic App Icon
Dynamic Crosshair
Dynamic Sound Filters
Eating Animation
EnhancedVisuals
Entity Model Features
Entity Texture Features
Equipemt Compare
Fabric Carpet
Fabric Language Kotlin
Falling Leaves
FerriteCore
First Person Model
Forge Config API Port
Fuel Info
Iceberg
Indium
Inspecio
Inventory HUD+
Iris (Shaders)
Item Borders
Item Scroller
Item Swapper
Legendary Tooltips
Litematica
Lithium
Make Bubbles Pop
MaLiLib
Mambience
MemoryLeakFix
Minihud
Mixin Trace
Mod Menu
NBT Autocomplete
No Chat Reports
Not Enough Animations
OptiGUI
oωo (owo-lib)
Physics Mod
Presence Footsteps
Prism
Quilted Fabric API &   Quilt Standard Libraries
Reese's Sodium Options
Remote Players
Replay Mod
Satin API
Seamless
Shulker Pick
Shulkerbox Tooltip
Simple Shulker Preview
SmoothBoot
SmoothSwapping
Sodium Extra
Sodium Fabric
Spyglass Astronomy
Starlight
Stendhal
Tiny Item Animations
Travellers Toasts
Tweakeroo
Visuality
Void Fog
Wavey Capes
Xaero's Minimap
Xaero's World Map
Yet Another Config Lib
Zoomify
LambDynamicLights

**Comment by mrbuilder1961** [comment]
do you have any images of what the messages look like without the mod installed, the ones you can't see?

**Comment by AlfmanOO7** [comment]
![image](https://github.com/mrbuilder1961/ChatPatches/assets/62825044/06b9def1-f04a-41d9-8a8a-256e665d0178)
^here 
I'm gonna mess around with removing other mods to see if I can find an incompatibility

**Comment by mrbuilder1961** [comment]
ok ill work on this, do you know what mod/plugin changes your name color? or is that a scoreboard/team thing?

**Comment by AlfmanOO7** [comment]
Name colours are done by LuckPerms

**Comment by AlfmanOO7** [comment]
I have done more testing.
The issue is not present on:

- Vanilla Servers
- 'Clean' Paper Servers
- Singleplayer

removing AuthMe and NoChatReports (individually) did not resolve the issue

**Comment by mrbuilder1961** [comment]
could you try removing LuckPerms and/or disabling that name changer thing as well? i can't use my computer rn but tomorrow i can build a debug file w some loggers to help fix this issue.

**Comment by AlfmanOO7** [comment]
Unfortunately, I am not an Admin on the server in question, so I am unable to change that. All I have been able to do is run a paper-only server to test on (no additional plugins). I could attempt to run a paper server with _just_ LuckPerms, however, my knowledge of how plugins work is limited, and I also don't know the exact configs used by my server. For now, the previous version of ChatPatches is working.

**Comment by mrbuilder1961** [comment]
ok, could you load this and send me the log after it errors? it doesn't try to fix it, but it logs some information for me to look at.
the only difference is adding logpoints and changing the version. the sources file ends in `-sources` and the runnable is the other one.
thanks!
[libs.zip](https://github.com/mrbuilder1961/ChatPatches/files/11970240/libs.zip)

**Comment by AlfmanOO7** [comment]
[latest.log](https://github.com/mrbuilder1961/ChatPatches/files/11974361/latest.log)
Here's the log after using that jar

**Comment by mrbuilder1961** [comment]
ok, so i don't know what is causing this specific error but i can see the problem. but i'm wondering, do you have show advanced tooltips on?

(https://mclo.gs/bZMAK2H)

**Comment by mrbuilder1961** [comment]
i can maybe look into this more tomorrow

**Comment by AlfmanOO7** [comment]
> ok, so i don't know what is causing this specific error but i can see the problem. but i'm wondering, do you have show advanced tooltips on?
> 
> (https://mclo.gs/bZMAK2H)

Yes I have it on

**Comment by mrbuilder1961** [comment]
the issue seems to be that luckperms reformats the message to have the custom color in a different type of message. that really isn't too hard of an issue to fix, but it strips player data from the name (unlike vanilla, which adds some info you can see with advanced tooltips enabled).

if i can find a way to access the formatter luckperms uses to create the message, it should be pretty easy. however, idrk how to do that, so i'll have to do some digging.

**Comment by AlfmanOO7** [comment]
good that you've figured out the issue. no worries if it takes a while to resolve it, thanks for looking into it!

**Comment by mrbuilder1961** [comment]
ok try this for me and send the log!
*edit2: i made some other changes so try this one instead:*
**[libs.zip](https://github.com/mrbuilder1961/ChatPatches/files/11990839/libs.zip)**

**Comment by AlfmanOO7** [comment]
sorry its taken me while to get back to you, had a very busy weekend. Here's the log: 
https://mclo.gs/SFQogYn

not sure if it's part of the debug version, or if you even intended this to happen, player names appeared twice: 
![image](https://github.com/mrbuilder1961/ChatPatches/assets/62825044/fdfb9db4-b54c-4e9d-acbd-cb26fe6ebfe0)

**Comment by mrbuilder1961** [comment]
huh, that's odd. thanks for getting back to me, i'll take a look later today when i have some free time.

edit: i just remembered, could you check and see if you can hover over your (chat patches formatted) name and see if it has the proper tooltip/click event? thanks 😊

**Comment by mrbuilder1961** [comment]
hey, so i checked the log, and it didnt have any extra data, which doesn't make sense because what i added always logs something. it looks like you loaded the old version by accident, but that's okay because i added a couple more logpoints anyway just in case.
heres another updated file: (sorry theres no other way i know of 😣) 
for @AlfmanOO7 : [libs.zip](https://github.com/mrbuilder1961/ChatPatches/files/12009463/libs.zip)

**Comment by AlfmanOO7** [comment]
another log: https://mclo.gs/OKFg1it

Hopefully its correct this time

**Comment by mrbuilder1961** [comment]
ok great, thanks! i think i know how to remove the duped name, so i'll send another dev file later today, and when i do could you just lmk if it's working and send the log? i'll test as much as possible on my end too, of course 😄

**Comment by mrbuilder1961** [comment]
ok i think this should work now!!!! please lmk asap if there are any more issues!
** @AlfmanOO7 => [libs.zip](https://github.com/mrbuilder1961/ChatPatches/files/12022387/libs.zip)**

**Comment by AlfmanOO7** [comment]
~~seems to work~~, player name colours aren't carried over, but I can fix that in the configs (all players will be same colour, but thats only an issue for admins and moderators) here's the log: [Log](https://mclo.gs/dHbyyps,) I did encounter a crash when clicking on the time stamp decoration text config, here's the crash log for that if its something you didnt know about: [Crash](https://mclo.gs/83WPh7z)

**Comment by AlfmanOO7** [comment]
Ok, turns out the crash occurs when I do anything in the mod's config menu, all the logs are the same though

~~Edit:
More testing has lead me to find that messages sent via discord now cause me to crash: [Crash Report](https://mclo.gs/ZgTEm3q); [Log](https://mclo.gs/odViAT8)~~
Didn't read those crash reports hard enough before posting here, issue was with EMF not Chat Patches it seems, just a conincidence

**Comment by mrbuilder1961** [comment]
yeah the crash is what i was talking about in the discord and why `194.5.0` doesn't have preview images (https://github.com/isXander/YetAnotherConfigLib/issues/87), I was just testing it at the same time and forgot to remove it from the debug jar, my bad. however, about the colors being erased, I think i might just have to put that on the backburner for now because i don't know how well that will mix with the config name format (because you can add colors there too) but i will try.

but other than that stuff, is everything else working okay?

**Comment by AlfmanOO7** [comment]
I haven't had any issues other than the crash, so I'd say so, thanks!
