### ISSUE TITLE
Crash on 1.19.3 - YACL 3.x - 194.5.0

### ISSUE THREAD

**Issue by whitebear60** [mrbuilder1961/WheresMyChatHistory#97]
### Description
Chat Patches on 1.19.3 won't launch on the latest version because Yet Another Config Lib 3.0 isn't available for that version, and it explicitly states in the requirements the requirement of 3.0 and up

### How to reproduce
1. Install the latest Chat Patches and Yet Another Config Lib for 1.19.3 (194.5.0 and 2.2.0 at the time of mee writing this issue)
2. Try launching the game

### Expected result
The game should launch properly

### Log file link
https://mclo.gs/y8lsS0f

### Specs and Details
Required information:
- Computer OS: macOS 13.4.1
- Mod version: 194.5.0
- Fabric and API versions: Quilt 0.19.2; API 5.0.0-beta.9+0.76.0-1.19.3
- YetAnotherConfigLib and Mod Menu versions (if installed): 2.2.0; 5.1.0-beta4
- List of all installed mods (can be a list *copied* from a log file **OR** a screenshot of the mods folder)
https://mclo.gs/1G06hMF

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`)
```json
{
  "time": true,
  "timeDate": "h:mm a",
  "timeFormat": "[$]",
  "timeColor": 2867199,
  "hover": true,
  "hoverDate": "MM/dd/yyyy",
  "hoverFormat": "$",
  "hoverColor": 16777215,
  "counter": true,
  "counterFormat": "\u00268(\u00267x\u0026e$\u00268)",
  "counterColor": 16777045,
  "boundary": true,
  "boundaryFormat": "\u00268[\u0026b$\u00268]",
  "boundaryColor": 5636095,
  "saveChat": false,
  "shiftChat": 10,
  "chatWidth": 0,
  "nameFormat": "\u003c$\u003e",
  "maxMsgs": 16384,
  "messageDrafting": false,
  "searchDrafting": true
}
```

### Additional context
Possible solutions I can think about: either bump all Chat Patches that are built for YACL v3 as incompatible with 1.19.3 or make it so it still loads with 2.2.0, if compatible

**Comment by whitebear60** [comment]
YACL 3.0 is available only for 1.19.4 and up

**Comment by mrbuilder1961** [comment]
i might just have to mark it incompatible, but i'll see if there's any way to make yacl work in 1.19.3

**Comment by whitebear60** [comment]
If you'll mark it as incompatible, probably would be better to mark all the versions with yacl 3.0 as incompatible to avoid updating to an incompatible versions with tools such as prism launcher

**Comment by mrbuilder1961** [comment]
ok i marked `194.5.0` as incompatible with 1.19.3 and future versions will also not allow it. however, the jar itself will not prevent 1.19.3 from trying to load, so until 194.5.1, only you or the launcher can control if it should be added to the mods list.

btw, try to update to 1.19.4 if possible! most (*updated*) mods should have it available.
